"use client";

import { AlertTriangle, BadgeDollarSign, BookOpenCheck, CalendarClock, FileText, Megaphone, Receipt, ShieldCheck, UsersRound } from "lucide-react";
import { useAccounting } from "../../lib/accounting-context";
import { unprocessedSourceEvents } from "../../lib/accounting-engine";
import { useFinance } from "../../lib/finance-context";
import { useHcm } from "../../lib/hcm-context";
import { canManageEmployee } from "../../lib/hcm-engine";
import { useMarketing } from "../../lib/marketing-context";
import { usePerformance } from "../../lib/performance-context";
import { reportVisibleTo } from "../../lib/performance-engine";
import type { PageKey } from "../../lib/types";
import { useWorkspace } from "../../lib/workspace-context";
import { Button, Section, StatusPill, formatDate, formatMoney } from "../ui";

type ActionItem = { id: string; title: string; detail: string; category: string; page: PageKey; urgency: "Blocking" | "Due" | "Review" | "Watch"; icon: typeof AlertTriangle };
const urgencyTone = (urgency: ActionItem["urgency"]) => urgency === "Blocking" ? "danger" as const : urgency === "Due" ? "warning" as const : urgency === "Review" ? "info" as const : "neutral" as const;
const urgencyRank: Record<ActionItem["urgency"], number> = { Blocking: 0, Due: 1, Review: 2, Watch: 3 };

export function ActionCenter() {
  const { data, scope, currentUser, navigate } = useWorkspace(); const { hcm } = useHcm(); const { performance } = usePerformance(); const { finance } = useFinance(); const { state: marketing } = useMarketing(); const { accounting, events } = useAccounting();
  if (!currentUser || currentUser.role === "Customer") return null;
  const admin = currentUser.role === "Administrator"; const manager = currentUser.role === "Sales Manager"; const actions: ActionItem[] = []; const today = new Date().toISOString().slice(0, 10);
  for (const task of hcm.tasks.filter((task) => task.status === "Open" && (task.ownerId === currentUser.id || admin))) actions.push({ id: `hcm:${task.id}`, title: task.title, detail: task.detail, category: "Human Resources", page: "people", urgency: task.dueDate && task.dueDate < today ? "Due" : "Review", icon: UsersRound });
  if (admin || manager) for (const request of hcm.workflows.filter((request) => request.status === "Submitted" && request.userId !== currentUser.id && canManageEmployee(currentUser, request.userId, data))) actions.push({ id: `hr-request:${request.id}`, title: request.title, detail: `${data.users.find((user) => user.id === request.userId)?.name ?? "Employee"} · ${request.type}`, category: "Human Resources", page: "people", urgency: "Review", icon: UsersRound });
  for (const report of performance.reports.filter((report) => report.status === "Submitted" && report.userId !== currentUser.id && reportVisibleTo(currentUser, report, data))) { const author = data.users.find((user) => user.id === report.userId); actions.push({ id: `report:${report.id}`, title: `Review ${report.type.toLowerCase()} report`, detail: `${author?.name ?? "Employee"} · submitted ${formatDate(report.submittedAt, { month: "short", day: "numeric" })}`, category: "Performance", page: "reports", urgency: "Review", icon: FileText }); }
  for (const expense of finance.expenses) { const requester = data.users.find((user) => user.id === expense.requesterId); const managerCan = manager && expense.requesterId !== currentUser.id && (requester?.managerId === currentUser.id || requester?.team === currentUser.team); if (expense.status === "Submitted" && (admin || managerCan)) actions.push({ id: `expense-manager:${expense.id}`, title: "Review business expense", detail: `${requester?.name ?? "Employee"} · ${expense.merchant} · ${formatMoney(expense.amount)}`, category: "Finance", page: "finance", urgency: "Review", icon: Receipt }); else if (expense.status === "Manager approved" && admin) actions.push({ id: `expense-finance:${expense.id}`, title: "Finance approval required", detail: `${expense.merchant} · ${formatMoney(expense.amount)}`, category: "Finance", page: "finance", urgency: "Review", icon: Receipt }); else if (expense.status === "Finance approved" && admin) actions.push({ id: `expense-pay:${expense.id}`, title: "Reimbursement ready for payment", detail: `${requester?.name ?? "Employee"} · ${formatMoney(expense.amount)}`, category: "Finance", page: "finance", urgency: "Due", icon: BadgeDollarSign }); }
  if (admin) { for (const request of marketing.requests.filter((item) => item.status === "Submitted")) actions.push({ id: `marketing-request:${request.id}`, title: "Marketing request needs review", detail: request.title, category: "Marketing", page: "marketing", urgency: "Review", icon: Megaphone }); for (const campaign of marketing.campaigns.filter((item) => item.status === "Awaiting approval")) actions.push({ id: `campaign:${campaign.id}`, title: "Campaign budget needs approval", detail: `${campaign.name} · ${formatMoney(campaign.requestedBudget)}`, category: "Marketing", page: "marketing", urgency: "Review", icon: Megaphone }); for (const spend of marketing.spend.filter((item) => item.status === "Submitted")) actions.push({ id: `marketing-spend:${spend.id}`, title: "Marketing spend needs approval", detail: `${formatMoney(spend.amount)} · ${spend.businessPurpose}`, category: "Marketing", page: "marketing", urgency: "Review", icon: Megaphone }); for (const event of unprocessedSourceEvents(accounting, events)) actions.push({ id: `accounting:${event.id}`, title: event.blockedReason ? "Accounting policy required" : "Accounting event ready", detail: event.blockedReason ?? event.description, category: "Accounting", page: "finance", urgency: event.blockedReason ? "Blocking" : "Review", icon: BookOpenCheck }); }
  if (admin || manager || currentUser.role === "Operations") for (const appointment of scope.appointments.filter((item) => item.status === "Scheduled" && !item.ownerId && item.date <= today)) { const location = data.accounts.find((account) => account.id === appointment.accountId); actions.push({ id: `dispatch:${appointment.id}`, title: "Unassigned scheduled work", detail: `${location?.locationName ?? location?.name ?? "Location"} · ${appointment.date} ${appointment.startTime}`, category: "Dispatch", page: "dispatch", urgency: appointment.date < today ? "Blocking" : "Due", icon: CalendarClock }); }
  for (const lot of scope.inventory.filter((lot) => lot.status === "Quality hold")) actions.push({ id: `hold:${lot.id}`, title: "Inventory quality hold", detail: `${lot.lotCode} · ${lot.onHand} cases unavailable`, category: "Inventory", page: "inventory", urgency: "Blocking", icon: ShieldCheck });
  actions.sort((a, b) => urgencyRank[a.urgency] - urgencyRank[b.urgency]);
  return <Section title="Cross-functional action center" description="A single place to see work that needs your role. Decisions still happen on the source record, never on a context-free alert." action={<StatusPill tone={actions.some((item) => item.urgency === "Blocking") ? "danger" : actions.length ? "warning" : "success"}>{actions.length} action{actions.length === 1 ? "" : "s"}</StatusPill>}><div className="company-request-list">{actions.slice(0, 25).map((item) => { const Icon = item.icon; return <article key={item.id}><span><Icon size={17}/></span><div><small>{item.category}</small><strong>{item.title}</strong><p>{item.detail}</p></div><StatusPill tone={urgencyTone(item.urgency)}>{item.urgency}</StatusPill><Button size="sm" variant="secondary" onClick={() => navigate(item.page)}>Open source</Button></article>; })}{actions.length === 0 && <div className="review-empty"><ShieldCheck size={25}/><h3>Action center clear</h3><p>No cross-functional source records currently require this role.</p></div>}</div>{actions.length > 25 && <div className="form-callout"><AlertTriangle size={16}/><p>{actions.length - 25} additional actions are available inside their source modules. The queue is capped here to keep My Work usable.</p></div>}</Section>;
}
