import assert from "node:assert/strict";import test from "node:test";
import { mergeDocument } from "../lib/persistence";import { orderCasesForProduct, orderLinesFor } from "../lib/order-lines";import { createCommerceSeed } from "../lib/commerce-engine";import type { Order,WorkspaceData } from "../lib/types";
const multi:Order={id:"o",number:"GE-X",accountId:"a",cases:17,pricePerCase:24,amount:408,status:"Approved",placedAt:"2026-09-23",ownerId:"u",priceBasis:"Tier A",paymentStatus:"Not invoiced",product:"Multiple products",lines:[{id:"l1",product:"0.25L (8.4oz) Golden Eagle Energy Drink (24pack)",cases:12,pricePerCase:24,amount:288},{id:"l2",product:"0.25L (8.4oz) Golden Eagle SugarFree (24pack)",cases:5,pricePerCase:24,amount:120}]};
test("multi-SKU order keeps exact product quantities",()=>{assert.equal(orderLinesFor(multi).length,2);assert.equal(orderCasesForProduct(multi,"Original"),12);assert.equal(orderCasesForProduct(multi,"Sugar Free"),5)});
test("persistence omission cannot delete existing array record",()=>{const base={items:[{id:"one",v:1},{id:"two",v:1}]};const local={items:[{id:"one",v:2}]};const merged=mergeDocument(base,local,base) as {items:{id:string;v:number}[]};assert.deepEqual(merged.items.map(x=>x.id).sort(),["one","two"]);assert.equal(merged.items.find(x=>x.id==="one")?.v,2)});
test("small-business invoices default to COD",()=>{const data:WorkspaceData={users:[],customers:[{id:"c",name:"Customer",accountType:"Independent",createdAt:"2026-09-23T00:00:00.000Z",paymentTerms:"COD"}],accounts:[{id:"a",customerId:"c",name:"Shop",location:"Phoenix",channel:"Retail",stage:"Opening order",ownerId:"u",contactName:"x",contactRole:"owner",phone:"1",email:"x@y.com",lastActivity:"",nextAction:"",nextActionDate:"2026-09-23",health:"New",lifetimeCases:0,reorderCount:0,notes:""}],activities:[],appointments:[],orders:[multi],placements:[],inventory:[],approvals:[],timeEntries:[],timecards:[],notifications:[],bulletins:[],territories:[]};assert.equal(createCommerceSeed(data).invoices[0]?.terms,"COD")});


test("legacy shorthand resolves to canonical SKU lines",()=>{assert.equal(orderCasesForProduct(multi,"0.25L (8.4oz) Golden Eagle Energy Drink (24pack)"),12);assert.equal(orderCasesForProduct(multi,"Original"),12)});

import { createInventoryLedgerSeed, normalizeInventoryLedger, warehouseNodeId } from "../lib/inventory-ledger";

test("multi-SKU reservations survive inventory ledger normalization",()=>{
  const original="0.25L (8.4oz) Golden Eagle Energy Drink (24pack)";const sugar="0.25L (8.4oz) Golden Eagle SugarFree (24pack)";
  const data:WorkspaceData={users:[{id:"u",name:"User",firstName:"User",email:"u@test.local",initials:"U",title:"Admin",role:"Administrator",team:"Leadership",accent:"#000"}],customers:[],accounts:[],activities:[],appointments:[],orders:[multi],placements:[],inventory:[{id:"lot-o",lotCode:"O",product:original,receivedAt:"2026-09-01",bestBy:"2027-09-01",onHand:100,reserved:0,available:100,status:"Available",location:"Warehouse"},{id:"lot-s",lotCode:"S",product:sugar,receivedAt:"2026-09-01",bestBy:"2027-09-01",onHand:100,reserved:0,available:100,status:"Available",location:"Warehouse"}],approvals:[],timeEntries:[],timecards:[],notifications:[],bulletins:[],territories:[]};
  const seed=createInventoryLedgerSeed(data);const state={...seed,reservations:[{id:"r1",orderId:"o",lotId:"lot-o",quantity:12,status:"Active" as const,createdAt:"2026-09-23T10:00:00.000Z",createdBy:"u"},{id:"r2",orderId:"o",lotId:"lot-s",quantity:5,status:"Active" as const,createdAt:"2026-09-23T10:00:00.000Z",createdBy:"u"}]};
  const normalized=normalizeInventoryLedger(state,data);assert.equal(normalized.reservations.length,2);assert.equal(normalized.nodes.some((node)=>node.id===warehouseNodeId),true);
});
