"use client";

import { FormEvent, useMemo, useState } from "react";
import { ClipboardCheck, MoveRight, PackageCheck } from "lucide-react";
import type { MovementType } from "../../lib/inventory-ledger";
import { nodeLotBalance } from "../../lib/inventory-ledger";
import { useInventoryLedger } from "../../lib/inventory-ledger-context";
import { useWorkspace } from "../../lib/workspace-context";
import { Button, Field, Section, StatusPill, formatDate } from "../ui";

const movementTypes: MovementType[]=["Receipt","Transfer","Delivery","Return","Sample","Damage","Shrink","Adjustment","Disposal"];

export function WarehouseOperationsPanel(){
  const { data,currentUser }=useWorkspace();
  const { ledger,postMovement,recordCount,releaseReservation }=useInventoryLedger();
  const [lotId,setLotId]=useState(data.inventory[0]?.id??"");
  const [movementType,setMovementType]=useState<MovementType>("Transfer");
  const [fromNode,setFromNode]=useState("");const[toNode,setToNode]=useState("");const[quantity,setQuantity]=useState("");const[reason,setReason]=useState("");const[relatedOrderId,setRelatedOrderId]=useState("");
  const [countNode,setCountNode]=useState(ledger.nodes.find((node)=>node.type==="Warehouse")?.id??"");const[countLot,setCountLot]=useState(data.inventory[0]?.id??"");const[countQty,setCountQty]=useState("");const[notice,setNotice]=useState("");
  const activeReservations=useMemo(()=>ledger.reservations.filter((item)=>item.status==="Active"),[ledger.reservations]);
  if(currentUser?.role!=="Warehouse")return null;
  const submitMovement=(event:FormEvent)=>{event.preventDefault();const id=postMovement({lotId,quantity:Number(quantity),type:movementType,fromNodeId:fromNode||undefined,toNodeId:toNode||undefined,relatedOrderId:relatedOrderId||undefined,reason});setNotice(id?"Movement recorded":"Movement could not be recorded. Check quantity, custody path, reservation/order link, period lock, and reason.");if(id){setQuantity("");setReason("");setRelatedOrderId("");}};
  const submitCount=(event:FormEvent)=>{event.preventDefault();const id=recordCount(countNode,countLot,Number(countQty));setNotice(id?"Physical count recorded for Operations review":"Count could not be recorded.");if(id)setCountQty("");};
  return <div className="warehouse-operations-panel"><Section title="Warehouse workspace" action={notice?<StatusPill tone="info">{notice}</StatusPill>:undefined}>
    <div className="warehouse-ops-grid"><form className="warehouse-ops-card form-grid" onSubmit={submitMovement}><div className="warehouse-ops-title"><MoveRight size={18}/><strong>Record inventory movement</strong></div><Field label="Lot"><select value={lotId} onChange={(event)=>setLotId(event.target.value)}>{data.inventory.map((lot)=><option key={lot.id} value={lot.id}>{lot.product} · {lot.lotCode}</option>)}</select></Field><Field label="Movement"><select value={movementType} onChange={(event)=>setMovementType(event.target.value as MovementType)}>{movementTypes.map((type)=><option key={type}>{type}</option>)}</select></Field><Field label="Related order"><select value={relatedOrderId} onChange={(event)=>{const orderId=event.target.value;setRelatedOrderId(orderId);if(movementType==="Delivery"&&orderId){const order=data.orders.find((item)=>item.id===orderId);if(order)setToNode(`node-account-${order.accountId}`);}}}><option value="">Not order-related</option>{data.orders.filter((order)=>["Approved","Allocated","Out for delivery"].includes(order.status)).map((order)=><option key={order.id} value={order.id}>{order.number} · {order.cases} cases</option>)}</select></Field><Field label="From"><select value={fromNode} onChange={(event)=>setFromNode(event.target.value)}><option value="">None / source outside ledger</option>{ledger.nodes.filter((node)=>node.active).map((node)=><option key={node.id} value={node.id}>{node.name}</option>)}</select></Field><Field label="To"><select value={toNode} onChange={(event)=>setToNode(event.target.value)}><option value="">None / leaves custody</option>{ledger.nodes.filter((node)=>node.active).map((node)=><option key={node.id} value={node.id}>{node.name}</option>)}</select></Field><Field label="Cases"><input type="number" min="1" required value={quantity} onChange={(event)=>setQuantity(event.target.value)}/></Field><Field label="Reason" className="field--full"><input required value={reason} onChange={(event)=>setReason(event.target.value)}/></Field><Button type="submit">Record movement</Button></form>
    <form className="warehouse-ops-card form-grid" onSubmit={submitCount}><div className="warehouse-ops-title"><ClipboardCheck size={18}/><strong>Physical count</strong></div><Field label="Custody location"><select value={countNode} onChange={(event)=>setCountNode(event.target.value)}>{ledger.nodes.filter((node)=>node.active&&node.type!=="External").map((node)=><option key={node.id} value={node.id}>{node.name}</option>)}</select></Field><Field label="Lot"><select value={countLot} onChange={(event)=>setCountLot(event.target.value)}>{data.inventory.map((lot)=><option key={lot.id} value={lot.id}>{lot.product} · {lot.lotCode}</option>)}</select></Field><Field label="Counted cases"><input type="number" min="0" required value={countQty} onChange={(event)=>setCountQty(event.target.value)}/></Field><div className="warehouse-system-balance"><span>System quantity</span><strong>{countNode&&countLot?nodeLotBalance(ledger,countNode,countLot):0}</strong></div><Button type="submit">Record count</Button></form></div>
    <div className="warehouse-count-list"><h3>Open count variances</h3>{ledger.counts.filter((item)=>item.status==="Open").map((count)=><article key={count.id}><div><strong>{data.inventory.find((lot)=>lot.id===count.lotId)?.lotCode}</strong><span>{ledger.nodes.find((node)=>node.id===count.nodeId)?.name} · system {count.systemQty} · counted {count.countedQty} · variance {count.variance}</span></div><StatusPill tone="warning">Operations review</StatusPill></article>)}{ledger.counts.filter((item)=>item.status==="Open").length===0&&<span>No open count variances.</span>}</div>
    <div className="warehouse-count-list"><h3>Active order reservations</h3>{activeReservations.map((reservation)=><article key={reservation.id}><div><PackageCheck size={16}/><div><strong>{data.orders.find((order)=>order.id===reservation.orderId)?.number??reservation.orderId} · {reservation.quantity} cases</strong><span>{data.inventory.find((lot)=>lot.id===reservation.lotId)?.lotCode} · reserved {formatDate(reservation.createdAt,{month:"short",day:"numeric",hour:"numeric",minute:"2-digit"})}</span><small>Reservation becomes fulfilled only after the linked delivery movement proves customer custody.</small></div></div><div className="request-actions"><Button size="sm" variant="secondary" onClick={()=>releaseReservation(reservation.id)}>Release</Button></div></article>)}{activeReservations.length===0&&<span>No active reservations.</span>}</div>
  </Section></div>;
}
