"use client";

import { Building2, CalendarClock, ContactRound, FileClock, MapPin, MessageSquareText, Plus, Store, Target, UserRoundCheck } from "lucide-react";
import { FormEvent, useMemo, useState } from "react";
import { CrmContact, CrmInteraction, Opportunity, OpportunityStage } from "../../lib/crm-engine";
import { useCrm } from "../../lib/crm-context";
import { customerForLocation, customerLocations, customersForLocations, locationLabel } from "../../lib/crm-hierarchy";
import { useWorkspace } from "../../lib/workspace-context";
import { Button, Field, Modal, Section, StatusPill, formatDate } from "../ui";

const opportunityStages:OpportunityStage[]=["Prospecting","Qualified","Sample / evaluation","Commercial review","Order pending","Won","Lost"];
const opportunityTone=(status:Opportunity["status"])=>status==="Won"?"success" as const:status==="Lost"?"danger" as const:"info" as const;

export function CrmDepthPanel(){
  const{data,scope,currentUser,createAccount,navigate}=useWorkspace();const{crm,addContact,addInteraction,addOpportunity,updateOpportunity}=useCrm();
  const customers=customersForLocations(data,scope.accounts);const[customerId,setCustomerId]=useState(customers[0]?.id??"");
  const locations=customerLocations(data,customerId,scope.accounts);const[locationId,setLocationId]=useState(locations[0]?.id??scope.accounts[0]?.id??"");
  const selected=scope.accounts.find((item)=>item.id===locationId)??locations[0]??scope.accounts[0];const customer=selected?customerForLocation(data,selected):undefined;
  const customerLocationsVisible=customer?customerLocations(data,customer.id,scope.accounts):[];
  const contacts=crm.contacts.filter((contact)=>customer&&contact.customerId===customer.id&&(!contact.locationId||customerLocationsVisible.some((location)=>location.id===contact.locationId))).sort((a,b)=>Number(b.primary)-Number(a.primary)||a.name.localeCompare(b.name));
  const interactions=crm.interactions.filter((item)=>selected&&item.locationId===selected.id).sort((a,b)=>b.occurredAt.localeCompare(a.occurredAt));
  const opportunities=crm.opportunities.filter((item)=>selected&&item.locationId===selected.id).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));
  const responsibility=selected?crm.responsibilityHistory.filter((item)=>item.locationId===selected.id).sort((a,b)=>b.effectiveAt.localeCompare(a.effectiveAt)):[];
  const currentResponsible=data.users.find((user)=>user.id===selected?.ownerId);const originator=data.users.find((user)=>user.id===selected?.originatorId);const manager=data.users.find((user)=>user.id===selected?.accountManagerId);const closer=data.users.find((user)=>user.id===selected?.closerId);
  const canBuild=Boolean(currentUser&&["Administrator","Sales Manager","Sales Representative"].includes(currentUser.role));
  const [contactOpen,setContactOpen]=useState(false);const[interactionOpen,setInteractionOpen]=useState(false);const[opportunityOpen,setOpportunityOpen]=useState(false);const[locationOpen,setLocationOpen]=useState(false);
  const [contactForm,setContactForm]=useState({scope:"Location" as CrmContact["scope"],name:"",role:"",email:"",phone:"",decisionRole:"Decision maker" as CrmContact["decisionRole"],primary:false});
  const [interactionForm,setInteractionForm]=useState({type:"Call" as CrmInteraction["type"],summary:"",outcome:"",nextAction:"",nextActionDate:"",contactId:""});
  const [opportunityForm,setOpportunityForm]=useState({name:"",stage:"Prospecting" as OpportunityStage,estimatedCases:"",expectedCloseDate:"",nextAction:"",nextActionDate:""});
  const [locationForm,setLocationForm]=useState({locationName:"",location:"Phoenix, AZ",channel:selected?.channel??"Independent retail",contactName:"",contactRole:"Owner / buyer",phone:"",email:"",streetAddress:""});

  const switchCustomer=(id:string)=>{setCustomerId(id);const next=customerLocations(data,id,scope.accounts)[0];if(next)setLocationId(next.id);};
  const addContactSubmit=(event:FormEvent)=>{event.preventDefault();if(!customer||!selected||!currentUser)return;addContact({scope:contactForm.scope,customerId:customer.id,locationId:contactForm.scope==="Location"?selected.id:undefined,name:contactForm.name.trim(),role:contactForm.role.trim(),email:contactForm.email.trim()||undefined,phone:contactForm.phone.trim()||undefined,decisionRole:contactForm.decisionRole,primary:contactForm.primary,active:true});setContactOpen(false);setContactForm({scope:"Location",name:"",role:"",email:"",phone:"",decisionRole:"Decision maker",primary:false});};
  const addInteractionSubmit=(event:FormEvent)=>{event.preventDefault();if(!selected)return;addInteraction({locationId:selected.id,type:interactionForm.type,summary:interactionForm.summary.trim(),outcome:interactionForm.outcome.trim()||undefined,nextAction:interactionForm.nextAction.trim()||undefined,nextActionDate:interactionForm.nextActionDate||undefined,contactId:interactionForm.contactId||undefined});setInteractionOpen(false);setInteractionForm({type:"Call",summary:"",outcome:"",nextAction:"",nextActionDate:"",contactId:""});};
  const addOpportunitySubmit=(event:FormEvent)=>{event.preventDefault();if(!selected||!customer||!currentUser)return;addOpportunity({customerId:customer.id,locationId:selected.id,name:opportunityForm.name.trim(),stage:opportunityForm.stage,ownerId:selected.ownerId,estimatedCases:opportunityForm.estimatedCases?Number(opportunityForm.estimatedCases):undefined,expectedCloseDate:opportunityForm.expectedCloseDate||undefined,nextAction:opportunityForm.nextAction.trim(),nextActionDate:opportunityForm.nextActionDate,status:opportunityForm.stage==="Won"?"Won":opportunityForm.stage==="Lost"?"Lost":"Open"});setOpportunityOpen(false);setOpportunityForm({name:"",stage:"Prospecting",estimatedCases:"",expectedCloseDate:"",nextAction:"",nextActionDate:""});};
  const addLocationSubmit=(event:FormEvent)=>{event.preventDefault();if(!customer)return;const id=createAccount({name:`${customer.name} · ${locationForm.locationName.trim()}`,customerName:customer.name,locationName:locationForm.locationName.trim(),location:locationForm.location,streetAddress:locationForm.streetAddress.trim()||undefined,channel:locationForm.channel,contactName:locationForm.contactName,contactRole:locationForm.contactRole,phone:locationForm.phone,email:locationForm.email});if(id){setLocationId(id);setLocationOpen(false);setLocationForm({locationName:"",location:"Phoenix, AZ",channel:selected?.channel??"Independent retail",contactName:"",contactRole:"Owner / buyer",phone:"",email:"",streetAddress:""});}};
  const openDispatch=()=>{if(!selected)return;sessionStorage.setItem("momentum-focus-record",selected.id);navigate("dispatch");};
  if(!selected||!customer)return null;

  return <div className="page crm-depth-panel">
    <Section title="Customer & location structure" description="The customer account is the parent relationship. Sales responsibility, appointments, orders, placements, and performance attribution attach to the exact service location instead of silently transferring an entire chain."><div className="crm-hierarchy-selector"><label><span>Customer account</span><select value={customer.id} onChange={(event)=>switchCustomer(event.target.value)}>{customers.map((item)=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label><span>Service location</span><select value={selected.id} onChange={(event)=>setLocationId(event.target.value)}>{customerLocationsVisible.map((location)=><option value={location.id} key={location.id}>{locationLabel(location)} · {location.location}</option>)}</select></label>{canBuild&&<Button variant="secondary" size="sm" icon={<Plus size={14}/>} onClick={()=>setLocationOpen(true)}>Add location</Button>}</div><div className="dispatch-record-pair"><article><small>Customer account</small><strong>{customer.name}</strong><p>{customer.accountType} · {customerLocationsVisible.length} location{customerLocationsVisible.length===1?"":"s"} in your scope</p></article><article><small>Selected service location</small><strong>{locationLabel(selected)}</strong><p>{selected.streetAddress||selected.location} · {selected.channel}</p></article></div><div className="company-rule-facts"><div><span>Originator</span><strong>{originator?.name??"Not recorded"}</strong><small>Who opened this location record</small></div><div><span>Current responsibility</span><strong>{currentResponsible?.name??"Unassigned"}</strong><small>Location-level responsibility</small></div><div><span>Account manager</span><strong>{manager?.name??"Not assigned"}</strong><small>Ongoing relationship responsibility</small></div><div><span>Closer</span><strong>{closer?.name??"Not yet recorded"}</strong><small>Recorded only after a closing event</small></div></div><div className="account-detail__actions"><Button size="sm" onClick={openDispatch}>Schedule this location</Button><Button size="sm" variant="secondary" onClick={()=>navigate("orders")}>Open orders</Button></div></Section>

    <div className="company-grid company-grid--two"><Section title="Contacts" description="Multiple customer- and location-level contacts with decision roles" action={canBuild?<Button size="sm" variant="secondary" icon={<Plus size={14}/>} onClick={()=>setContactOpen(true)}>Add contact</Button>:undefined}><div className="company-request-list">{contacts.map((contact)=><article key={contact.id}><span><ContactRound size={17}/></span><div><small>{contact.scope}{contact.locationId?` · ${locationLabel(scope.accounts.find((item)=>item.id===contact.locationId)??selected)}`:""}</small><strong>{contact.name}{contact.primary?" · Primary":""}</strong><p>{contact.role} · {contact.decisionRole}{contact.email?` · ${contact.email}`:""}{contact.phone?` · ${contact.phone}`:""}</p></div><StatusPill tone={contact.active?"success":"neutral"}>{contact.active?"Active":"Inactive"}</StatusPill></article>)}{contacts.length===0&&<div className="review-empty"><ContactRound size={23}/><h3>No contacts</h3><p>Add the buyer, billing contact, operations contact, or other decision roles.</p></div>}</div></Section><Section title="Location responsibility history" description="Assignment history remains separate from customer ownership"><div className="hcm-audit-list">{responsibility.map((event)=>{const from=data.users.find((item)=>item.id===event.fromUserId);const to=data.users.find((item)=>item.id===event.toUserId);const actor=data.users.find((item)=>item.id===event.changedBy);return <article key={event.id}><span><UserRoundCheck size={16}/></span><div><strong>{from?.name??"Unassigned"} → {to?.name??"Unknown"}</strong><p>{event.reason} · changed by {actor?.name??"System"}</p><small>{formatDate(event.effectiveAt,{month:"short",day:"numeric",year:"numeric",hour:"numeric",minute:"2-digit"})}</small></div>{event.acceptedAt&&<StatusPill tone="success">Accepted</StatusPill>}</article>})}</div></Section></div>

    <div className="company-grid company-grid--two"><Section title="Interaction history" description="Calls, emails, texts, visits, samples, notes, outcomes, and next actions stay attached to the location" action={canBuild?<Button size="sm" variant="secondary" icon={<Plus size={14}/>} onClick={()=>setInteractionOpen(true)}>Log interaction</Button>:undefined}><div className="mini-timeline">{interactions.slice(0,12).map((item)=><article key={item.id}><i/><div><strong>{item.type}: {item.summary}</strong><p>{item.outcome||"No outcome note"}{item.nextAction?` Next: ${item.nextAction}${item.nextActionDate?` on ${item.nextActionDate}`:""}.`:""}</p><small>{data.users.find((user)=>user.id===item.userId)?.name??"User"} · {formatDate(item.occurredAt,{month:"short",day:"numeric",hour:"numeric",minute:"2-digit"})}</small></div></article>)}{interactions.length===0&&<div className="review-empty"><MessageSquareText size={23}/><p>No CRM interactions yet.</p></div>}</div></Section><Section title="Opportunities" description="Commercial opportunities are location-specific and retain their own next action" action={canBuild?<Button size="sm" variant="secondary" icon={<Plus size={14}/>} onClick={()=>setOpportunityOpen(true)}>New opportunity</Button>:undefined}><div className="company-request-list">{opportunities.map((opportunity)=><article key={opportunity.id}><span><Target size={17}/></span><div><small>{opportunity.stage}{opportunity.expectedCloseDate?` · expected ${formatDate(opportunity.expectedCloseDate,{month:"short",day:"numeric"})}`:""}</small><strong>{opportunity.name}</strong><p>{opportunity.estimatedCases?`${opportunity.estimatedCases} estimated cases · `:""}Next: {opportunity.nextAction} · {opportunity.nextActionDate}</p></div><StatusPill tone={opportunityTone(opportunity.status)}>{opportunity.status}</StatusPill>{opportunity.status==="Open"&&<select value={opportunity.stage} onChange={(event)=>{const stage=event.target.value as OpportunityStage;updateOpportunity(opportunity.id,{stage,status:stage==="Won"?"Won":stage==="Lost"?"Lost":"Open"});}}>{opportunityStages.map((stage)=><option key={stage}>{stage}</option>)}</select>}</article>)}{opportunities.length===0&&<div className="review-empty"><Target size={23}/><h3>No open opportunity record</h3><p>Create one when there is a defined commercial pursuit beyond normal account maintenance.</p></div>}</div></Section></div>

    <Modal open={contactOpen} title="Add CRM contact" description="Choose whether this person belongs to the parent customer account or only the selected location." onClose={()=>setContactOpen(false)} footer={<><Button variant="ghost" onClick={()=>setContactOpen(false)}>Cancel</Button><Button type="submit" form="crm-contact-form">Add contact</Button></>}><form id="crm-contact-form" className="form-grid" onSubmit={addContactSubmit}><Field label="Scope"><select value={contactForm.scope} onChange={(event)=>setContactForm({...contactForm,scope:event.target.value as CrmContact["scope"]})}><option>Location</option><option>Customer</option></select></Field><Field label="Name"><input required value={contactForm.name} onChange={(event)=>setContactForm({...contactForm,name:event.target.value})}/></Field><Field label="Role / title"><input required value={contactForm.role} onChange={(event)=>setContactForm({...contactForm,role:event.target.value})}/></Field><Field label="Decision role"><select value={contactForm.decisionRole} onChange={(event)=>setContactForm({...contactForm,decisionRole:event.target.value as CrmContact["decisionRole"]})}><option>Decision maker</option><option>Influencer</option><option>Billing</option><option>Operations</option><option>Other</option></select></Field><Field label="Email"><input type="email" value={contactForm.email} onChange={(event)=>setContactForm({...contactForm,email:event.target.value})}/></Field><Field label="Phone"><input value={contactForm.phone} onChange={(event)=>setContactForm({...contactForm,phone:event.target.value})}/></Field><Field label="Primary contact"><select value={contactForm.primary?"yes":"no"} onChange={(event)=>setContactForm({...contactForm,primary:event.target.value==="yes"})}><option value="no">No</option><option value="yes">Yes</option></select></Field></form></Modal>

    <Modal open={interactionOpen} title="Log CRM interaction" description="Preserve the interaction, outcome, and next action against the exact location." onClose={()=>setInteractionOpen(false)} footer={<><Button variant="ghost" onClick={()=>setInteractionOpen(false)}>Cancel</Button><Button type="submit" form="crm-interaction-form">Save interaction</Button></>}><form id="crm-interaction-form" className="form-grid" onSubmit={addInteractionSubmit}><Field label="Interaction"><select value={interactionForm.type} onChange={(event)=>setInteractionForm({...interactionForm,type:event.target.value as CrmInteraction["type"]})}><option>Call</option><option>Email</option><option>Text</option><option>Visit</option><option>Sample</option><option>Note</option></select></Field><Field label="Contact"><select value={interactionForm.contactId} onChange={(event)=>setInteractionForm({...interactionForm,contactId:event.target.value})}><option value="">No specific contact</option>{contacts.map((contact)=><option key={contact.id} value={contact.id}>{contact.name}</option>)}</select></Field><Field label="Summary" className="field--full"><input required value={interactionForm.summary} onChange={(event)=>setInteractionForm({...interactionForm,summary:event.target.value})}/></Field><Field label="Outcome" className="field--full"><textarea rows={3} value={interactionForm.outcome} onChange={(event)=>setInteractionForm({...interactionForm,outcome:event.target.value})}/></Field><Field label="Next action"><input value={interactionForm.nextAction} onChange={(event)=>setInteractionForm({...interactionForm,nextAction:event.target.value})}/></Field><Field label="Next-action date"><input type="date" value={interactionForm.nextActionDate} onChange={(event)=>setInteractionForm({...interactionForm,nextActionDate:event.target.value})}/></Field></form></Modal>

    <Modal open={opportunityOpen} title="Create opportunity" description="Opportunities belong to the exact location being pursued." onClose={()=>setOpportunityOpen(false)} footer={<><Button variant="ghost" onClick={()=>setOpportunityOpen(false)}>Cancel</Button><Button type="submit" form="crm-opportunity-form">Create</Button></>}><form id="crm-opportunity-form" className="form-grid" onSubmit={addOpportunitySubmit}><Field label="Opportunity"><input required value={opportunityForm.name} onChange={(event)=>setOpportunityForm({...opportunityForm,name:event.target.value})}/></Field><Field label="Stage"><select value={opportunityForm.stage} onChange={(event)=>setOpportunityForm({...opportunityForm,stage:event.target.value as OpportunityStage})}>{opportunityStages.map((stage)=><option key={stage}>{stage}</option>)}</select></Field><Field label="Estimated cases"><input type="number" min="0" value={opportunityForm.estimatedCases} onChange={(event)=>setOpportunityForm({...opportunityForm,estimatedCases:event.target.value})}/></Field><Field label="Expected close"><input type="date" value={opportunityForm.expectedCloseDate} onChange={(event)=>setOpportunityForm({...opportunityForm,expectedCloseDate:event.target.value})}/></Field><Field label="Next action"><input required value={opportunityForm.nextAction} onChange={(event)=>setOpportunityForm({...opportunityForm,nextAction:event.target.value})}/></Field><Field label="Next-action date"><input required type="date" value={opportunityForm.nextActionDate} onChange={(event)=>setOpportunityForm({...opportunityForm,nextActionDate:event.target.value})}/></Field></form></Modal>

    <Modal open={locationOpen} title={`Add a ${customer.name} location`} description="The new location gets its own sales responsibility, contacts, appointments, orders, placement history, and compensation attribution. It does not transfer the parent customer account." onClose={()=>setLocationOpen(false)} footer={<><Button variant="ghost" onClick={()=>setLocationOpen(false)}>Cancel</Button><Button type="submit" form="crm-location-form">Create location</Button></>}><form id="crm-location-form" className="form-grid" onSubmit={addLocationSubmit}><Field label="Location name / number"><input required value={locationForm.locationName} onChange={(event)=>setLocationForm({...locationForm,locationName:event.target.value})} placeholder="Example: Store #2417"/></Field><Field label="City / market"><input required value={locationForm.location} onChange={(event)=>setLocationForm({...locationForm,location:event.target.value})}/></Field><Field label="Street address" className="field--full"><input value={locationForm.streetAddress} onChange={(event)=>setLocationForm({...locationForm,streetAddress:event.target.value})}/></Field><Field label="Channel"><input required value={locationForm.channel} onChange={(event)=>setLocationForm({...locationForm,channel:event.target.value})}/></Field><Field label="Primary contact"><input value={locationForm.contactName} onChange={(event)=>setLocationForm({...locationForm,contactName:event.target.value})}/></Field><Field label="Contact role"><input value={locationForm.contactRole} onChange={(event)=>setLocationForm({...locationForm,contactRole:event.target.value})}/></Field><Field label="Phone"><input value={locationForm.phone} onChange={(event)=>setLocationForm({...locationForm,phone:event.target.value})}/></Field><Field label="Email"><input type="email" value={locationForm.email} onChange={(event)=>setLocationForm({...locationForm,email:event.target.value})}/></Field></form></Modal>
  </div>;
}
