import { paymentSettlementDate, type CommerceState } from "./commerce-engine";
import type { FinanceState } from "./finance-engine";
import type { InventoryLedgerState } from "./inventory-ledger";
import type { PayrollState } from "./payroll-engine";

export const ACCOUNTING_STORAGE_KEY="momentum-accounting-v1";
export type AccountingBasis="Not configured"|"Cash"|"Accrual";
export type InventoryValuation="Not configured"|"FIFO"|"Weighted average";
export type AccountType="Asset"|"Liability"|"Equity"|"Revenue"|"Expense";
export type LedgerAccount={id:string;code:string;name:string;type:AccountType;active:boolean;systemRole?:"Cash"|"Accounts receivable"|"Sales revenue"|"Refunds / returns"|"Inventory"|"COGS"|"Payroll expense"|"Payroll liability"|"Expense payable"};
export type SourceEventType="Invoice issued"|"Payment cleared"|"Payment reversed"|"Credit applied"|"Refund settled"|"Inventory receipt"|"Inventory delivered"|"Inventory adjustment"|"Payroll released"|"Expense paid";
export type AccountingRule={id:string;eventType:SourceEventType;debitAccountId:string;creditAccountId:string;effectiveDate:string;active:boolean;memoTemplate:string};
export type JournalLine={id:string;accountId:string;debit:number;credit:number;memo?:string};
export type JournalEntry={id:string;number:string;date:string;memo:string;status:"Draft"|"Posted"|"Voided";sourceType:SourceEventType|"Manual";sourceId:string;lines:JournalLine[];createdAt:string;createdBy:string;postedAt?:string;postedBy?:string;voidedAt?:string;voidedBy?:string;voidReason?:string};
export type Reconciliation={id:string;accountId:string;periodEnd:string;statementEndingBalance:number;ledgerEndingBalance:number;difference:number;status:"Open"|"Reconciled";createdAt:string;createdBy:string;reconciledAt?:string;reconciledBy?:string;note?:string};
export type AccountingSettings={basis:AccountingBasis;inventoryValuation:InventoryValuation;fiscalYearStartMonth:number};
export type AccountingState={version:1;settings:AccountingSettings;accounts:LedgerAccount[];rules:AccountingRule[];journals:JournalEntry[];reconciliations:Reconciliation[]};
export type AccountingSourceEvent={id:string;type:SourceEventType;date:string;amount?:number;description:string;sourceId:string;blockedReason?:string};

const now=()=>new Date().toISOString();
const date=(value:string)=>value.slice(0,10);
export function createAccountingSeed():AccountingState{return{version:1,settings:{basis:"Not configured",inventoryValuation:"Not configured",fiscalYearStartMonth:1},accounts:[
  {id:"acct-cash",code:"1000",name:"Cash / clearing",type:"Asset",active:true,systemRole:"Cash"},
  {id:"acct-ar",code:"1100",name:"Accounts receivable",type:"Asset",active:true,systemRole:"Accounts receivable"},
  {id:"acct-inventory",code:"1200",name:"Inventory",type:"Asset",active:true,systemRole:"Inventory"},
  {id:"acct-sales",code:"4000",name:"Sales revenue",type:"Revenue",active:true,systemRole:"Sales revenue"},
  {id:"acct-returns",code:"4050",name:"Returns / credits",type:"Revenue",active:true,systemRole:"Refunds / returns"},
  {id:"acct-cogs",code:"5000",name:"Cost of goods sold",type:"Expense",active:true,systemRole:"COGS"},
  {id:"acct-payroll",code:"6100",name:"Payroll expense",type:"Expense",active:true,systemRole:"Payroll expense"},
  {id:"acct-payroll-liability",code:"2100",name:"Payroll liabilities",type:"Liability",active:true,systemRole:"Payroll liability"},
  {id:"acct-expense-payable",code:"2200",name:"Employee reimbursement payable",type:"Liability",active:true,systemRole:"Expense payable"},
],rules:[],journals:[],reconciliations:[]};}
export function normalizeAccountingState(input:unknown):AccountingState{const seed=createAccountingSeed();if(!input||typeof input!=="object")return seed;const state=input as Partial<AccountingState>;return{version:1,settings:{...seed.settings,...state.settings},accounts:Array.isArray(state.accounts)&&state.accounts.length?state.accounts:seed.accounts,rules:Array.isArray(state.rules)?state.rules:[],journals:Array.isArray(state.journals)?state.journals:[],reconciliations:Array.isArray(state.reconciliations)?state.reconciliations:[]};}
export function journalBalanced(entry:JournalEntry){const debit=entry.lines.reduce((sum,line)=>sum+line.debit,0);const credit=entry.lines.reduce((sum,line)=>sum+line.credit,0);return Math.abs(debit-credit)<0.005&&debit>0;}
export function accountBalance(state:AccountingState,accountId:string,through?:string){const account=state.accounts.find((item)=>item.id===accountId);if(!account)return 0;const lines=state.journals.filter((entry)=>entry.status==="Posted"&&(!through||entry.date<=through)).flatMap((entry)=>entry.lines.filter((line)=>line.accountId===accountId));const debit=lines.reduce((sum,line)=>sum+line.debit,0);const credit=lines.reduce((sum,line)=>sum+line.credit,0);return["Asset","Expense"].includes(account.type)?debit-credit:credit-debit;}
export function trialBalance(state:AccountingState,through?:string){return state.accounts.filter((account)=>account.active).map((account)=>({account,balance:accountBalance(state,account.id,through)}));}

export function sourceEvents(commerce:CommerceState,inventory:InventoryLedgerState,payroll?:PayrollState,finance?:FinanceState):AccountingSourceEvent[]{const events:AccountingSourceEvent[]=[];
  for(const invoice of commerce.invoices.filter((item)=>item.status!=="Void"))events.push({id:`invoice:${invoice.id}`,type:"Invoice issued",date:date(invoice.issuedAt),amount:invoice.total,description:`Invoice ${invoice.number}`,sourceId:invoice.id});
  for(const payment of commerce.payments.filter((item)=>item.status==="Cleared"))events.push({id:`payment:${payment.id}`,type:"Payment cleared",date:paymentSettlementDate(payment)??date(payment.receivedAt),amount:payment.amount,description:`Cleared ${payment.method} payment`,sourceId:payment.id});
  for(const payment of commerce.payments.filter((item)=>item.status==="Reversed"))events.push({id:`payment-reversal:${payment.id}`,type:"Payment reversed",date:date(payment.reversedAt??payment.receivedAt),amount:payment.amount,description:`Reversed ${payment.method} payment`,sourceId:payment.id,blockedReason:"Payment reversal accounting requires approved treatment and linkage to the original posted payment journal before posting."});
  for(const credit of commerce.credits.filter((item)=>item.status==="Applied")){const invoice=commerce.invoices.find((item)=>item.id===credit.invoiceId);events.push({id:`credit:${credit.id}`,type:"Credit applied",date:date(credit.appliedAt??credit.approvedAt??credit.createdAt),amount:credit.amount,description:`Credit applied to ${invoice?.number??credit.invoiceId}`,sourceId:credit.id});}
  for(const refund of commerce.refunds.filter((item)=>item.status==="Settled"))events.push({id:`refund:${refund.id}`,type:"Refund settled",date:date(refund.settledAt??refund.createdAt),amount:refund.amount,description:"Customer refund settled",sourceId:refund.id});
  for(const movement of inventory.movements){if(movement.type==="Receipt")events.push({id:`movement:${movement.id}`,type:"Inventory receipt",date:date(movement.at),description:`${movement.quantity} case receipt · ${movement.product}`,sourceId:movement.id,blockedReason:"Inventory dollar value requires the approved valuation method and unit cost."});else if(movement.type==="Delivery")events.push({id:`movement:${movement.id}`,type:"Inventory delivered",date:date(movement.at),description:`${movement.quantity} case delivery · ${movement.product}`,sourceId:movement.id,blockedReason:"COGS requires the approved inventory valuation method and cost record."});else if(["Adjustment","Damage","Shrink","Disposal"].includes(movement.type))events.push({id:`movement:${movement.id}`,type:"Inventory adjustment",date:date(movement.at),description:`${movement.type} · ${movement.quantity} cases · ${movement.product}`,sourceId:movement.id,blockedReason:"Inventory adjustment value requires the approved valuation method and cost record."});}
  for(const run of payroll?.runs.filter((item)=>item.status==="Released")??[]){const gross=run.lines.reduce((sum,line)=>sum+line.grossPay+line.employerTaxes,0);events.push({id:`payroll:${run.id}`,type:"Payroll released",date:date(run.releasedAt??run.payDate),amount:gross,description:`${run.kind} payroll · gross plus employer tax ${gross.toFixed(2)}`,sourceId:run.id,blockedReason:"Payroll requires a multi-line accounting template for wages, employer taxes, benefit deductions, tax liabilities, other deductions, and net-pay clearing. A two-line rule would be materially incomplete."});}
  for(const expense of finance?.expenses.filter((item)=>item.status==="Paid")??[])events.push({id:`expense:${expense.id}`,type:"Expense paid",date:date(expense.paidAt??expense.submittedAt),amount:expense.amount,description:`${expense.category} · ${expense.merchant}`,sourceId:expense.id,blockedReason:"Expense accounting requires an approved category-to-ledger mapping before automatic posting."});
  return events.sort((a,b)=>b.date.localeCompare(a.date));}
export function unprocessedSourceEvents(state:AccountingState,events:AccountingSourceEvent[]){const processed=new Set(state.journals.filter((entry)=>entry.status!=="Voided").map((entry)=>`${entry.sourceType}:${entry.sourceId}`));return events.filter((event)=>!processed.has(`${event.type}:${event.sourceId}`));}
export function ruleForEvent(state:AccountingState,event:AccountingSourceEvent){return state.rules.filter((rule)=>rule.active&&rule.eventType===event.type&&rule.effectiveDate<=event.date).sort((a,b)=>b.effectiveDate.localeCompare(a.effectiveDate))[0];}
export function buildJournalFromEvent(state:AccountingState,event:AccountingSourceEvent,actorId:string):JournalEntry|null{if(!event.amount||event.amount<=0||event.blockedReason)return null;const rule=ruleForEvent(state,event);if(!rule||rule.debitAccountId===rule.creditAccountId)return null;const number=`JE-${String(state.journals.length+1).padStart(5,"0")}`;return{id:`journal-${event.id.replace(/[^a-z0-9]/gi,"-")}`,number,date:event.date,memo:rule.memoTemplate.replace("{description}",event.description),status:"Draft",sourceType:event.type,sourceId:event.sourceId,lines:[{id:`line-${number}-d`,accountId:rule.debitAccountId,debit:event.amount,credit:0},{id:`line-${number}-c`,accountId:rule.creditAccountId,debit:0,credit:event.amount}],createdAt:now(),createdBy:actorId};}
