"use client";

import { ReactNode, createContext, useContext, useEffect, useMemo, useState } from "react";
import { ACCOUNTING_STORAGE_KEY, AccountingBasis, AccountingRule, AccountingState, InventoryValuation, JournalEntry, LedgerAccount, Reconciliation, accountBalance, buildJournalFromEvent, buildPaymentReversalJournal, buildPayrollJournal, buildPayrollVoidJournal, createAccountingSeed, journalBalanced, normalizeAccountingState, sourceEvents, systemBuiltEventType, unprocessedSourceEvents } from "./accounting-engine";
import { useCommerce } from "./commerce-context";
import { useFinance } from "./finance-context";
import { useHcm } from "./hcm-context";
import { useInventoryLedger } from "./inventory-ledger-context";
import { payrollRunControlIssues } from "./payroll-controls";
import { usePayroll } from "./payroll-context";
import { usePeriodLocks } from "./period-lock-context";
import { useRuntimeMode } from "./runtime-mode";
import { useWorkspace } from "./workspace-context";
const now=()=>new Date().toISOString();const uid=(prefix:string)=>`${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
type AccountingContextValue={accounting:AccountingState;events:ReturnType<typeof sourceEvents>;setSettings:(basis:AccountingBasis,inventoryValuation:InventoryValuation)=>boolean;addAccount:(input:Omit<LedgerAccount,"id">)=>string|null;addRule:(input:Omit<AccountingRule,"id">)=>string|null;toggleRule:(id:string,active:boolean)=>boolean;runAutomation:()=>number;postJournal:(id:string)=>boolean;voidJournal:(id:string,reason:string)=>boolean;addManualJournal:(input:{date:string;memo:string;debitAccountId:string;creditAccountId:string;amount:number})=>string|null;createReconciliation:(accountId:string,periodEnd:string,statementEndingBalance:number)=>string|null;reconcile:(id:string,note:string)=>boolean;resetAccounting:()=>boolean};
const AccountingContext=createContext<AccountingContextValue|null>(null);
export function AccountingProvider({children}:{children:ReactNode}){const{data,currentUser}=useWorkspace();const{commerce}=useCommerce();const{ledger}=useInventoryLedger();const{payroll}=usePayroll();const{hcm}=useHcm();const{finance}=useFinance();const locks=usePeriodLocks();const runtime=useRuntimeMode();const read=()=>{if(typeof window==="undefined")return createAccountingSeed();try{return normalizeAccountingState(JSON.parse(window.localStorage.getItem(ACCOUNTING_STORAGE_KEY)??"null"));}catch{return createAccountingSeed();}};const[accounting,setAccounting]=useState<AccountingState>(()=>read());useEffect(()=>{if(typeof window!=="undefined")window.localStorage.setItem(ACCOUNTING_STORAGE_KEY,JSON.stringify(accounting));},[accounting]);const events=useMemo(()=>sourceEvents(commerce,ledger,payroll,finance),[commerce,ledger,payroll,finance]);const canManageAccounting=currentUser?.role==="Administrator";
  const setSettings=(basis:AccountingBasis,inventoryValuation:InventoryValuation)=>{if(!canManageAccounting)return false;setAccounting((state)=>({...state,settings:{...state.settings,basis,inventoryValuation}}));return true;};
  const addAccount=(input:Omit<LedgerAccount,"id">)=>{if(!canManageAccounting||!input.code.trim()||!input.name.trim()||accounting.accounts.some((account)=>account.code.trim().toLowerCase()===input.code.trim().toLowerCase()))return null;const id=uid("account");setAccounting((state)=>({...state,accounts:[{...input,code:input.code.trim(),name:input.name.trim(),id},...state.accounts]}));return id;};
  const addRule=(input:Omit<AccountingRule,"id">)=>{if(!canManageAccounting||systemBuiltEventType(input.eventType)||!input.effectiveDate||input.debitAccountId===input.creditAccountId||!accounting.accounts.some((account)=>account.id===input.debitAccountId&&account.active)||!accounting.accounts.some((account)=>account.id===input.creditAccountId&&account.active))return null;const id=uid("rule");setAccounting((state)=>({...state,rules:[{...input,memoTemplate:input.memoTemplate.trim()||"{description}",id},...state.rules]}));return id;};
  const toggleRule=(id:string,active:boolean)=>{if(!canManageAccounting||!accounting.rules.some((rule)=>rule.id===id))return false;setAccounting((state)=>({...state,rules:state.rules.map((rule)=>rule.id===id?{...rule,active}:rule)}));return true;};
  const runAutomation=()=>{if(!canManageAccounting||!currentUser)return 0;let working=accounting;let actions=0;const staleDraftReasons=new Map<string,string>();const voidedPayrollIds=new Set(payroll.runs.filter((run)=>run.status==="Voided").map((run)=>run.id));const reversedPaymentIds=new Set(commerce.payments.filter((payment)=>payment.status==="Reversed").map((payment)=>payment.id));for(const entry of working.journals.filter((item)=>item.status==="Draft")){if(entry.sourceType==="Payroll released"&&voidedPayrollIds.has(entry.sourceId))staleDraftReasons.set(entry.id,"Source payroll run was voided before journal posting.");if(entry.sourceType==="Payment cleared"&&reversedPaymentIds.has(entry.sourceId))staleDraftReasons.set(entry.id,"Source payment was reversed before journal posting.");}if(staleDraftReasons.size){const at=now();working={...working,journals:working.journals.map((entry)=>staleDraftReasons.has(entry.id)?{...entry,status:"Voided" as const,voidedAt:at,voidedBy:currentUser.id,voidReason:staleDraftReasons.get(entry.id)}:entry)};actions+=staleDraftReasons.size;}const pending=unprocessedSourceEvents(working,events);for(const event of pending){let entry:JournalEntry|null=null;if(event.type==="Payroll released"){const run=payroll.runs.find((item)=>item.id===event.sourceId);if(run&&run.status==="Released"&&payrollRunControlIssues(payroll,data,hcm,run).length===0)entry=buildPayrollJournal(working,run,currentUser.id);}else if(event.type==="Payroll voided"){const run=payroll.runs.find((item)=>item.id===event.sourceId);if(run)entry=buildPayrollVoidJournal(working,run,currentUser.id);}else if(event.type==="Payment reversed"){const payment=commerce.payments.find((item)=>item.id===event.sourceId);if(payment)entry=buildPaymentReversalJournal(working,payment,currentUser.id);}else entry=buildJournalFromEvent(working,event,currentUser.id);if(!entry||locks.isLocked("Accounting",entry.date))continue;working={...working,journals:[entry,...working.journals]};actions+=1;}if(actions)setAccounting(working);return actions;};
  const postJournal=(id:string)=>{if(!canManageAccounting||!currentUser)return false;const target=accounting.journals.find((entry)=>entry.id===id);if(!target||target.status!=="Draft"||!journalBalanced(target)||locks.isLocked("Accounting",target.date))return false;if(target.sourceType==="Payroll released"){const run=payroll.runs.find((item)=>item.id===target.sourceId);if(!run||run.status!=="Released"||payrollRunControlIssues(payroll,data,hcm,run).length>0)return false;}if(target.sourceType==="Payroll voided"){const run=payroll.runs.find((item)=>item.id===target.sourceId);const original=accounting.journals.find((entry)=>entry.sourceType==="Payroll released"&&entry.sourceId===target.sourceId&&entry.status==="Posted");if(!run||run.status!=="Voided"||!original)return false;}if(target.sourceType==="Payment cleared"){const payment=commerce.payments.find((item)=>item.id===target.sourceId);if(!payment||payment.status!=="Cleared")return false;}if(target.sourceType==="Payment reversed"){const payment=commerce.payments.find((item)=>item.id===target.sourceId);const original=accounting.journals.find((entry)=>entry.sourceType==="Payment cleared"&&entry.sourceId===target.sourceId&&entry.status==="Posted");if(!payment||payment.status!=="Reversed"||!original)return false;}let posted=false;setAccounting((state)=>({...state,journals:state.journals.map((entry)=>{if(entry.id!==id)return entry;posted=true;return{...entry,status:"Posted",postedAt:now(),postedBy:currentUser.id};})}));return posted;};
  const voidJournal=(id:string,reason:string)=>{if(!canManageAccounting||!currentUser||!reason.trim())return false;let voided=false;setAccounting((state)=>({...state,journals:state.journals.map((entry)=>{if(entry.id!==id||entry.status!=="Posted"||locks.isLocked("Accounting",entry.date)||["Payment cleared","Payment reversed","Payroll released","Payroll voided"].includes(entry.sourceType))return entry;voided=true;return{...entry,status:"Voided",voidReason:reason.trim(),voidedAt:now(),voidedBy:currentUser.id};})}));return voided;};
  const addManualJournal=(input:{date:string;memo:string;debitAccountId:string;creditAccountId:string;amount:number})=>{if(!canManageAccounting||!currentUser||!input.memo.trim()||input.amount<=0||input.debitAccountId===input.creditAccountId||locks.isLocked("Accounting",input.date)||!accounting.accounts.some((account)=>account.id===input.debitAccountId&&account.active)||!accounting.accounts.some((account)=>account.id===input.creditAccountId&&account.active))return null;const id=uid("journal");const number=`JE-${String(accounting.journals.length+1).padStart(5,"0")}`;const entry:JournalEntry={id,number,date:input.date,memo:input.memo.trim(),status:"Draft",sourceType:"Manual",sourceId:id,lines:[{id:uid("line"),accountId:input.debitAccountId,debit:input.amount,credit:0},{id:uid("line"),accountId:input.creditAccountId,debit:0,credit:input.amount}],createdAt:now(),createdBy:currentUser.id};setAccounting((state)=>({...state,journals:[entry,...state.journals]}));return id;};
  const createReconciliation=(accountId:string,periodEnd:string,statementEndingBalance:number)=>{if(!canManageAccounting||!currentUser||locks.isLocked("Accounting",periodEnd)||!Number.isFinite(statementEndingBalance))return null;const ledgerAccount=accounting.accounts.find((item)=>item.id===accountId&&item.active);if(!ledgerAccount)return null;const ledgerEndingBalance=accountBalance(accounting,accountId,periodEnd);const id=uid("reconciliation");const record:Reconciliation={id,accountId,periodEnd,statementEndingBalance,ledgerEndingBalance,difference:statementEndingBalance-ledgerEndingBalance,status:"Open",createdAt:now(),createdBy:currentUser.id};setAccounting((state)=>({...state,reconciliations:[record,...state.reconciliations]}));return id;};
  const reconcile=(id:string,note:string)=>{if(!canManageAccounting||!currentUser)return false;let reconciled=false;setAccounting((state)=>({...state,reconciliations:state.reconciliations.map((item)=>{if(item.id!==id||item.status!=="Open"||Math.abs(item.difference)>=0.005||locks.isLocked("Accounting",item.periodEnd))return item;reconciled=true;return{...item,status:"Reconciled",note:note.trim()||undefined,reconciledAt:now(),reconciledBy:currentUser.id};})}));return reconciled;};
  const resetAccounting=()=>{if(!runtime.isDemo||!canManageAccounting)return false;setAccounting(createAccountingSeed());return true;};return <AccountingContext.Provider value={{accounting,events,setSettings,addAccount,addRule,toggleRule,runAutomation,postJournal,voidJournal,addManualJournal,createReconciliation,reconcile,resetAccounting}}>{children}</AccountingContext.Provider>;
}
export function useAccounting(){const value=useContext(AccountingContext);if(!value)throw new Error("useAccounting must be used inside AccountingProvider");return value;}
