"use client";

import { ReactNode, createContext, useContext, useEffect, useMemo, useState } from "react";
import { ACCOUNTING_STORAGE_KEY, AccountingBasis, AccountingRule, AccountingState, InventoryValuation, JournalEntry, LedgerAccount, Reconciliation, accountBalance, buildJournalFromEvent, createAccountingSeed, journalBalanced, normalizeAccountingState, sourceEvents, unprocessedSourceEvents } from "./accounting-engine";
import { useCommerce } from "./commerce-context";
import { useFinance } from "./finance-context";
import { useInventoryLedger } from "./inventory-ledger-context";
import { usePayroll } from "./payroll-context";
import { usePeriodLocks } from "./period-lock-context";
import { useRuntimeMode } from "./runtime-mode";
import { useWorkspace } from "./workspace-context";
const now=()=>new Date().toISOString();const uid=(prefix:string)=>`${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
type AccountingContextValue={accounting:AccountingState;events:ReturnType<typeof sourceEvents>;setSettings:(basis:AccountingBasis,inventoryValuation:InventoryValuation)=>boolean;addAccount:(input:Omit<LedgerAccount,"id">)=>string|null;addRule:(input:Omit<AccountingRule,"id">)=>string|null;toggleRule:(id:string,active:boolean)=>boolean;runAutomation:()=>number;postJournal:(id:string)=>boolean;voidJournal:(id:string,reason:string)=>boolean;addManualJournal:(input:{date:string;memo:string;debitAccountId:string;creditAccountId:string;amount:number})=>string|null;createReconciliation:(accountId:string,periodEnd:string,statementEndingBalance:number)=>string|null;reconcile:(id:string,note:string)=>boolean;resetAccounting:()=>boolean};
const AccountingContext=createContext<AccountingContextValue|null>(null);
export function AccountingProvider({children}:{children:ReactNode}){const{currentUser}=useWorkspace();const{commerce}=useCommerce();const{ledger}=useInventoryLedger();const{payroll}=usePayroll();const{finance}=useFinance();const locks=usePeriodLocks();const runtime=useRuntimeMode();const read=()=>{if(typeof window==="undefined")return createAccountingSeed();try{return normalizeAccountingState(JSON.parse(window.localStorage.getItem(ACCOUNTING_STORAGE_KEY)??"null"));}catch{return createAccountingSeed();}};const[accounting,setAccounting]=useState<AccountingState>(()=>read());useEffect(()=>{if(typeof window!=="undefined")window.localStorage.setItem(ACCOUNTING_STORAGE_KEY,JSON.stringify(accounting));},[accounting]);const events=useMemo(()=>sourceEvents(commerce,ledger,payroll,finance),[commerce,ledger,payroll,finance]);const canManageAccounting=currentUser?.role==="Administrator";
  const setSettings=(basis:AccountingBasis,inventoryValuation:InventoryValuation)=>{if(!canManageAccounting)return false;setAccounting((state)=>({...state,settings:{...state.settings,basis,inventoryValuation}}));return true;};
  const addAccount=(input:Omit<LedgerAccount,"id">)=>{if(!canManageAccounting||!input.code.trim()||!input.name.trim()||accounting.accounts.some((account)=>account.code.trim().toLowerCase()===input.code.trim().toLowerCase()))return null;const id=uid("account");setAccounting((state)=>({...state,accounts:[{...input,code:input.code.trim(),name:input.name.trim(),id},...state.accounts]}));return id;};
  const addRule=(input:Omit<AccountingRule,"id">)=>{if(!canManageAccounting||!input.effectiveDate||input.debitAccountId===input.creditAccountId||!accounting.accounts.some((account)=>account.id===input.debitAccountId&&account.active)||!accounting.accounts.some((account)=>account.id===input.creditAccountId&&account.active))return null;const id=uid("rule");setAccounting((state)=>({...state,rules:[{...input,memoTemplate:input.memoTemplate.trim()||"{description}",id},...state.rules]}));return id;};
  const toggleRule=(id:string,active:boolean)=>{if(!canManageAccounting||!accounting.rules.some((rule)=>rule.id===id))return false;setAccounting((state)=>({...state,rules:state.rules.map((rule)=>rule.id===id?{...rule,active}:rule)}));return true;};
  const runAutomation=()=>{if(!canManageAccounting||!currentUser)return 0;const pending=unprocessedSourceEvents(accounting,events);const journals=pending.map((event)=>buildJournalFromEvent(accounting,event,currentUser.id)).filter((entry):entry is JournalEntry=>Boolean(entry)).filter((entry)=>!locks.isLocked("Accounting",entry.date));if(!journals.length)return 0;setAccounting((state)=>({...state,journals:[...journals,...state.journals]}));return journals.length;};
  const postJournal=(id:string)=>{if(!canManageAccounting||!currentUser)return false;let posted=false;setAccounting((state)=>({...state,journals:state.journals.map((entry)=>{if(entry.id!==id||entry.status!=="Draft"||!journalBalanced(entry)||locks.isLocked("Accounting",entry.date))return entry;posted=true;return{...entry,status:"Posted",postedAt:now(),postedBy:currentUser.id};})}));return posted;};
  const voidJournal=(id:string,reason:string)=>{if(!canManageAccounting||!currentUser||!reason.trim())return false;let voided=false;setAccounting((state)=>({...state,journals:state.journals.map((entry)=>{if(entry.id!==id||entry.status!=="Posted"||locks.isLocked("Accounting",entry.date))return entry;voided=true;return{...entry,status:"Voided",voidReason:reason.trim(),voidedAt:now(),voidedBy:currentUser.id};})}));return voided;};
  const addManualJournal=(input:{date:string;memo:string;debitAccountId:string;creditAccountId:string;amount:number})=>{if(!canManageAccounting||!currentUser||!input.memo.trim()||input.amount<=0||input.debitAccountId===input.creditAccountId||locks.isLocked("Accounting",input.date)||!accounting.accounts.some((account)=>account.id===input.debitAccountId&&account.active)||!accounting.accounts.some((account)=>account.id===input.creditAccountId&&account.active))return null;const id=uid("journal");const number=`JE-${String(accounting.journals.length+1).padStart(5,"0")}`;const entry:JournalEntry={id,number,date:input.date,memo:input.memo.trim(),status:"Draft",sourceType:"Manual",sourceId:id,lines:[{id:uid("line"),accountId:input.debitAccountId,debit:input.amount,credit:0},{id:uid("line"),accountId:input.creditAccountId,debit:0,credit:input.amount}],createdAt:now(),createdBy:currentUser.id};setAccounting((state)=>({...state,journals:[entry,...state.journals]}));return id;};
  const createReconciliation=(accountId:string,periodEnd:string,statementEndingBalance:number)=>{if(!canManageAccounting||!currentUser||locks.isLocked("Accounting",periodEnd)||!Number.isFinite(statementEndingBalance))return null;const account=accounting.accounts.find((item)=>item.id===accountId&&item.active);if(!account)return null;const ledgerEndingBalance=accountBalance(accounting,accountId,periodEnd);const id=uid("reconciliation");const record:Reconciliation={id,accountId,periodEnd,statementEndingBalance,ledgerEndingBalance,difference:statementEndingBalance-ledgerEndingBalance,status:"Open",createdAt:now(),createdBy:currentUser.id};setAccounting((state)=>({...state,reconciliations:[record,...state.reconciliations]}));return id;};
  const reconcile=(id:string,note:string)=>{if(!canManageAccounting||!currentUser)return false;let reconciled=false;setAccounting((state)=>({...state,reconciliations:state.reconciliations.map((item)=>{if(item.id!==id||item.status!=="Open"||Math.abs(item.difference)>=0.005||locks.isLocked("Accounting",item.periodEnd))return item;reconciled=true;return{...item,status:"Reconciled",note:note.trim()||undefined,reconciledAt:now(),reconciledBy:currentUser.id};})}));return reconciled;};
  const resetAccounting=()=>{if(!runtime.isDemo||!canManageAccounting)return false;setAccounting(createAccountingSeed());return true;};return <AccountingContext.Provider value={{accounting,events,setSettings,addAccount,addRule,toggleRule,runAutomation,postJournal,voidJournal,addManualJournal,createReconciliation,reconcile,resetAccounting}}>{children}</AccountingContext.Provider>;
}
export function useAccounting(){const value=useContext(AccountingContext);if(!value)throw new Error("useAccounting must be used inside AccountingProvider");return value;}
