import type { WorkspaceData, WorkspaceUser } from "./types";
import { customerForLocation } from "./crm-hierarchy";

export const CRM_STORAGE_KEY="momentum-crm-v1";
export type ContactScope="Customer"|"Location";
export type CrmContact={id:string;scope:ContactScope;customerId:string;locationId?:string;name:string;role:string;email?:string;phone?:string;decisionRole:"Decision maker"|"Influencer"|"Billing"|"Operations"|"Other";primary:boolean;active:boolean;createdAt:string;createdBy:string};
export type CrmInteraction={id:string;locationId:string;userId:string;type:"Call"|"Email"|"Text"|"Visit"|"Sample"|"Note";occurredAt:string;summary:string;outcome?:string;nextAction?:string;nextActionDate?:string;contactId?:string};
export type OpportunityStage="Prospecting"|"Qualified"|"Sample / evaluation"|"Commercial review"|"Order pending"|"Won"|"Lost";
export type Opportunity={id:string;customerId:string;locationId:string;name:string;stage:OpportunityStage;ownerId:string;estimatedCases?:number;expectedCloseDate?:string;nextAction:string;nextActionDate:string;status:"Open"|"Won"|"Lost";lossReason?:string;createdAt:string;createdBy:string;updatedAt:string};
export type ResponsibilityEvent={id:string;locationId:string;fromUserId?:string;toUserId:string;effectiveAt:string;reason:string;changedBy:string;acceptedAt?:string};
export type CrmState={version:1;contacts:CrmContact[];interactions:CrmInteraction[];opportunities:Opportunity[];responsibilityHistory:ResponsibilityEvent[]};

const now=()=>new Date().toISOString();
export function createCrmSeed(data:WorkspaceData):CrmState{
  const contacts:CrmContact[]=data.accounts.filter((location)=>location.contactName).map((location)=>{const customer=customerForLocation(data,location);return{id:`contact-${location.id}-primary`,scope:"Location",customerId:customer.id,locationId:location.id,name:location.contactName,role:location.contactRole||"Contact",email:location.email||undefined,phone:location.phone||undefined,decisionRole:"Decision maker",primary:true,active:true,createdAt:now(),createdBy:"system"};});
  const responsibilityHistory:ResponsibilityEvent[]=data.accounts.map((location)=>({id:`responsibility-${location.id}-initial`,locationId:location.id,toUserId:location.ownerId,effectiveAt:location.responsibilityStartedAt??now(),reason:"Initial location responsibility",changedBy:location.originatorId??location.ownerId,acceptedAt:location.responsibilityStartedAt??now()}));
  const interactions:CrmInteraction[]=data.activities.filter((activity)=>activity.accountId).map((activity)=>({id:`crm-${activity.id}`,locationId:activity.accountId!,userId:activity.userId,type:activity.type==="call"?"Call":activity.type==="visit"?"Visit":activity.type==="sample"?"Sample":"Note",occurredAt:activity.at,summary:activity.title,outcome:activity.detail}));
  return{version:1,contacts,interactions,opportunities:[],responsibilityHistory};
}
export function normalizeCrmState(input:unknown,data:WorkspaceData):CrmState{const seed=createCrmSeed(data);if(!input||typeof input!=="object")return seed;const state=input as Partial<CrmState>;const contacts=Array.isArray(state.contacts)?state.contacts:seed.contacts;const existingContactLocations=new Set(contacts.filter((c)=>c.locationId).map((c)=>c.locationId));for(const contact of seed.contacts)if(contact.locationId&&!existingContactLocations.has(contact.locationId))contacts.push(contact);const responsibilityHistory=Array.isArray(state.responsibilityHistory)?state.responsibilityHistory:seed.responsibilityHistory;const existingResponsibility=new Set(responsibilityHistory.map((item)=>item.locationId));for(const event of seed.responsibilityHistory)if(!existingResponsibility.has(event.locationId))responsibilityHistory.push(event);return{version:1,contacts,interactions:Array.isArray(state.interactions)?state.interactions:seed.interactions,opportunities:Array.isArray(state.opportunities)?state.opportunities:[],responsibilityHistory};}
export function crmRecordVisible(actor:WorkspaceUser|null|undefined,locationId:string,data:WorkspaceData){if(!actor)return false;if(actor.role==="Administrator"||actor.role==="Operations")return true;if(actor.role==="Customer")return(actor.accountIds??[]).includes(locationId);const location=data.accounts.find((item)=>item.id===locationId);if(!location)return false;if(actor.role==="Sales Representative")return location.ownerId===actor.id;if(actor.role==="Sales Manager"){const owner=data.users.find((item)=>item.id===location.ownerId);return owner?.managerId===actor.id||owner?.team===actor.team;}return false;}
export function openOpportunities(state:CrmState,locationId?:string){return state.opportunities.filter((item)=>item.status==="Open"&&(!locationId||item.locationId===locationId));}
