import type { WorkspaceData } from "./types";

const dateKey = (offset = 0) => {
  const date = new Date();
  date.setDate(date.getDate() + offset);
  return date.toISOString().slice(0, 10);
};

const stamp = (offsetHours = 0) => {
  const date = new Date();
  date.setHours(date.getHours() + offsetHours);
  return date.toISOString();
};

const startOfWeek = () => {
  const date = new Date();
  const day = date.getDay();
  const distance = day === 0 ? -6 : 1 - day;
  date.setDate(date.getDate() + distance);
  return date.toISOString().slice(0, 10);
};

const endOfWeek = () => {
  const date = new Date(`${startOfWeek()}T12:00:00`);
  date.setDate(date.getDate() + 6);
  return date.toISOString().slice(0, 10);
};

export function createDemoData(): WorkspaceData {
  return {
    users: [
      {
        id: "usr-mia",
        name: "Mia",
        firstName: "Mia",
        email: "mia@momentum.demo",
        initials: "MI",
        title: "Director of Operations",
        role: "Administrator",
        team: "Leadership",
        managedTeams: ["Leadership", "Sales", "Operations"],
        accent: "#e6b82f",
      },
      {
        id: "usr-flo",
        name: "Flo",
        firstName: "Flo",
        email: "flo@momentum.demo",
        initials: "FL",
        title: "Executive Owner",
        role: "Administrator",
        team: "Leadership",
        managedTeams: ["Leadership", "Sales", "Operations"],
        accent: "#4b7bec",
      },
      {
        id: "usr-avery",
        name: "Avery Chen",
        firstName: "Avery",
        email: "manager@momentum.demo",
        initials: "AC",
        title: "Arizona Sales Manager",
        role: "Sales Manager",
        team: "Sales",
        managerId: "usr-mia",
        managedTeams: ["Sales"],
        accent: "#1558b0",
      },
      {
        id: "usr-jordan",
        name: "Jordan Lee",
        firstName: "Jordan",
        email: "rep@momentum.demo",
        initials: "JL",
        title: "Sales Representative",
        role: "Sales Representative",
        team: "Sales",
        managerId: "usr-avery",
        accent: "#e64b4b",
      },
      {
        id: "usr-elena",
        name: "Elena Torres",
        firstName: "Elena",
        email: "ops@momentum.demo",
        initials: "ET",
        title: "Operations Coordinator",
        role: "Operations",
        team: "Operations",
        managerId: "usr-mia",
        accent: "#2ab49b",
      },
      {
        id: "usr-customer",
        name: "Tasha Green",
        firstName: "Tasha",
        email: "customer@momentum.demo",
        initials: "TG",
        title: "Retail Partner",
        role: "Customer",
        team: "Customer",
        accountIds: ["acc-101"],
        accent: "#d8212e",
      },
    ],
    accounts: [
      {
        id: "acc-101",
        name: "Desert Lantern Market",
        location: "Phoenix, AZ",
        channel: "Independent retail",
        stage: "Reordered",
        ownerId: "usr-jordan",
        contactName: "Tasha Green",
        contactRole: "Owner",
        phone: "(602) 555-0142",
        email: "tasha@example.test",
        lastActivity: "Second order paid",
        nextAction: "Placement check and stock count",
        nextActionDate: dateKey(1),
        health: "Strong",
        lifetimeCases: 34,
        reorderCount: 2,
        notes: "Demo account. Strong cold-box placement near checkout.",
      },
      {
        id: "acc-102",
        name: "Copper State Fitness",
        location: "Tempe, AZ",
        channel: "Gym / fitness",
        stage: "Placed",
        ownerId: "usr-jordan",
        contactName: "Andre Mills",
        contactRole: "General Manager",
        phone: "(480) 555-0188",
        email: "andre@example.test",
        lastActivity: "Placement photo logged",
        nextAction: "First reorder conversation",
        nextActionDate: dateKey(3),
        health: "New",
        lifetimeCases: 10,
        reorderCount: 0,
        notes: "Demo account. Product placed in front lobby cooler.",
      },
      {
        id: "acc-103",
        name: "Juniper Night Market",
        location: "Scottsdale, AZ",
        channel: "Restaurant / nightlife",
        stage: "Opening order",
        ownerId: "usr-mia",
        contactName: "Nina Patel",
        contactRole: "Beverage Buyer",
        phone: "(480) 555-0107",
        email: "nina@example.test",
        lastActivity: "Draft order created",
        nextAction: "Approve introductory pricing",
        nextActionDate: dateKey(0),
        health: "New",
        lifetimeCases: 0,
        reorderCount: 0,
        notes: "Demo account. Pricing shown is a proposed scenario only.",
      },
      {
        id: "acc-104",
        name: "Mesa Quick Stop",
        location: "Mesa, AZ",
        channel: "Convenience store",
        stage: "Sampled",
        ownerId: "usr-jordan",
        contactName: "Ray Alvarez",
        contactRole: "Owner",
        phone: "(480) 555-0131",
        email: "ray@example.test",
        lastActivity: "Cold sample accepted",
        nextAction: "Opening-order follow-up",
        nextActionDate: dateKey(0),
        health: "Watch",
        lifetimeCases: 0,
        reorderCount: 0,
        notes: "Demo account. Buyer requested two days to review cooler space.",
      },
      {
        id: "acc-105",
        name: "Sonoran Fuel #14",
        location: "Glendale, AZ",
        channel: "Fuel / convenience",
        stage: "Qualified",
        ownerId: "usr-mia",
        contactName: "Morgan Bell",
        contactRole: "Category Manager",
        phone: "(623) 555-0156",
        email: "morgan@example.test",
        lastActivity: "Buyer requirements captured",
        nextAction: "Send non-binding program summary",
        nextActionDate: dateKey(2),
        health: "New",
        lifetimeCases: 0,
        reorderCount: 0,
        notes: "Demo multi-location opportunity. Terms are not approved.",
      },
      {
        id: "acc-106",
        name: "Roosevelt Social",
        location: "Phoenix, AZ",
        channel: "Restaurant / nightlife",
        stage: "At risk",
        ownerId: "usr-jordan",
        contactName: "Camille Brooks",
        contactRole: "Bar Manager",
        phone: "(602) 555-0195",
        email: "camille@example.test",
        lastActivity: "Low stock reported",
        nextAction: "Resolve placement and reorder blocker",
        nextActionDate: dateKey(0),
        health: "At risk",
        lifetimeCases: 18,
        reorderCount: 1,
        notes: "Demo account. Product moved from the primary cooler.",
      },
    ],
    activities: [
      {
        id: "act-1",
        accountId: "acc-101",
        type: "order",
        title: "Payment recorded",
        detail: "Demo order GE-1047 marked paid.",
        at: stamp(-3),
        userId: "usr-elena",
      },
      {
        id: "act-2",
        accountId: "acc-102",
        type: "placement",
        title: "Placement verified",
        detail: "Four facings observed in the lobby cooler.",
        at: stamp(-22),
        userId: "usr-jordan",
      },
      {
        id: "act-3",
        accountId: "acc-104",
        type: "sample",
        title: "Cold sample dropped",
        detail: "Decision-maker received sample and sales sheet.",
        at: stamp(-28),
        userId: "usr-jordan",
      },
      {
        id: "act-4",
        accountId: "acc-106",
        type: "note",
        title: "Account risk flagged",
        detail: "Product is no longer in the primary cold box.",
        at: stamp(-30),
        userId: "usr-mia",
      },
    ],
    appointments: [
      {
        id: "apt-1",
        accountId: "acc-104",
        ownerId: "usr-jordan",
        date: dateKey(0),
        startTime: "09:30",
        duration: 30,
        type: "First visit",
        status: "Scheduled",
        objective: "Confirm cooler space and ask for the opening order.",
        location: "Mesa, AZ",
      },
      {
        id: "apt-2",
        accountId: "acc-106",
        ownerId: "usr-jordan",
        date: dateKey(0),
        startTime: "11:15",
        duration: 35,
        type: "Placement check",
        status: "Dispatched",
        objective: "Restore cold placement and identify reorder blocker.",
        location: "Phoenix, AZ",
      },
      {
        id: "apt-3",
        accountId: "acc-103",
        ownerId: "usr-mia",
        date: dateKey(0),
        startTime: "14:00",
        duration: 45,
        type: "Reorder",
        status: "Scheduled",
        objective: "Review proposed terms and confirm approval path.",
        location: "Scottsdale, AZ",
      },
      {
        id: "apt-4",
        accountId: "acc-101",
        ownerId: "usr-jordan",
        date: dateKey(1),
        startTime: "10:00",
        duration: 30,
        type: "Placement check",
        status: "Scheduled",
        objective: "Count stock and document shelf price.",
        location: "Phoenix, AZ",
      },
      {
        id: "apt-5",
        accountId: "acc-105",
        ownerId: "usr-mia",
        date: dateKey(2),
        startTime: "13:30",
        duration: 45,
        type: "Sample drop",
        status: "Scheduled",
        objective: "Validate buyer requirements before any commercial quote.",
        location: "Glendale, AZ",
      },
    ],
    orders: [
      {
        id: "ord-1047",
        number: "GE-1047",
        accountId: "acc-101",
        cases: 12,
        pricePerCase: 24,
        amount: 288,
        status: "Paid",
        placedAt: dateKey(-4),
        ownerId: "usr-jordan",
        priceBasis: "Demo entered price",
        paymentStatus: "Paid",
      },
      {
        id: "ord-1048",
        number: "GE-1048",
        accountId: "acc-102",
        cases: 10,
        pricePerCase: 24,
        amount: 240,
        status: "Delivered",
        placedAt: dateKey(-2),
        ownerId: "usr-jordan",
        priceBasis: "Demo entered price",
        paymentStatus: "Open",
      },
      {
        id: "ord-1049",
        number: "GE-1049",
        accountId: "acc-103",
        cases: 10,
        pricePerCase: 24,
        amount: 240,
        status: "Awaiting approval",
        placedAt: dateKey(0),
        ownerId: "usr-mia",
        priceBasis: "Demo entered price",
        paymentStatus: "Not invoiced",
      },
    ],
    placements: [
      {
        id: "plc-1",
        accountId: "acc-101",
        product: "Golden Eagle · tour SKU",
        casesDelivered: 12,
        facings: 5,
        location: "Front checkout cooler",
        cold: true,
        shelfPrice: 1.99,
        observedStock: 96,
        lastChecked: dateKey(-5),
        nextCheck: dateKey(1),
        source: "Physical count",
        status: "Healthy",
      },
      {
        id: "plc-2",
        accountId: "acc-102",
        product: "Golden Eagle · tour SKU",
        casesDelivered: 10,
        facings: 4,
        location: "Lobby cooler",
        cold: true,
        shelfPrice: 1.99,
        observedStock: 178,
        lastChecked: dateKey(-1),
        nextCheck: dateKey(3),
        source: "Physical count",
        status: "Healthy",
      },
      {
        id: "plc-3",
        accountId: "acc-106",
        product: "Golden Eagle · tour SKU",
        casesDelivered: 8,
        facings: 0,
        location: "Back-room inventory",
        cold: false,
        shelfPrice: 1.99,
        observedStock: 41,
        lastChecked: dateKey(-2),
        nextCheck: dateKey(0),
        source: "Customer estimate",
        status: "Check soon",
      },
    ],
    inventory: [
      {
        id: "lot-1",
        lotCode: "DEMO-AZ-2408",
        product: "Golden Eagle · tour SKU",
        receivedAt: dateKey(-31),
        bestBy: dateKey(330),
        onHand: 428,
        reserved: 72,
        available: 356,
        status: "Available",
        location: "Phoenix demo warehouse",
      },
      {
        id: "lot-2",
        lotCode: "DEMO-HOLD-01",
        product: "Golden Eagle · tour SKU",
        receivedAt: dateKey(-14),
        bestBy: dateKey(347),
        onHand: 24,
        reserved: 0,
        available: 0,
        status: "Quality hold",
        location: "QA cage · demo",
        holdReason: "Demo receiving inspection requires an authorized disposition.",
      },
    ],
    approvals: [
      {
        id: "apr-1",
        type: "Order",
        title: "Review order GE-1049",
        detail: "10 cases · demo-entered price · Juniper Night Market",
        requestedBy: "Mia",
        requesterId: "usr-mia",
        recordId: "ord-1049",
        team: "Leadership",
        submittedAt: stamp(-2),
        dueAt: stamp(4),
        priority: "High",
        status: "Pending",
      },
      {
        id: "apr-2",
        type: "Timecard",
        title: "Jordan Lee · weekly timecard",
        detail: "32.5 recorded hours · one missing-punch correction acknowledged",
        requestedBy: "Jordan Lee",
        requesterId: "usr-jordan",
        recordId: "tc-jordan",
        team: "Sales",
        submittedAt: stamp(-8),
        dueAt: stamp(18),
        priority: "Normal",
        status: "Pending",
      },
    ],
    timeEntries: [
      {
        id: "te-1",
        userId: "usr-jordan",
        date: dateKey(-2),
        clockIn: "08:04",
        clockOut: "16:22",
        breakMinutes: 30,
        source: "Demo mobile",
      },
      {
        id: "te-2",
        userId: "usr-jordan",
        date: dateKey(-1),
        clockIn: "08:11",
        clockOut: "16:45",
        breakMinutes: 32,
        source: "Demo mobile",
      },
      {
        id: "te-3",
        userId: "usr-mia",
        date: dateKey(-1),
        clockIn: "17:30",
        clockOut: "19:45",
        breakMinutes: 0,
        source: "Demo desktop",
      },
    ],
    timecards: [
      {
        id: "tc-avery",
        userId: "usr-avery",
        weekStart: startOfWeek(),
        weekEnd: endOfWeek(),
        status: "Open",
        attested: false,
      },
      {
        id: "tc-jordan",
        userId: "usr-jordan",
        weekStart: startOfWeek(),
        weekEnd: endOfWeek(),
        status: "Submitted",
        submittedAt: stamp(-8),
        attested: true,
      },
      {
        id: "tc-mia",
        userId: "usr-mia",
        weekStart: startOfWeek(),
        weekEnd: endOfWeek(),
        status: "Open",
        attested: false,
      },
      {
        id: "tc-elena",
        userId: "usr-elena",
        weekStart: startOfWeek(),
        weekEnd: endOfWeek(),
        status: "Open",
        attested: false,
      },
    ],
    notifications: [
      {
        id: "note-1",
        title: "Inventory hold requires review",
        detail: "DEMO-HOLD-01 remains unavailable while the quality hold is open.",
        at: stamp(-1),
        readBy: [],
        tone: "warning",
        audienceUserIds: ["usr-mia", "usr-flo", "usr-elena"],
      },
      {
        id: "note-2",
        title: "Three approvals need review",
        detail: "One item is marked urgent.",
        at: stamp(-3),
        readBy: [],
        tone: "info",
        audienceUserIds: ["usr-mia", "usr-flo", "usr-avery"],
      },
      {
        id: "note-3",
        title: "Demo placement verified",
        detail: "Copper State Fitness now has four cold facings recorded.",
        at: stamp(-22),
        readBy: ["usr-mia", "usr-flo", "usr-avery", "usr-jordan"],
        tone: "success",
        audienceUserIds: ["usr-mia", "usr-flo", "usr-avery", "usr-jordan"],
      },
    ],
    bulletins: [
      {
        id: "blt-company-1",
        title: "Field closeout is now required",
        body: "Every completed customer visit must record the outcome, a concise note, and the next action with a date. This keeps handoffs from disappearing between sales and operations.",
        audience: "Company",
        priority: "Important",
        authorId: "usr-mia",
        publishedAt: stamp(-20),
        acknowledgedBy: ["usr-mia", "usr-flo"],
      },
      {
        id: "blt-sales-1",
        title: "Sales team placement standard",
        body: "On placement and reorder visits, record observed stock, facings, shelf price, and whether the product is cold before closing the visit.",
        audience: "Team",
        team: "Sales",
        priority: "Update",
        authorId: "usr-avery",
        publishedAt: stamp(-10),
        acknowledgedBy: ["usr-avery"],
      },
    ],
  };
}
