"use client";

import { ReactNode, createContext, useContext, useEffect, useState } from "react";
import { INVENTORY_LEDGER_STORAGE_KEY, InventoryCount, InventoryLedgerState, InventoryMovement, InventoryReservation, MovementType, createInventoryLedgerSeed, movementCanPost, nodeLotBalance, normalizeInventoryLedger } from "./inventory-ledger";
import { usePeriodLocks } from "./period-lock-context";
import { useRuntimeMode } from "./runtime-mode";
import { useWorkspace } from "./workspace-context";
const now=()=>new Date().toISOString();const today=()=>new Date().toISOString().slice(0,10);const uid=(prefix:string)=>`${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
type InventoryLedgerContextValue={ledger:InventoryLedgerState;postMovement:(input:{lotId:string;quantity:number;type:MovementType;fromNodeId?:string;toNodeId?:string;relatedOrderId?:string;reason:string})=>string|null;reserve:(orderId:string,lotId:string,quantity:number)=>string|null;releaseReservation:(id:string)=>void;fulfillReservation:(id:string)=>void;recordCount:(nodeId:string,lotId:string,countedQty:number)=>string|null;reconcileCount:(id:string,reason:string)=>void;resetLedger:()=>void};
const InventoryLedgerContext=createContext<InventoryLedgerContextValue|null>(null);
export function InventoryLedgerProvider({children}:{children:ReactNode}){const{data,currentUser}=useWorkspace();const locks=usePeriodLocks();const runtime=useRuntimeMode();const read=()=>{if(typeof window==="undefined")return createInventoryLedgerSeed(data);try{return normalizeInventoryLedger(JSON.parse(window.localStorage.getItem(INVENTORY_LEDGER_STORAGE_KEY)??"null"),data);}catch{return createInventoryLedgerSeed(data);}};const[ledger,setLedger]=useState<InventoryLedgerState>(()=>read());useEffect(()=>{const handle=window.setTimeout(()=>setLedger((state)=>normalizeInventoryLedger(state,data)),0);return()=>window.clearTimeout(handle);},[data]);useEffect(()=>{if(typeof window!=="undefined")window.localStorage.setItem(INVENTORY_LEDGER_STORAGE_KEY,JSON.stringify(ledger));},[ledger]);const locked=()=>locks.isLocked("Inventory",today());
  const postMovement=(input:{lotId:string;quantity:number;type:MovementType;fromNodeId?:string;toNodeId?:string;relatedOrderId?:string;reason:string})=>{if(locked()||!input.reason.trim()||!movementCanPost(ledger,input))return null;const lot=data.inventory.find((item)=>item.id===input.lotId);if(!lot)return null;const id=uid("movement");const record:InventoryMovement={id,lotId:input.lotId,product:lot.product,quantity:input.quantity,type:input.type,fromNodeId:input.fromNodeId,toNodeId:input.toNodeId,relatedOrderId:input.relatedOrderId,reason:input.reason.trim(),at:now(),actorId:currentUser?.id??"system"};setLedger((state)=>({...state,movements:[record,...state.movements]}));return id;};
  const reserve=(orderId:string,lotId:string,quantity:number)=>{if(locked()||quantity<=0)return null;const order=data.orders.find((item)=>item.id===orderId);if(!order||quantity>order.cases)return null;const id=uid("reservation");const record:InventoryReservation={id,orderId,lotId,quantity,status:"Active",createdAt:now(),createdBy:currentUser?.id??"system"};setLedger((state)=>({...state,reservations:[record,...state.reservations]}));return id;};
  const releaseReservation=(id:string)=>{if(locked())return;setLedger((state)=>({...state,reservations:state.reservations.map((item)=>item.id===id&&item.status==="Active"?{...item,status:"Released",releasedAt:now()}:item)}));};
  const fulfillReservation=(id:string)=>{if(locked())return;setLedger((state)=>({...state,reservations:state.reservations.map((item)=>item.id===id&&item.status==="Active"?{...item,status:"Fulfilled",fulfilledAt:now()}:item)}));};
  const recordCount=(nodeId:string,lotId:string,countedQty:number)=>{if(locked()||countedQty<0)return null;const id=uid("count");const systemQty=nodeLotBalance(ledger,nodeId,lotId);const record:InventoryCount={id,nodeId,lotId,countedQty,systemQty,variance:countedQty-systemQty,countedAt:now(),countedBy:currentUser?.id??"system",status:"Open"};setLedger((state)=>({...state,counts:[record,...state.counts]}));return id;};
  const reconcileCount=(id:string,reason:string)=>{if(locked()||!reason.trim())return;setLedger((state)=>{const count=state.counts.find((item)=>item.id===id&&item.status==="Open");if(!count)return state;let movements=state.movements;let adjustmentMovementId:string|undefined;if(count.variance!==0){const lot=data.inventory.find((item)=>item.id===count.lotId);if(!lot)return state;adjustmentMovementId=uid("movement");const movement:InventoryMovement={id:adjustmentMovementId,lotId:count.lotId,product:lot.product,quantity:Math.abs(count.variance),type:"Adjustment",fromNodeId:count.variance<0?count.nodeId:undefined,toNodeId:count.variance>0?count.nodeId:undefined,reason:`Count reconciliation: ${reason.trim()}`,at:now(),actorId:currentUser?.id??"system"};movements=[movement,...movements];}return{...state,movements,counts:state.counts.map((item)=>item.id===id?{...item,status:"Reconciled",reason:reason.trim(),reconciledAt:now(),reconciledBy:currentUser?.id??"system",adjustmentMovementId}:item)};});};
  const resetLedger=()=>{if(runtime.isDemo)setLedger(createInventoryLedgerSeed(data));};return <InventoryLedgerContext.Provider value={{ledger,postMovement,reserve,releaseReservation,fulfillReservation,recordCount,reconcileCount,resetLedger}}>{children}</InventoryLedgerContext.Provider>;
}
export function useInventoryLedger(){const value=useContext(InventoryLedgerContext);if(!value)throw new Error("useInventoryLedger must be used inside InventoryLedgerProvider");return value;}
