"use client";

import { ReactNode, createContext, useContext, useEffect, useState } from "react";
import { INVENTORY_LEDGER_STORAGE_KEY, InventoryCount, InventoryLedgerState, InventoryMovement, InventoryReservation, MovementType, activeReservedForOrder, createInventoryLedgerSeed, holdNodeId, movementCanPost, nodeLotBalance, normalizeInventoryLedger, orderCanAdvanceInventory, orderDeliveryQuantity, reservationCanCreate, warehouseNodeId } from "./inventory-ledger";
import { usePeriodLocks } from "./period-lock-context";
import { useRuntimeMode } from "./runtime-mode";
import { useWorkspace } from "./workspace-context";
const now=()=>new Date().toISOString();const today=()=>new Date().toISOString().slice(0,10);const uid=(prefix:string)=>`${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
type FulfillmentStatus="Allocated"|"Out for delivery"|"Delivered";
type InventoryLedgerContextValue={ledger:InventoryLedgerState;postMovement:(input:{lotId:string;quantity:number;type:MovementType;fromNodeId?:string;toNodeId?:string;relatedOrderId?:string;reason:string})=>string|null;reserve:(orderId:string,lotId:string,quantity:number)=>string|null;releaseReservation:(id:string)=>boolean;fulfillReservation:(id:string)=>boolean;advanceOrderFulfillment:(orderId:string,status:FulfillmentStatus)=>boolean;resolveQualityHold:(lotId:string,decision:"Release"|"Retain",reason:string)=>boolean;recordCount:(nodeId:string,lotId:string,countedQty:number)=>string|null;reconcileCount:(id:string,reason:string)=>boolean;resetLedger:()=>void};
const InventoryLedgerContext=createContext<InventoryLedgerContextValue|null>(null);
export function InventoryLedgerProvider({children}:{children:ReactNode}){const{data,currentUser,setOrderStatus,resolveInventoryHold}=useWorkspace();const locks=usePeriodLocks();const runtime=useRuntimeMode();const read=()=>{if(typeof window==="undefined")return createInventoryLedgerSeed(data);try{return normalizeInventoryLedger(JSON.parse(window.localStorage.getItem(INVENTORY_LEDGER_STORAGE_KEY)??"null"),data);}catch{return createInventoryLedgerSeed(data);}};const[ledger,setLedger]=useState<InventoryLedgerState>(()=>read());useEffect(()=>{const handle=window.setTimeout(()=>setLedger((state)=>normalizeInventoryLedger(state,data)),0);return()=>window.clearTimeout(handle);},[data]);useEffect(()=>{if(typeof window!=="undefined")window.localStorage.setItem(INVENTORY_LEDGER_STORAGE_KEY,JSON.stringify(ledger));},[ledger]);const locked=()=>locks.isLocked("Inventory",today());const inventoryActor=Boolean(currentUser&&["Administrator","Operations","Warehouse"].includes(currentUser.role));const inventoryManager=Boolean(currentUser&&["Administrator","Operations"].includes(currentUser.role));
  const postMovement=(input:{lotId:string;quantity:number;type:MovementType;fromNodeId?:string;toNodeId?:string;relatedOrderId?:string;reason:string})=>{if(!inventoryActor||locked()||!input.reason.trim()||["Allocation","Release","Adjustment"].includes(input.type)||!input.fromNodeId||!input.toNodeId||!movementCanPost(ledger,input))return null;const lot=data.inventory.find((item)=>item.id===input.lotId);if(!lot)return null;const from=ledger.nodes.find((node)=>node.id===input.fromNodeId);const to=ledger.nodes.find((node)=>node.id===input.toNodeId);const order=input.relatedOrderId?data.orders.find((item)=>item.id===input.relatedOrderId):undefined;if(!from||!to||input.relatedOrderId&&!order)return null;if(order&&order.product&&order.product!==lot.product)return null;
    if(input.type==="Receipt"){if(from.type!=="External"||!["Warehouse","Quality hold"].includes(to.type))return null;}
    if(input.type==="Transfer"&&order&&input.fromNodeId===warehouseNodeId){if(activeReservedForOrder(ledger,order.id,lot.id)<input.quantity)return null;if(!["Employee custody","Vehicle","Bin","Customer"].includes(to.type))return null;}
    if(input.type==="Delivery"){if(!order||!["Allocated","Out for delivery"].includes(order.status))return null;const expectedCustomerNode=`node-account-${order.accountId}`;if(input.toNodeId!==expectedCustomerNode||activeReservedForOrder(ledger,order.id,lot.id)<input.quantity)return null;if(orderDeliveryQuantity(ledger,order.id)+input.quantity>order.cases)return null;if(["Customer","External","Quality hold","Disposed"].includes(from.type))return null;}
    if(input.type==="Return"&&order){const expectedCustomerNode=`node-account-${order.accountId}`;if(input.fromNodeId!==expectedCustomerNode||!["Warehouse","Quality hold"].includes(to.type))return null;}
    if(["Damage","Shrink"].includes(input.type)&&!["Quality hold","Disposed"].includes(to.type))return null;
    if(input.type==="Disposal"&&to.type!=="Disposed")return null;
    const id=uid("movement");const record:InventoryMovement={id,lotId:input.lotId,product:lot.product,quantity:input.quantity,type:input.type,fromNodeId:input.fromNodeId,toNodeId:input.toNodeId,relatedOrderId:input.relatedOrderId,reason:input.reason.trim(),at:now(),actorId:currentUser!.id};setLedger((state)=>({...state,movements:[record,...state.movements]}));return id;};
  const reserve=(orderId:string,lotId:string,quantity:number)=>{if(!inventoryActor||locked()||!reservationCanCreate(ledger,data,orderId,lotId,quantity))return null;const id=uid("reservation");const record:InventoryReservation={id,orderId,lotId,quantity,status:"Active",createdAt:now(),createdBy:currentUser!.id};setLedger((state)=>({...state,reservations:[record,...state.reservations]}));return id;};
  const releaseReservation=(id:string)=>{if(!inventoryActor||locked())return false;const existing=ledger.reservations.find((item)=>item.id===id&&item.status==="Active");if(!existing)return false;setLedger((state)=>({...state,reservations:state.reservations.map((item)=>item.id===id&&item.status==="Active"?{...item,status:"Released",releasedAt:now()}:item)}));return true;};
  const fulfillReservation=(id:string)=>{if(!inventoryActor||locked())return false;const reservation=ledger.reservations.find((item)=>item.id===id&&item.status==="Active");if(!reservation)return false;const deliveredForLot=ledger.movements.filter((movement)=>movement.relatedOrderId===reservation.orderId&&movement.lotId===reservation.lotId&&movement.type==="Delivery").reduce((sum,movement)=>sum+movement.quantity,0);const fulfilledForLot=ledger.reservations.filter((item)=>item.orderId===reservation.orderId&&item.lotId===reservation.lotId&&item.status==="Fulfilled").reduce((sum,item)=>sum+item.quantity,0);if(deliveredForLot-fulfilledForLot<reservation.quantity)return false;setLedger((state)=>({...state,reservations:state.reservations.map((item)=>item.id===id&&item.status==="Active"?{...item,status:"Fulfilled",fulfilledAt:now()}:item)}));return true;};
  const advanceOrderFulfillment=(orderId:string,status:FulfillmentStatus)=>{if(!inventoryManager||locked())return false;const order=data.orders.find((item)=>item.id===orderId);if(!order)return false;const expected=order.status==="Approved"?"Allocated":order.status==="Allocated"?"Out for delivery":order.status==="Out for delivery"?"Delivered":null;if(expected!==status||!orderCanAdvanceInventory(ledger,order,status))return false;if(status==="Delivered"){const active=ledger.reservations.filter((item)=>item.orderId===order.id&&item.status==="Active");for(const reservation of active){const deliveredForLot=ledger.movements.filter((movement)=>movement.relatedOrderId===order.id&&movement.lotId===reservation.lotId&&movement.type==="Delivery").reduce((sum,movement)=>sum+movement.quantity,0);const fulfilledForLot=ledger.reservations.filter((item)=>item.orderId===order.id&&item.lotId===reservation.lotId&&item.status==="Fulfilled").reduce((sum,item)=>sum+item.quantity,0);if(deliveredForLot-fulfilledForLot<reservation.quantity)return false;}setLedger((state)=>({...state,reservations:state.reservations.map((item)=>item.orderId===order.id&&item.status==="Active"?{...item,status:"Fulfilled",fulfilledAt:now()}:item)}));}setOrderStatus(order.id,status);return true;};
  const resolveQualityHold=(lotId:string,decision:"Release"|"Retain",reason:string)=>{if(!inventoryManager||locked()||reason.trim().length<8)return false;const lot=data.inventory.find((item)=>item.id===lotId);if(!lot||lot.status!=="Quality hold")return false;if(decision==="Retain")return resolveInventoryHold(lotId,"Retain",reason);const heldQty=nodeLotBalance(ledger,holdNodeId,lotId);if(heldQty<=0||!movementCanPost(ledger,{lotId,quantity:heldQty,type:"Transfer",fromNodeId:holdNodeId,toNodeId:warehouseNodeId}))return false;if(!resolveInventoryHold(lotId,"Release",reason))return false;const movement:InventoryMovement={id:uid("movement-hold-release"),lotId,product:lot.product,quantity:heldQty,type:"Transfer",fromNodeId:holdNodeId,toNodeId:warehouseNodeId,reason:`Quality hold release: ${reason.trim()}`,at:now(),actorId:currentUser!.id};setLedger((state)=>({...state,movements:[movement,...state.movements]}));return true;};
  const recordCount=(nodeId:string,lotId:string,countedQty:number)=>{if(!inventoryActor||locked()||countedQty<0||!ledger.nodes.some((node)=>node.id===nodeId&&node.type!=="External")||!data.inventory.some((lot)=>lot.id===lotId))return null;const id=uid("count");const systemQty=nodeLotBalance(ledger,nodeId,lotId);const record:InventoryCount={id,nodeId,lotId,countedQty,systemQty,variance:countedQty-systemQty,countedAt:now(),countedBy:currentUser!.id,status:"Open"};setLedger((state)=>({...state,counts:[record,...state.counts]}));return id;};
  const reconcileCount=(id:string,reason:string)=>{if(!inventoryManager||locked()||!reason.trim())return false;const existing=ledger.counts.find((item)=>item.id===id&&item.status==="Open");if(!existing||existing.countedBy===currentUser!.id)return false;setLedger((state)=>{const count=state.counts.find((item)=>item.id===id&&item.status==="Open");if(!count)return state;let movements=state.movements;let adjustmentMovementId:string|undefined;if(count.variance!==0){const lot=data.inventory.find((item)=>item.id===count.lotId);if(!lot)return state;adjustmentMovementId=uid("movement");const movement:InventoryMovement={id:adjustmentMovementId,lotId:count.lotId,product:lot.product,quantity:Math.abs(count.variance),type:"Adjustment",fromNodeId:count.variance<0?count.nodeId:undefined,toNodeId:count.variance>0?count.nodeId:undefined,reason:`Count reconciliation: ${reason.trim()}`,at:now(),actorId:currentUser!.id};movements=[movement,...movements];}return{...state,movements,counts:state.counts.map((item)=>item.id===id?{...item,status:"Reconciled",reason:reason.trim(),reconciledAt:now(),reconciledBy:currentUser!.id,adjustmentMovementId}:item)};});return true;};
  const resetLedger=()=>{if(runtime.isDemo&&currentUser?.role==="Administrator")setLedger(createInventoryLedgerSeed(data));};return <InventoryLedgerContext.Provider value={{ledger,postMovement,reserve,releaseReservation,fulfillReservation,advanceOrderFulfillment,resolveQualityHold,recordCount,reconcileCount,resetLedger}}>{children}</InventoryLedgerContext.Provider>;
}
export function useInventoryLedger(){const value=useContext(InventoryLedgerContext);if(!value)throw new Error("useInventoryLedger must be used inside InventoryLedgerProvider");return value;}
