import type { FieldTrackingState } from "./location-tracking-engine";
import type { Appointment, WorkspaceData, WorkspaceUser } from "./types";

export type ManagementKpiKey = "collected_revenue" | "paid_cases" | "paid_orders" | "new_paid_accounts" | "completed_demos" | "demo_completion_rate" | "new_business_close_rate" | "reorder_accounts" | "reorder_account_share" | "closeout_completeness_rate" | "arrival_verification_rate" | "offsite_exceptions";
export type KpiFormat = "currency" | "integer" | "percent";
export type KpiDefinition = { key: ManagementKpiKey; label: string; shortLabel: string; group: "Sales" | "Retention" | "Execution" | "Field accountability"; format: KpiFormat; description: string; formula: string; inclusion: string; exclusion: string; source: string; frequency: string; owner: string; auditMethod: string; intendedBehavior: string; gamingRisk: string; actionTriggered: string };
export type KpiPeriod = { start: string; end: string };
export type KpiResult = { key: ManagementKpiKey; value: number; numerator: number; denominator?: number; sourceRecordIds: string[] };
export type KpiSeriesPoint = KpiResult & { start: string; end: string; label: string };
export type KpiPersonRow = { userId: string; name: string; role: string; team: string; result: KpiResult };

type DefinitionInput = Omit<KpiDefinition, "frequency" | "auditMethod" | "intendedBehavior" | "gamingRisk" | "actionTriggered"> & Partial<Pick<KpiDefinition, "frequency" | "auditMethod" | "intendedBehavior" | "gamingRisk" | "actionTriggered">>;
const define = (input: DefinitionInput): KpiDefinition => ({ frequency: "Live from source records; review weekly.", auditMethod: "Trace exported source record IDs to the underlying ledger before using the result for management action or compensation.", intendedBehavior: "Reward verified business outcomes and clean execution.", gamingRisk: "Duplicate, backdated, reassigned, or incomplete source records can distort the metric.", actionTriggered: "Investigate material variance and source-record quality before changing targets or forecasts.", ...input });

export const MANAGEMENT_KPI_DEFINITIONS: KpiDefinition[] = [
  define({ key:"collected_revenue", label:"Collected revenue", shortLabel:"Revenue", group:"Sales", format:"currency", description:"Money attached to paid orders in the selected period.", formula:"Sum order.amount for paid orders by paidAt; placedAt is only the legacy fallback when paidAt is missing.", inclusion:"Paid orders whose collection date is in range.", exclusion:"Open, partially paid, unpaid, or out-of-period orders.", source:"Order ledger: paymentStatus, paidAt, placedAt, amount, ownerId/creditedRepId.", owner:"Sales leadership / Finance", intendedBehavior:"Keep revenue tied to collected business, not pipeline." }),
  define({ key:"paid_cases", label:"Paid cases", shortLabel:"Paid cases", group:"Sales", format:"integer", description:"Cases on orders that have actually been paid.", formula:"Sum order.cases for paid orders collected in range.", inclusion:"Paid orders in range.", exclusion:"Unpaid or out-of-period orders.", source:"Order ledger: cases, paymentStatus, paidAt/placedAt, ownerId/creditedRepId.", owner:"Sales leadership" }),
  define({ key:"paid_orders", label:"Paid orders", shortLabel:"Paid orders", group:"Sales", format:"integer", description:"Orders that reached paid status in the period.", formula:"Count paid orders by collection date.", inclusion:"Paid orders in range.", exclusion:"Unpaid or out-of-period orders.", source:"Order ledger.", owner:"Sales leadership", gamingRisk:"Artificial order splitting can inflate order count." }),
  define({ key:"new_paid_accounts", label:"New paid accounts", shortLabel:"New paid", group:"Sales", format:"integer", description:"Accounts whose first paid order occurred in the period.", formula:"Find each account's earliest paid order; count accounts whose earliest paid date is in range.", inclusion:"Distinct first-ever paid accounts in range.", exclusion:"Accounts first paid before the period.", source:"Full paid-order history by account.", owner:"Sales leadership", auditMethod:"Confirm each counted order is that account's earliest paid order and check duplicate-account risk." }),
  define({ key:"completed_demos", label:"Completed demos", shortLabel:"Demos", group:"Execution", format:"integer", description:"Completed First visit and Sample drop appointments.", formula:"Count completed First visit/Sample drop appointments by completedAt, with scheduled date as legacy fallback.", inclusion:"Completed First visit or Sample drop in range.", exclusion:"Unfinished, delivery, reorder, and placement-only appointments.", source:"Appointment ledger: type, status, completedAt/date, ownerId.", owner:"Sales Manager", gamingRisk:"Duplicate appointments or false completion can inflate activity." }),
  define({ key:"demo_completion_rate", label:"Demo completion rate", shortLabel:"Demo rate", group:"Execution", format:"percent", description:"Share of scheduled demo-type appointments that were completed.", formula:"Completed First visit/Sample drop appointments ÷ all First visit/Sample drop appointments scheduled in range × 100.", inclusion:"Demo appointments scheduled in range.", exclusion:"Non-demo appointment types.", source:"Appointment ledger: date, type, status, ownerId.", owner:"Sales Manager", gamingRisk:"Deleting missed appointments or only scheduling after a visit happens." }),
  define({ key:"new_business_close_rate", label:"New-business close rate", shortLabel:"Close rate", group:"Sales", format:"percent", description:"Share of completed demo decisions that produced an order outcome.", formula:"Completed demo appointments with outcome Order placed ÷ completed demos with Order placed, Follow-up scheduled, No decision, or Closed lost × 100.", inclusion:"Completed First visit/Sample drop with a decision outcome in range.", exclusion:"Missing outcomes and non-demo appointment types.", source:"Appointment closeout ledger.", owner:"Sales Manager", auditMethod:"Trace denominator closeouts and reconcile Order placed outcomes to actual orders before compensation use.", gamingRisk:"Leaving weak outcomes blank or marking Order placed before a real order exists." }),
  define({ key:"reorder_accounts", label:"Accounts with paid reorder", shortLabel:"Reorders", group:"Retention", format:"integer", description:"Distinct accounts with a paid order after their first paid order.", formula:"Classify each account's earliest paid order, then count distinct accounts with a later paid order in range.", inclusion:"Second-or-later paid orders in range.", exclusion:"First paid orders and unpaid reorders.", source:"Full paid-order history by account.", owner:"Sales leadership / Account growth", intendedBehavior:"Keep account health tied to repeat revenue." }),
  define({ key:"reorder_account_share", label:"Reorder account share", shortLabel:"Reorder share", group:"Retention", format:"percent", description:"Share of paid-active accounts that also reordered in the period.", formula:"Distinct accounts with paid reorder in range ÷ distinct accounts with any paid order in range × 100.", inclusion:"Accounts with paid activity in range.", exclusion:"Accounts without paid activity in range.", source:"Paid-order history by account.", owner:"Sales leadership / Account growth", gamingRisk:"Splitting one opening order can falsely resemble repeat activity." }),
  define({ key:"closeout_completeness_rate", label:"Closeout completeness", shortLabel:"Closeout", group:"Execution", format:"percent", description:"Completed sales appointments with the required outcome, note, next action, and next-action date.", formula:"Complete non-delivery sales closeouts ÷ completed non-delivery sales appointments × 100.", inclusion:"Completed First visit, Sample drop, Placement check, and Reorder appointments in range.", exclusion:"Delivery and unfinished appointments.", source:"Appointment closeout fields.", owner:"Sales Manager", gamingRisk:"Low-quality filler text can technically satisfy fields.", actionTriggered:"Return incomplete or low-quality closeouts for correction before forecast or bonus review." }),
  define({ key:"arrival_verification_rate", label:"Verified arrival rate", shortLabel:"Arrival verified", group:"Field accountability", format:"percent", description:"Completed sales-rep field appointments with verified geofenced arrival evidence.", formula:"Completed sales-rep field appointments with Arrival verified event ÷ completed sales-rep field appointments × 100.", inclusion:"Completed First visit, Sample drop, Placement check, or Reorder owned by Sales Representatives.", exclusion:"Delivery, non-sales-rep, and unfinished appointments.", source:"Appointment ledger + field-tracking appointmentEvents.", owner:"Sales Manager / Operations leadership", auditMethod:"Trace appointments to Arrival verified events and geofence evidence; missing evidence stays missing.", intendedBehavior:"Make owner-requested field presence measurable without treating route trails as productivity.", gamingRisk:"Shared devices, mocked browser location, or work completed on an untracked device.", actionTriggered:"Investigate missing verification, permission failure, device setup, and geofence configuration before personnel action." }),
  define({ key:"offsite_exceptions", label:"Offsite continuation exceptions", shortLabel:"Offsite exceptions", group:"Field accountability", format:"integer", description:"Documented visits that continued after leaving the customer geofence.", formula:"Count offsite continuation exception records created in range.", inclusion:"Visible-user exceptions created in range.", exclusion:"Normal closeouts without an exception record.", source:"Field-tracking exception ledger.", owner:"Sales Manager / Operations leadership", auditMethod:"Review linked appointment, departure event, user, and written reason.", gamingRisk:"Habitual or boilerplate exception reasons.", actionTriggered:"Review repeated patterns and fix geofence/workflow problems before treating them as misconduct." }),
];

const definitionMap = new Map(MANAGEMENT_KPI_DEFINITIONS.map((item) => [item.key, item]));
export const managementKpiDefinition = (key: ManagementKpiKey) => definitionMap.get(key)!;
const decisionOutcomes = new Set(["Order placed", "Follow-up scheduled", "No decision", "Closed lost"]);
const demoTypes = new Set<Appointment["type"]>(["First visit", "Sample drop"]);
const fieldSalesTypes = new Set<Appointment["type"]>(["First visit", "Sample drop", "Placement check", "Reorder"]);

export function localDateKey(date = new Date()) { return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`; }
const dateOnly = (value:string) => value.slice(0,10);
const inPeriod = (value:string|undefined, period:KpiPeriod) => Boolean(value && dateOnly(value) >= period.start && dateOnly(value) <= period.end);
const eventDate = (appointment:Appointment) => appointment.completedAt ? dateOnly(appointment.completedAt) : appointment.date;
const paidDate = (order:WorkspaceData["orders"][number]) => dateOnly(order.paidAt ?? order.placedAt);
const orderOwner = (order:WorkspaceData["orders"][number]) => order.creditedRepId ?? order.ownerId;
const unique = (values:string[]) => [...new Set(values)];
const percent = (n:number,d:number) => d > 0 ? n/d*100 : 0;
const visibleUserSet = (ids?:Iterable<string>) => ids ? new Set(ids) : undefined;
const userAllowed = (id:string|undefined, users?:Set<string>) => Boolean(id) && (!users || users.has(id!));
const paidOrders = (data:WorkspaceData, users?:Set<string>) => data.orders.filter((order)=>order.paymentStatus==="Paid" && userAllowed(orderOwner(order),users));

function firstPaidOrderByAccount(data:WorkspaceData){ const first=new Map<string,WorkspaceData["orders"][number]>(); data.orders.filter((o)=>o.paymentStatus==="Paid").forEach((o)=>{const current=first.get(o.accountId); if(!current||paidDate(o)<paidDate(current)||(paidDate(o)===paidDate(current)&&o.id<current.id)) first.set(o.accountId,o);}); return first; }
const completedDemos=(data:WorkspaceData,period:KpiPeriod,users?:Set<string>)=>data.appointments.filter((a)=>userAllowed(a.ownerId,users)&&demoTypes.has(a.type)&&a.status==="Completed"&&inPeriod(eventDate(a),period));
const completedSales=(data:WorkspaceData,period:KpiPeriod,users?:Set<string>)=>data.appointments.filter((a)=>userAllowed(a.ownerId,users)&&fieldSalesTypes.has(a.type)&&a.status==="Completed"&&inPeriod(eventDate(a),period));

export function calculateManagementKpi(key:ManagementKpiKey,data:WorkspaceData,period:KpiPeriod,userIds?:Iterable<string>,tracking?:FieldTrackingState):KpiResult{
  const users=visibleUserSet(userIds); const paid=paidOrders(data,users); const paidInRange=paid.filter((o)=>inPeriod(paidDate(o),period)); const first=firstPaidOrderByAccount(data);
  if(key==="collected_revenue"){const value=paidInRange.reduce((s,o)=>s+o.amount,0);return{key,value,numerator:value,sourceRecordIds:paidInRange.map((o)=>o.id)}}
  if(key==="paid_cases"){const value=paidInRange.reduce((s,o)=>s+o.cases,0);return{key,value,numerator:value,sourceRecordIds:paidInRange.map((o)=>o.id)}}
  if(key==="paid_orders") return{key,value:paidInRange.length,numerator:paidInRange.length,sourceRecordIds:paidInRange.map((o)=>o.id)};
  if(key==="new_paid_accounts"){const rows=[...first.values()].filter((o)=>userAllowed(orderOwner(o),users)&&inPeriod(paidDate(o),period));return{key,value:rows.length,numerator:rows.length,sourceRecordIds:rows.map((o)=>o.id)}}
  if(key==="completed_demos"){const rows=completedDemos(data,period,users);return{key,value:rows.length,numerator:rows.length,sourceRecordIds:rows.map((a)=>a.id)}}
  if(key==="demo_completion_rate"){const all=data.appointments.filter((a)=>userAllowed(a.ownerId,users)&&demoTypes.has(a.type)&&inPeriod(a.date,period));const done=all.filter((a)=>a.status==="Completed");return{key,value:percent(done.length,all.length),numerator:done.length,denominator:all.length,sourceRecordIds:all.map((a)=>a.id)}}
  if(key==="new_business_close_rate"){const done=completedDemos(data,period,users);const decided=done.filter((a)=>Boolean(a.outcome&&decisionOutcomes.has(a.outcome)));const won=decided.filter((a)=>a.outcome==="Order placed");return{key,value:percent(won.length,decided.length),numerator:won.length,denominator:decided.length,sourceRecordIds:decided.map((a)=>a.id)}}
  if(key==="reorder_accounts"||key==="reorder_account_share"){const reorderRows=paidInRange.filter((o)=>first.get(o.accountId)?.id!==o.id);const reorderIds=unique(reorderRows.map((o)=>o.accountId));if(key==="reorder_accounts")return{key,value:reorderIds.length,numerator:reorderIds.length,sourceRecordIds:reorderRows.map((o)=>o.id)};const active=unique(paidInRange.map((o)=>o.accountId));return{key,value:percent(reorderIds.length,active.length),numerator:reorderIds.length,denominator:active.length,sourceRecordIds:paidInRange.map((o)=>o.id)}}
  if(key==="closeout_completeness_rate"){const done=completedSales(data,period,users);const complete=done.filter((a)=>Boolean(a.outcome&&a.closeoutNote?.trim()&&a.nextAction?.trim()&&a.nextActionDate));return{key,value:percent(complete.length,done.length),numerator:complete.length,denominator:done.length,sourceRecordIds:done.map((a)=>a.id)}}
  if(key==="arrival_verification_rate"){const repIds=new Set(data.users.filter((u)=>u.role==="Sales Representative"&&(!users||users.has(u.id))).map((u)=>u.id));const done=completedSales(data,period,repIds);const doneIds=new Set(done.map((a)=>a.id));const events=(tracking?.appointmentEvents??[]).filter((e)=>e.event==="Arrival verified"&&repIds.has(e.userId)&&doneIds.has(e.appointmentId));const verified=new Set(events.map((e)=>e.appointmentId));return{key,value:percent(verified.size,done.length),numerator:verified.size,denominator:done.length,sourceRecordIds:unique([...done.map((a)=>a.id),...events.map((e)=>e.id)])}}
  const exceptions=(tracking?.exceptions??[]).filter((e)=>(!users||users.has(e.userId))&&inPeriod(e.createdAt,period));return{key,value:exceptions.length,numerator:exceptions.length,sourceRecordIds:exceptions.map((e)=>e.id)};
}

export function managementKpiRows(key:ManagementKpiKey,data:WorkspaceData,period:KpiPeriod,users:WorkspaceUser[],tracking?:FieldTrackingState):KpiPersonRow[]{return users.map((u)=>({userId:u.id,name:u.name,role:u.role,team:u.team,result:calculateManagementKpi(key,data,period,[u.id],tracking)})).sort((a,b)=>b.result.value-a.result.value||a.name.localeCompare(b.name));}
const parseDateKey=(value:string)=>{const[y,m,d]=value.split("-").map(Number);return new Date(y,m-1,d,12)};
const keyFromDate=(date:Date)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;
const addDays=(value:string,days:number)=>{const date=parseDateKey(value);date.setDate(date.getDate()+days);return keyFromDate(date)};
const daysInclusive=(period:KpiPeriod)=>Math.max(1,Math.round((parseDateKey(period.end).getTime()-parseDateKey(period.start).getTime())/86_400_000)+1);
export function kpiSeries(key:ManagementKpiKey,data:WorkspaceData,period:KpiPeriod,userIds?:Iterable<string>,tracking?:FieldTrackingState):KpiSeriesPoint[]{const bucket=daysInclusive(period)<=31?1:7;const points:KpiSeriesPoint[]=[];for(let start=period.start;start<=period.end;start=addDays(start,bucket)){const rawEnd=addDays(start,bucket-1);const end=rawEnd>period.end?period.end:rawEnd;points.push({...calculateManagementKpi(key,data,{start,end},userIds,tracking),start,end,label:bucket===1?start.slice(5):`${start.slice(5)}–${end.slice(5)}`})}return points;}
export function kpiPresetPeriod(preset:"7d"|"30d"|"month"|"90d",today=localDateKey()):KpiPeriod{if(preset==="7d")return{start:addDays(today,-6),end:today};if(preset==="30d")return{start:addDays(today,-29),end:today};if(preset==="90d")return{start:addDays(today,-89),end:today};return{start:`${today.slice(0,7)}-01`,end:today};}
export function formatKpiValue(result:Pick<KpiResult,"value">,format:KpiFormat){if(format==="currency")return new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(result.value);if(format==="percent")return`${result.value.toFixed(1)}%`;return Math.round(result.value).toLocaleString("en-US");}
const csvCell=(value:string|number)=>`"${String(value??"").replaceAll('"','""')}"`;
export function managementKpiCsv(definition:KpiDefinition,period:KpiPeriod,rows:KpiPersonRow[],generatedAt:string){const metadata=[["Metric",definition.label],["Period start",period.start],["Period end",period.end],["Generated at",generatedAt],["Formula",definition.formula],["Inclusion",definition.inclusion],["Exclusion",definition.exclusion],["Source",definition.source],["Owner",definition.owner],["Audit method",definition.auditMethod],["Gaming risk",definition.gamingRisk],["Action triggered",definition.actionTriggered]];const detail=[["Employee","Role","Team","Value","Numerator","Denominator","Source record IDs"],...rows.map((r)=>[r.name,r.role,r.team,r.result.value,r.result.numerator,r.result.denominator??"",r.result.sourceRecordIds.join("|")])];return[...metadata.map((r)=>r.map(csvCell).join(",")),"",...detail.map((r)=>r.map(csvCell).join(","))].join("\n");}
