"use client";

import { ReactNode, createContext, useContext, useEffect, useMemo, useState } from "react";
import { MARKETING_STORAGE_KEY, Asset, Campaign, MarketingAttribution, MarketingRequest, MarketingSpend, MarketingState, MarketingTouch, MaterialItem, MaterialMovement, Partnership, createMarketingSeed, materialBalance, normalizeMarketingState } from "./marketing-engine";
import { useWorkspace } from "./workspace-context";

const now=()=>new Date().toISOString();const uid=(prefix:string)=>`${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
type MarketingContextValue={state:MarketingState;submitRequest:(input:Omit<MarketingRequest,"id"|"submittedAt"|"status">)=>string;decideRequest:(id:string,status:"Approved"|"Returned")=>void;fulfillRequest:(id:string)=>void;createCampaign:(input:Omit<Campaign,"id"|"createdAt"|"status">&{status?:Campaign["status"]})=>string;decideCampaign:(id:string,status:"Approved"|"Returned")=>void;setCampaignStatus:(id:string,status:Campaign["status"])=>void;recordSpend:(input:Omit<MarketingSpend,"id"|"submittedAt"|"status"|"submittedBy">)=>string|null;decideSpend:(id:string,status:"Approved"|"Returned")=>void;reconcileSpend:(id:string)=>void;addAsset:(input:Omit<Asset,"id"|"updatedAt"|"updatedBy">)=>string;setAssetStatus:(id:string,status:Asset["status"])=>void;addMaterial:(input:Omit<MaterialItem,"id">)=>string;moveMaterial:(input:Omit<MaterialMovement,"id"|"at"|"actorId">)=>string|null;addTouch:(input:Omit<MarketingTouch,"id"|"createdBy">)=>string;addAttribution:(input:Omit<MarketingAttribution,"id"|"createdAt"|"createdBy"|"reviewed">)=>string;reviewAttribution:(id:string)=>void;addPartnership:(input:Omit<Partnership,"id"|"createdAt"|"ownerId">)=>string;resetMarketing:()=>void};
const MarketingContext=createContext<MarketingContextValue|null>(null);

export function MarketingProvider({children}:{children:ReactNode}){
  const{currentUser}=useWorkspace();const read=()=>{if(typeof window==="undefined")return createMarketingSeed();try{return normalizeMarketingState(JSON.parse(window.localStorage.getItem(MARKETING_STORAGE_KEY)??"null"));}catch{return createMarketingSeed();}};const[state,setState]=useState<MarketingState>(()=>read());
  useEffect(()=>{if(typeof window!=="undefined")window.localStorage.setItem(MARKETING_STORAGE_KEY,JSON.stringify(state));},[state]);
  const submitRequest=(input:Omit<MarketingRequest,"id"|"submittedAt"|"status">)=>{const id=uid("marketing-request");const record:MarketingRequest={...input,id,submittedAt:now(),status:"Submitted"};setState((s)=>({...s,requests:[record,...s.requests]}));return id;};
  const decideRequest=(id:string,status:"Approved"|"Returned")=>setState((s)=>({...s,requests:s.requests.map((request)=>request.id===id&&request.status==="Submitted"?{...request,status,decidedAt:now(),decidedBy:currentUser?.id}:request)}));
  const fulfillRequest=(id:string)=>setState((s)=>{const request=s.requests.find((item)=>item.id===id&&item.status==="Approved");if(!request)return s;let movements=s.materialMovements;if(request.materialItemId&&request.quantity){if(materialBalance(s,request.materialItemId)<request.quantity)return s;movements=[{id:uid("material-movement"),itemId:request.materialItemId,type:"Issue",quantity:request.quantity,accountId:request.accountId,campaignId:request.campaignId,requestId:request.id,reason:`Fulfilled marketing request: ${request.title}`,at:now(),actorId:currentUser?.id??"system"},...movements];}return{...s,materialMovements:movements,requests:s.requests.map((item)=>item.id===id?{...item,status:"Fulfilled",fulfilledAt:now(),fulfilledBy:currentUser?.id}:item)};});
  const createCampaign=(input:Omit<Campaign,"id"|"createdAt"|"status">&{status?:Campaign["status"]})=>{const id=uid("campaign");const record:Campaign={...input,id,createdAt:now(),status:input.status??(input.requestedBudget>0?"Awaiting approval":"Draft")};setState((s)=>({...s,campaigns:[record,...s.campaigns]}));return id;};
  const decideCampaign=(id:string,status:"Approved"|"Returned")=>setState((s)=>({...s,campaigns:s.campaigns.map((campaign)=>campaign.id===id&&campaign.status==="Awaiting approval"?{...campaign,status,approvedBudget:status==="Approved"?campaign.requestedBudget:undefined,approvedAt:now(),approvedBy:currentUser?.id}:campaign)}));
  const setCampaignStatus=(id:string,status:Campaign["status"])=>setState((s)=>({...s,campaigns:s.campaigns.map((campaign)=>campaign.id===id?{...campaign,status}:campaign)}));
  const recordSpend=(input:Omit<MarketingSpend,"id"|"submittedAt"|"status"|"submittedBy">)=>{const campaign=state.campaigns.find((item)=>item.id===input.campaignId);if(!campaign||input.amount<=0||!input.businessPurpose.trim())return null;const id=uid("marketing-spend");const record:MarketingSpend={...input,id,status:"Submitted",submittedBy:currentUser?.id??"system",submittedAt:now()};setState((s)=>({...s,spend:[record,...s.spend]}));return id;};
  const decideSpend=(id:string,status:"Approved"|"Returned")=>setState((s)=>({...s,spend:s.spend.map((spend)=>spend.id===id&&spend.status==="Submitted"?{...spend,status,approvedAt:now(),approvedBy:currentUser?.id}:spend)}));
  const reconcileSpend=(id:string)=>setState((s)=>({...s,spend:s.spend.map((spend)=>spend.id===id&&spend.status==="Approved"?{...spend,status:"Reconciled",reconciledAt:now()}:spend)}));
  const addAsset=(input:Omit<Asset,"id"|"updatedAt"|"updatedBy">)=>{const id=uid("asset");const record:Asset={...input,id,updatedAt:now(),updatedBy:currentUser?.id??"system"};setState((s)=>({...s,assets:[record,...s.assets]}));return id;};
  const setAssetStatus=(id:string,status:Asset["status"])=>setState((s)=>({...s,assets:s.assets.map((asset)=>asset.id===id?{...asset,status,updatedAt:now(),updatedBy:currentUser?.id??"system"}:asset)}));
  const addMaterial=(input:Omit<MaterialItem,"id">)=>{const id=uid("material");setState((s)=>({...s,materials:[{...input,id},...s.materials]}));return id;};
  const moveMaterial=(input:Omit<MaterialMovement,"id"|"at"|"actorId">)=>{if(input.quantity<=0||!input.reason.trim())return null;if(input.type==="Issue"&&materialBalance(state,input.itemId)<input.quantity)return null;const id=uid("material-movement");const record:MaterialMovement={...input,id,at:now(),actorId:currentUser?.id??"system"};setState((s)=>({...s,materialMovements:[record,...s.materialMovements]}));return id;};
  const addTouch=(input:Omit<MarketingTouch,"id"|"createdBy">)=>{const id=uid("marketing-touch");setState((s)=>({...s,touches:[{...input,id,createdBy:currentUser?.id??"system"},...s.touches]}));return id;};
  const addAttribution=(input:Omit<MarketingAttribution,"id"|"createdAt"|"createdBy"|"reviewed">)=>{const id=uid("attribution");setState((s)=>({...s,attributions:[{...input,id,createdAt:now(),createdBy:currentUser?.id??"system",reviewed:false},...s.attributions]}));return id;};
  const reviewAttribution=(id:string)=>setState((s)=>({...s,attributions:s.attributions.map((item)=>item.id===id?{...item,reviewed:true,reviewedBy:currentUser?.id,reviewedAt:now()}:item)}));
  const addPartnership=(input:Omit<Partnership,"id"|"createdAt"|"ownerId">)=>{const id=uid("partnership");setState((s)=>({...s,partnerships:[{...input,id,createdAt:now(),ownerId:currentUser?.id??"system"},...s.partnerships]}));return id;};
  const resetMarketing=()=>setState(createMarketingSeed());
  const value=useMemo(()=>({state,submitRequest,decideRequest,fulfillRequest,createCampaign,decideCampaign,setCampaignStatus,recordSpend,decideSpend,reconcileSpend,addAsset,setAssetStatus,addMaterial,moveMaterial,addTouch,addAttribution,reviewAttribution,addPartnership,resetMarketing}),[state,currentUser]);
  return <MarketingContext.Provider value={value}>{children}</MarketingContext.Provider>;
}
export function useMarketing(){const value=useContext(MarketingContext);if(!value)throw new Error("useMarketing must be used inside MarketingProvider");return value;}
