"use client";

import { ReactNode, createContext, useContext, useEffect, useMemo, useState } from "react";
import { useAudit } from "./audit-context";
import { NOTIFICATION_STORAGE_KEY, NotificationDelivery, NotificationPreference, NotificationState, createNotificationSeed, deliveryKey, enabledChannels, normalizeNotificationState, notificationCopy, resolveNotificationRecipients } from "./notification-engine";
import { useRuntimeMode } from "./runtime-mode";
import { useWorkspace } from "./workspace-context";

type NotificationContextValue = { state: NotificationState; currentUserItems: NotificationDelivery[]; unreadCount: number; updatePreference: (userId: string, patch: Partial<NotificationPreference>) => boolean; setEscalationHours: (hours: number) => boolean; markAllRead: () => void; resetNotifications: () => boolean };
const NotificationContext = createContext<NotificationContextValue | null>(null);
const uid = (prefix: string) => `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`;
function readState(users: ReturnType<typeof useWorkspace>["data"]["users"]) { if (typeof window === "undefined") return createNotificationSeed(users); try { return normalizeNotificationState(JSON.parse(window.localStorage.getItem(NOTIFICATION_STORAGE_KEY) ?? "null"), users); } catch { return createNotificationSeed(users); } }

export function NotificationProvider({ children }: { children: ReactNode }) {
  const { data, currentUser } = useWorkspace(); const { audit } = useAudit(); const runtime = useRuntimeMode(); const [state, setState] = useState<NotificationState>(() => readState(data.users));
  useEffect(() => { const handle = window.setTimeout(() => setState((current) => normalizeNotificationState(current, data.users)), 0); return () => window.clearTimeout(handle); }, [data.users]);
  useEffect(() => { if (typeof window !== "undefined") window.localStorage.setItem(NOTIFICATION_STORAGE_KEY, JSON.stringify(state)); }, [state]);
  useEffect(() => { const handle = window.setTimeout(() => setState((current) => { const existing = new Set(current.deliveries.map((item) => deliveryKey(item.sourceEventId, item.recipientUserId, item.channel))); const additions: NotificationDelivery[] = []; for (const event of audit.events.slice(0, 500)) { const copy = notificationCopy(event); for (const userId of resolveNotificationRecipients(event, data)) { const preference = current.preferences.find((item) => item.userId === userId); if (!preference) continue; for (const channel of enabledChannels(preference)) { const key = deliveryKey(event.id, userId, channel); if (existing.has(key)) continue; existing.add(key); additions.push({ id: uid("notice"), sourceEventId: event.id, recipientUserId: userId, channel, title: copy.title, detail: copy.detail, tone: copy.tone, createdAt: event.at, status: channel === "In app" ? "Unread" : "Awaiting integration" }); } } } return additions.length ? { ...current, deliveries: [...additions, ...current.deliveries].slice(0, 12000) } : current; }), 0); return () => window.clearTimeout(handle); }, [audit.events, data]);
  useEffect(() => { const handle = window.setTimeout(() => { const checkedAt = new Date().toISOString(); const nowMs = Date.now(); setState((current) => { const additions: NotificationDelivery[] = []; let changed = false; const updated = current.deliveries.map((delivery) => { if (delivery.channel !== "In app" || delivery.status !== "Unread" || delivery.escalatedAt || delivery.escalationOf || nowMs - new Date(delivery.createdAt).getTime() < current.escalationHours * 3600000) return delivery; const user = data.users.find((item) => item.id === delivery.recipientUserId); const recipients = new Set(data.users.filter((item) => item.role === "Administrator" || item.id === user?.managerId).map((item) => item.id)); recipients.delete(delivery.recipientUserId); let created = false; for (const recipientUserId of recipients) { additions.push({ id: uid("escalation"), sourceEventId: delivery.sourceEventId, recipientUserId, channel: "In app", title: `Escalation: ${delivery.title}`, detail: `${user?.name ?? "A user"} has an unread operational notification beyond the ${current.escalationHours}-hour escalation window.`, tone: "warning", createdAt: checkedAt, status: "Unread", escalationOf: delivery.id }); created = true; } if (!created) return delivery; changed = true; return { ...delivery, escalatedAt: checkedAt }; }); return changed ? { ...current, deliveries: [...additions, ...updated] } : current; }); }, 0); return () => window.clearTimeout(handle); }, [data.users, state.escalationHours]);
  const currentUserItems = useMemo(() => currentUser ? state.deliveries.filter((item) => item.recipientUserId === currentUser.id && item.channel === "In app").sort((a, b) => b.createdAt.localeCompare(a.createdAt)) : [], [currentUser, state.deliveries]);
  const unreadCount = currentUserItems.filter((item) => item.status === "Unread").length;
  const updatePreference = (userId: string, patch: Partial<NotificationPreference>) => { if (!currentUser || (currentUser.role !== "Administrator" && currentUser.id !== userId)) return false; setState((current) => ({ ...current, preferences: current.preferences.map((item) => item.userId === userId ? { ...item, ...patch, userId } : item) })); return true; };
  const setEscalationHours = (hours: number) => { if (currentUser?.role !== "Administrator" || !Number.isFinite(hours) || hours < 1 || hours > 168) return false; setState((current) => ({ ...current, escalationHours: Math.round(hours) })); return true; };
  const markAllRead = () => { if (!currentUser) return; const at = new Date().toISOString(); setState((current) => ({ ...current, deliveries: current.deliveries.map((item) => item.recipientUserId === currentUser.id && item.channel === "In app" && item.status === "Unread" ? { ...item, status: "Read", readAt: at } : item) })); };
  const resetNotifications = () => { if (!runtime.isDemo || currentUser?.role !== "Administrator") return false; setState(createNotificationSeed(data.users)); return true; };
  return <NotificationContext.Provider value={{ state, currentUserItems, unreadCount, updatePreference, setEscalationHours, markAllRead, resetNotifications }}>{children}</NotificationContext.Provider>;
}
export function useNotifications() { const value = useContext(NotificationContext); if (!value) throw new Error("useNotifications must be used inside NotificationProvider"); return value; }
