"use client";

import { ReactNode, createContext, useContext, useEffect, useState } from "react";
import { useHcm } from "./hcm-context";
import { usePeriodLocks } from "./period-lock-context";
import { useRuntimeMode } from "./runtime-mode";
import { PAYROLL_STORAGE_KEY, Disbursement, EmployerTaxRule, PayGroup, PayRun, PayRunStatus, PayrollEmployee, PayrollState, TaxLiability, TaxLiabilityStatus, WithholdingProfile, calculateBonusLine, calculateRegularLine, consumedTimecards, createPayrollSeed, earnedBonusesForMonth, normalizePayrollState } from "./payroll-engine";
import { useWorkspace } from "./workspace-context";

const now=()=>new Date().toISOString();const uid=(prefix:string)=>`${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
type PayrollContextValue={payroll:PayrollState;savePayGroup:(input:Omit<PayGroup,"id">)=>string;savePayrollEmployee:(input:PayrollEmployee)=>void;saveWithholding:(input:WithholdingProfile)=>void;saveEmployerTaxRule:(input:Omit<EmployerTaxRule,"id">)=>string;buildRegularRun:(periodStart:string,periodEnd:string,payDate:string)=>string|null;buildBonusRun:(month:string,payDate:string)=>string|null;setRunStatus:(runId:string,status:"Approved"|"Released",reason?:string)=>boolean;voidAndReissue:(runId:string,reason:string)=>string|null;settleDisbursement:(id:string)=>void;updateLiability:(id:string,status:TaxLiabilityStatus)=>void;resetPayroll:()=>void};
const PayrollContext=createContext<PayrollContextValue|null>(null);

export function PayrollProvider({children}:{children:ReactNode}){
  const{data,currentUser}=useWorkspace();const{hcm}=useHcm();const locks=usePeriodLocks();const runtime=useRuntimeMode();
  const read=()=>{if(typeof window==="undefined")return createPayrollSeed();try{return normalizePayrollState(JSON.parse(window.localStorage.getItem(PAYROLL_STORAGE_KEY)??"null"));}catch{return createPayrollSeed();}};
  const[payroll,setPayroll]=useState<PayrollState>(()=>read());useEffect(()=>{if(typeof window!=="undefined")window.localStorage.setItem(PAYROLL_STORAGE_KEY,JSON.stringify(payroll));},[payroll]);
  const savePayGroup=(input:Omit<PayGroup,"id">)=>{const id=uid("pay-group");setPayroll((state)=>({...state,payGroups:[{...input,id},...state.payGroups]}));return id;};
  const savePayrollEmployee=(input:PayrollEmployee)=>setPayroll((state)=>({...state,employees:[input,...state.employees.filter((item)=>item.userId!==input.userId)]}));
  const saveWithholding=(input:WithholdingProfile)=>setPayroll((state)=>({...state,withholdingProfiles:[input,...state.withholdingProfiles.filter((item)=>!(item.userId===input.userId&&item.effectiveDate===input.effectiveDate))]}));
  const saveEmployerTaxRule=(input:Omit<EmployerTaxRule,"id">)=>{const id=uid("employer-tax");setPayroll((state)=>({...state,employerTaxRules:[{...input,id},...state.employerTaxRules]}));return id;};
  const buildRegularRun=(periodStart:string,periodEnd:string,payDate:string)=>{if(!currentUser||currentUser.role!=="Administrator"||!periodStart||!periodEnd||!payDate||periodEnd<periodStart||locks.isRangeLocked("Payroll",periodStart,periodEnd)||locks.isLocked("Payroll",payDate))return null;const consumed=consumedTimecards(payroll);const ready=data.timecards.filter((card)=>["Manager approved","Payroll ready"].includes(card.status)&&card.weekStart>=periodStart&&card.weekEnd<=periodEnd&&!consumed.has(card.id));const employeeIds=[...new Set(ready.map((card)=>card.userId))];const lines=employeeIds.map((employeeId)=>calculateRegularLine(payroll,data,hcm,employeeId,periodStart,periodEnd,ready.filter((card)=>card.userId===employeeId).map((card)=>card.id))).filter((line):line is NonNullable<typeof line>=>Boolean(line));if(!lines.length)return null;const id=uid("pay-run");const run:PayRun={id,kind:"Regular",createdAt:now(),periodStart,periodEnd,payDate,status:"Draft",lines};setPayroll((state)=>({...state,runs:[run,...state.runs]}));return id;};
  const buildBonusRun=(month:string,payDate:string)=>{if(!currentUser||currentUser.role!=="Administrator"||!/^\d{4}-\d{2}$/.test(month)||!payDate)return null;const start=`${month}-01`;const monthDate=new Date(`${start}T12:00:00`);const end=new Date(monthDate.getFullYear(),monthDate.getMonth()+1,0,12).toISOString().slice(0,10);if(locks.isRangeLocked("Payroll",start,end)||locks.isLocked("Payroll",payDate))return null;const earnings=earnedBonusesForMonth(payroll,data,month);const byEmployee=new Map<string,{amount:number;ids:string[]}>();for(const item of earnings){const current=byEmployee.get(item.signal.repId)??{amount:0,ids:[]};current.amount+=item.signal.amount;current.ids.push(item.signal.id);byEmployee.set(item.signal.repId,current);}const lines=[...byEmployee.entries()].map(([employeeId,earning])=>calculateBonusLine(payroll,hcm,employeeId,payDate,earning.amount,earning.ids)).filter((line):line is NonNullable<typeof line>=>Boolean(line));if(!lines.length)return null;const id=uid("bonus-run");const run:PayRun={id,kind:"Monthly bonus",createdAt:now(),periodStart:start,periodEnd:end,payDate,status:"Draft",lines};setPayroll((state)=>({...state,runs:[run,...state.runs]}));return id;};
  const runLocked=(run:PayRun)=>locks.isRangeLocked("Payroll",run.periodStart,run.periodEnd)||locks.isLocked("Payroll",run.payDate);
  const setRunStatus=(runId:string,status:"Approved"|"Released")=>{if(!currentUser||currentUser.role!=="Administrator")return false;const run=payroll.runs.find((item)=>item.id===runId);if(!run||runLocked(run))return false;if(status==="Approved"&&run.status!=="Draft")return false;if(status==="Released"&&run.status!=="Approved")return false;if(status==="Approved"){setPayroll((state)=>({...state,runs:state.runs.map((item)=>item.id===runId?{...item,status:"Approved" as PayRunStatus,approvedAt:now(),approvedBy:currentUser.id}:item)}));return true;}const liabilities:TaxLiability[]=[{id:uid("tax"),payRunId:runId,type:"Federal employee",amount:run.lines.reduce((sum,line)=>sum+line.federalTax+line.additionalWithholding,0),status:"Accrued",createdAt:now()},{id:uid("tax"),payRunId:runId,type:"State employee",amount:run.lines.reduce((sum,line)=>sum+line.stateTax,0),status:"Accrued",createdAt:now()},{id:uid("tax"),payRunId:runId,type:"Local employee",amount:run.lines.reduce((sum,line)=>sum+line.localTax,0),status:"Accrued",createdAt:now()},{id:uid("tax"),payRunId:runId,type:"Employer",amount:run.lines.reduce((sum,line)=>sum+line.employerTaxes,0),status:"Accrued",createdAt:now()}].filter((item)=>item.amount>0);const disbursements:Disbursement[]=run.lines.map((line)=>{const employee=payroll.employees.find((item)=>item.userId===line.employeeId);return{id:uid("disbursement"),payRunId:runId,userId:line.employeeId,amount:line.netPay,method:employee?.paymentMethod??"Manual",tokenLabel:employee?.paymentTokenLabel??"",status:"Released",createdAt:now()};});setPayroll((state)=>({...state,runs:state.runs.map((item)=>item.id===runId?{...item,status:"Released" as PayRunStatus,releasedAt:now(),releasedBy:currentUser.id}:item),liabilities:[...liabilities,...state.liabilities],disbursements:[...disbursements,...state.disbursements]}));return true;};
  const voidAndReissue=(runId:string,reason:string)=>{if(!currentUser||currentUser.role!=="Administrator"||!reason.trim())return null;const original=payroll.runs.find((run)=>run.id===runId&&run.status==="Released");if(!original||runLocked(original))return null;const id=uid("pay-reissue");const reissue:PayRun={...original,id,createdAt:now(),status:"Draft",approvedAt:undefined,approvedBy:undefined,releasedAt:undefined,releasedBy:undefined,voidedAt:undefined,voidedBy:undefined,voidReason:undefined,reissueOf:runId};setPayroll((state)=>({...state,runs:[reissue,...state.runs.map((run):PayRun=>run.id===runId?{...run,status:"Voided",voidedAt:now(),voidedBy:currentUser.id,voidReason:reason.trim()}:run)],liabilities:state.liabilities.map((liability):TaxLiability=>liability.payRunId===runId?{...liability,status:"Reversed"}:liability),disbursements:state.disbursements.map((item):Disbursement=>item.payRunId===runId?{...item,status:"Voided"}:item)}));return id;};
  const settleDisbursement=(id:string)=>{if(!currentUser||currentUser.role!=="Administrator")return;const item=payroll.disbursements.find((entry)=>entry.id===id);const run=payroll.runs.find((entry)=>entry.id===item?.payRunId);if(!item||!run||runLocked(run))return;setPayroll((state)=>({...state,disbursements:state.disbursements.map((entry)=>entry.id===id&&entry.status==="Released"?{...entry,status:"Settled",settledAt:now()}:entry)}));};
  const updateLiability=(id:string,status:TaxLiabilityStatus)=>{if(!currentUser||currentUser.role!=="Administrator")return;const liability=payroll.liabilities.find((entry)=>entry.id===id);const run=payroll.runs.find((entry)=>entry.id===liability?.payRunId);if(!liability||!run||runLocked(run))return;setPayroll((state)=>({...state,liabilities:state.liabilities.map((item)=>item.id===id?{...item,status}:item)}));};
  const resetPayroll=()=>{if(runtime.isDemo&&currentUser?.role==="Administrator")setPayroll(createPayrollSeed());};
  return <PayrollContext.Provider value={{payroll,savePayGroup,savePayrollEmployee,saveWithholding,saveEmployerTaxRule,buildRegularRun,buildBonusRun,setRunStatus,voidAndReissue,settleDisbursement,updateLiability,resetPayroll}}>{children}</PayrollContext.Provider>;
}
export function usePayroll(){const value=useContext(PayrollContext);if(!value)throw new Error("usePayroll must be used inside PayrollProvider");return value;}
