"use client";

import { ReactNode, createContext, useContext, useEffect, useState } from "react";
import { addCalendarDays, isValidCalendarDateKey } from "./date-time";
import { useHcm } from "./hcm-context";
import { payrollCorrectionBlockers, payrollRunControlIssues, voidPayrollRunForCorrection } from "./payroll-controls";
import { disbursementCanRecordFailure, disbursementCanRecordSettlement, disbursementCanRetry, type DisbursementRecord, liabilityCanRecordPaid, liabilityCanSchedule, type TaxLiabilityRecord } from "./payroll-settlement-controls";
import { usePeriodLocks } from "./period-lock-context";
import { useRuntimeMode } from "./runtime-mode";
import { PAYROLL_STORAGE_KEY, BenefitTaxRule, BenefitTaxTreatment, Disbursement, EmployerTaxRule, PayGroup, PayRun, PayRunStatus, PayrollEmployee, PayrollState, TaxLiability, TaxLiabilityStatus, WithholdingProfile, calculateBonusLine, calculateRegularLine, consumedTimecards, createPayrollSeed, earnedBonusesForMonth, normalizePayrollState } from "./payroll-engine";
import { useWorkspace } from "./workspace-context";

const now=()=>new Date().toISOString();const uid=(prefix:string)=>`${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
const validDateKey=(value:string)=>isValidCalendarDateKey(value);
const validMonth=(value:string)=>/^\d{4}-(?:0[1-9]|1[0-2])$/.test(value);
const percentValid=(value:number)=>Number.isFinite(value)&&value>=0&&value<=100;
const frequencies=new Set<PayGroup["frequency"]>(["Weekly","Biweekly","Semimonthly","Monthly"]);
const paymentMethods=new Set<PayrollEmployee["paymentMethod"]>(["ACH","Check","Manual"]);
const monthEndKey=(month:string)=>{if(!validMonth(month))return"";const[year,monthNumber]=month.split("-").map(Number);const nextYear=monthNumber===12?year+1:year;const nextMonth=monthNumber===12?1:monthNumber+1;return addCalendarDays(`${nextYear}-${String(nextMonth).padStart(2,"0")}-01`,-1);};
type LiabilityEvidence={reference?:string;date?:string};
type PayrollContextValue={payroll:PayrollState;savePayGroup:(input:Omit<PayGroup,"id">)=>string;savePayrollEmployee:(input:PayrollEmployee)=>void;saveWithholding:(input:WithholdingProfile)=>void;saveEmployerTaxRule:(input:Omit<EmployerTaxRule,"id">)=>string;saveBenefitTaxRule:(planId:string,tierId:string,treatment:BenefitTaxTreatment,effectiveDate:string)=>string|null;buildRegularRun:(periodStart:string,periodEnd:string,payDate:string)=>string|null;buildBonusRun:(month:string,payDate:string)=>string|null;setRunStatus:(runId:string,status:"Approved"|"Released",reason?:string)=>boolean;voidRunForCorrection:(runId:string,reason:string)=>boolean;voidAndReissue:(runId:string,reason:string)=>string|null;settleDisbursement:(id:string,reference:string,settlementDate:string)=>boolean;failDisbursement:(id:string,reason:string)=>boolean;retryDisbursement:(id:string)=>string|null;updateLiability:(id:string,status:TaxLiabilityStatus,evidence?:LiabilityEvidence)=>boolean;resetPayroll:()=>void};
const PayrollContext=createContext<PayrollContextValue|null>(null);

export function PayrollProvider({children}:{children:ReactNode}){
  const{data,currentUser}=useWorkspace();const{hcm}=useHcm();const locks=usePeriodLocks();const runtime=useRuntimeMode();
  const read=()=>{if(typeof window==="undefined")return createPayrollSeed();try{return normalizePayrollState(JSON.parse(window.localStorage.getItem(PAYROLL_STORAGE_KEY)??"null"));}catch{return createPayrollSeed();}};
  const[payroll,setPayroll]=useState<PayrollState>(()=>read());useEffect(()=>{if(typeof window!=="undefined")window.localStorage.setItem(PAYROLL_STORAGE_KEY,JSON.stringify(payroll));},[payroll]);
  const isAdmin=currentUser?.role==="Administrator";
  const savePayGroup=(input:Omit<PayGroup,"id">)=>{if(!isAdmin||!input.name.trim()||!frequencies.has(input.frequency)||!Number.isFinite(input.overtimeThresholdHours)||input.overtimeThresholdHours<0||typeof input.active!=="boolean")return"";const id=uid("pay-group");setPayroll((state)=>({...state,payGroups:[{...input,name:input.name.trim(),id},...state.payGroups]}));return id;};
  const savePayrollEmployee=(input:PayrollEmployee)=>{if(!isAdmin||!data.users.some((user)=>user.id===input.userId&&user.role!=="Customer")||!payroll.payGroups.some((group)=>group.id===input.payGroupId&&group.active)||!paymentMethods.has(input.paymentMethod)||typeof input.paymentTokenLabel!=="string")return;setPayroll((state)=>({...state,employees:[input,...state.employees.filter((item)=>item.userId!==input.userId)]}));};
  const saveWithholding=(input:WithholdingProfile)=>{if(!isAdmin||!data.users.some((user)=>user.id===input.userId&&user.role!=="Customer")||!validDateKey(input.effectiveDate)||![input.federalPercent,input.statePercent,input.localPercent].every(percentValid)||![input.additionalWithholding,input.postTaxDeduction].every((value)=>Number.isFinite(value)&&value>=0))return;setPayroll((state)=>({...state,withholdingProfiles:[input,...state.withholdingProfiles.filter((item)=>!(item.userId===input.userId&&item.effectiveDate===input.effectiveDate))]}));};
  const saveEmployerTaxRule=(input:Omit<EmployerTaxRule,"id">)=>{if(!isAdmin||!input.name.trim()||!percentValid(input.percent)||!validDateKey(input.effectiveDate)||typeof input.active!=="boolean")return"";const id=uid("employer-tax");setPayroll((state)=>({...state,employerTaxRules:[{...input,name:input.name.trim(),id},...state.employerTaxRules]}));return id;};
  const saveBenefitTaxRule=(planId:string,tierId:string,treatment:BenefitTaxTreatment,effectiveDate:string)=>{if(!isAdmin||!validDateKey(effectiveDate)||!["Pre-tax","Post-tax"].includes(treatment))return null;const plan=hcm.benefitPlans.find((item)=>item.id===planId);if(!plan||!plan.tiers.some((tier)=>tier.id===tierId))return null;const id=uid("benefit-tax");const rule:BenefitTaxRule={id,planId,tierId,treatment,effectiveDate,active:true};setPayroll((state)=>({...state,benefitTaxRules:[rule,...state.benefitTaxRules.filter((item)=>!(item.planId===planId&&item.tierId===tierId&&item.effectiveDate===effectiveDate))]}));return id;};
  const buildRegularRun=(periodStart:string,periodEnd:string,payDate:string)=>{if(!isAdmin||!validDateKey(periodStart)||!validDateKey(periodEnd)||!validDateKey(payDate)||periodEnd<periodStart||locks.isRangeLocked("Payroll",periodStart,periodEnd)||locks.isLocked("Payroll",payDate))return null;const consumed=consumedTimecards(payroll);const ready=data.timecards.filter((card)=>["Manager approved","Payroll ready"].includes(card.status)&&validDateKey(card.weekStart)&&validDateKey(card.weekEnd)&&card.weekStart>=periodStart&&card.weekEnd<=periodEnd&&!consumed.has(card.id));const employeeIds=[...new Set(ready.map((card)=>card.userId))];if(!employeeIds.length)return null;const lineCandidates=employeeIds.map((employeeId)=>calculateRegularLine(payroll,data,hcm,employeeId,periodStart,periodEnd,ready.filter((card)=>card.userId===employeeId).map((card)=>card.id)));const lines=lineCandidates.filter((line):line is NonNullable<typeof line>=>Boolean(line));if(lines.length!==employeeIds.length)return null;const id=uid("pay-run");const run:PayRun={id,kind:"Regular",createdAt:now(),periodStart,periodEnd,payDate,status:"Draft",lines};setPayroll((state)=>{const alreadyConsumed=consumedTimecards(state);if(lines.some((line)=>line.sourceTimecardIds.some((sourceId)=>alreadyConsumed.has(sourceId))))return state;return{...state,runs:[run,...state.runs]};});return id;};
  const buildBonusRun=(month:string,payDate:string)=>{if(!isAdmin||!validMonth(month)||!validDateKey(payDate))return null;const start=`${month}-01`;const end=monthEndKey(month);if(!end||locks.isRangeLocked("Payroll",start,end)||locks.isLocked("Payroll",payDate))return null;const earnings=earnedBonusesForMonth(payroll,data,month);const byEmployee=new Map<string,{amount:number;ids:string[]}>();for(const item of earnings){const current=byEmployee.get(item.signal.repId)??{amount:0,ids:[]};current.amount+=item.signal.amount;current.ids.push(item.signal.id);byEmployee.set(item.signal.repId,current);}if(!byEmployee.size)return null;const lineCandidates=[...byEmployee.entries()].map(([employeeId,earning])=>calculateBonusLine(payroll,hcm,employeeId,payDate,earning.amount,earning.ids));const lines=lineCandidates.filter((line):line is NonNullable<typeof line>=>Boolean(line));if(lines.length!==byEmployee.size)return null;const id=uid("bonus-run");const run:PayRun={id,kind:"Monthly bonus",createdAt:now(),periodStart:start,periodEnd:end,payDate,status:"Draft",lines};setPayroll((state)=>{const consumed=new Set(state.runs.filter((item)=>item.status!=="Voided").flatMap((item)=>item.lines.flatMap((line)=>line.sourceBonusIds)));if(lines.some((line)=>line.sourceBonusIds.some((sourceId)=>consumed.has(sourceId))))return state;return{...state,runs:[run,...state.runs]};});return id;};
  const runLocked=(run:PayRun)=>locks.isRangeLocked("Payroll",run.periodStart,run.periodEnd)||locks.isLocked("Payroll",run.payDate);
  const runSourcesInvalid=(run:PayRun)=>payrollRunControlIssues(payroll,data,hcm,run).length>0;
  const setRunStatus=(runId:string,status:"Approved"|"Released")=>{if(!isAdmin||!currentUser)return false;const run=payroll.runs.find((item)=>item.id===runId);if(!run||runLocked(run)||runSourcesInvalid(run))return false;if(status==="Approved"&&run.status!=="Draft")return false;if(status==="Released"&&run.status!=="Approved")return false;if(status==="Approved"){setPayroll((state)=>({...state,runs:state.runs.map((item)=>item.id===runId&&item.status==="Draft"?{...item,status:"Approved" as PayRunStatus,approvedAt:now(),approvedBy:currentUser.id}:item)}));return true;}const liabilityCandidates:TaxLiability[]=[{id:uid("tax"),payRunId:runId,type:"Federal employee",amount:run.lines.reduce((sum,line)=>sum+line.federalTax+line.additionalWithholding,0),status:"Accrued",createdAt:now()},{id:uid("tax"),payRunId:runId,type:"State employee",amount:run.lines.reduce((sum,line)=>sum+line.stateTax,0),status:"Accrued",createdAt:now()},{id:uid("tax"),payRunId:runId,type:"Local employee",amount:run.lines.reduce((sum,line)=>sum+line.localTax,0),status:"Accrued",createdAt:now()},{id:uid("tax"),payRunId:runId,type:"Employer",amount:run.lines.reduce((sum,line)=>sum+line.employerTaxes,0),status:"Accrued",createdAt:now()}];if(liabilityCandidates.some((item)=>!Number.isFinite(item.amount)||item.amount<0))return false;const liabilities=liabilityCandidates.filter((item)=>item.amount>0);const disbursements:Disbursement[]=run.lines.filter((line)=>line.netPay>0).map((line)=>{const employee=payroll.employees.find((item)=>item.userId===line.employeeId);return{id:uid("disbursement"),payRunId:runId,userId:line.employeeId,amount:line.netPay,method:employee?.paymentMethod??"Manual",tokenLabel:employee?.paymentTokenLabel??"",status:"Released",createdAt:now()};});if(disbursements.some((item)=>!Number.isFinite(item.amount)||item.amount<=0))return false;setPayroll((state)=>{const liveRun=state.runs.find((item)=>item.id===runId);if(!liveRun||liveRun.status!=="Approved"||state.liabilities.some((item)=>item.payRunId===runId)||state.disbursements.some((item)=>item.payRunId===runId))return state;return{...state,runs:state.runs.map((item)=>item.id===runId?{...item,status:"Released" as PayRunStatus,releasedAt:now(),releasedBy:currentUser.id}:item),liabilities:[...liabilities,...state.liabilities],disbursements:[...disbursements,...state.disbursements]};});return true;};
  const voidRunForCorrection=(runId:string,reason:string)=>{if(!isAdmin||!currentUser||!reason.trim())return false;const run=payroll.runs.find((item)=>item.id===runId);if(!run||runLocked(run))return false;const next=voidPayrollRunForCorrection(payroll,runId,currentUser.id,reason.trim(),now());if(!next)return false;setPayroll(next);return true;};
  const voidAndReissue=(runId:string,reason:string)=>{if(!isAdmin||!currentUser||!reason.trim())return null;const original=payroll.runs.find((run)=>run.id===runId&&run.status==="Released");if(!original||runLocked(original)||runSourcesInvalid(original)||payrollCorrectionBlockers(payroll,original).length>0)return null;const id=uid("pay-reissue");const reissue:PayRun={...original,id,createdAt:now(),status:"Draft",approvedAt:undefined,approvedBy:undefined,releasedAt:undefined,releasedBy:undefined,voidedAt:undefined,voidedBy:undefined,voidReason:undefined,reissueOf:runId};const voided=voidPayrollRunForCorrection(payroll,runId,currentUser.id,reason.trim(),now());if(!voided)return null;setPayroll({...voided,runs:[reissue,...voided.runs]});return id;};
  const settleDisbursement=(id:string,reference:string,settlementDate:string)=>{if(!isAdmin)return false;const item=payroll.disbursements.find((entry)=>entry.id===id);if(!item||!disbursementCanRecordSettlement(item,reference,settlementDate))return false;setPayroll((state)=>({...state,disbursements:state.disbursements.map((entry)=>{if(entry.id!==id||entry.status!=="Released")return entry;const updated:DisbursementRecord={...entry,status:"Settled",settledAt:settlementDate,settlementReference:reference.trim()};return updated;})}));return true;};
  const failDisbursement=(id:string,reason:string)=>{if(!isAdmin||!currentUser)return false;const item=payroll.disbursements.find((entry)=>entry.id===id);if(!item||!disbursementCanRecordFailure(item,reason))return false;const failedAt=now();setPayroll((state)=>({...state,disbursements:state.disbursements.map((entry)=>{if(entry.id!==id||entry.status!=="Released")return entry;const updated:DisbursementRecord={...entry,status:"Failed",failedAt,failedBy:currentUser.id,failureReason:reason.trim()};return updated;})}));return true;};
  const retryDisbursement=(id:string)=>{if(!isAdmin)return null;const item=payroll.disbursements.find((entry)=>entry.id===id);const run=payroll.runs.find((entry)=>entry.id===item?.payRunId);const employee=payroll.employees.find((entry)=>entry.userId===item?.userId&&entry.active);if(!item||!run||!employee||run.status!=="Released"||runLocked(run)||runSourcesInvalid(run)||!disbursementCanRetry(item)||!Number.isFinite(item.amount)||item.amount<=0)return null;const replacementId=uid("disbursement-retry");const replacement:DisbursementRecord={id:replacementId,payRunId:item.payRunId,userId:item.userId,amount:item.amount,method:employee.paymentMethod,tokenLabel:employee.paymentTokenLabel,status:"Released",createdAt:now(),retryOf:item.id};setPayroll((state)=>{const live=state.disbursements.find((entry)=>entry.id===id);if(!live||!disbursementCanRetry(live))return state;return{...state,disbursements:[replacement,...state.disbursements.map((entry)=>{if(entry.id!==id)return entry;const failed:DisbursementRecord={...entry,replacedBy:replacementId};return failed;})]};});return replacementId;};
  const updateLiability=(id:string,status:TaxLiabilityStatus,evidence:LiabilityEvidence={})=>{if(!isAdmin||!currentUser)return false;const liability=payroll.liabilities.find((entry)=>entry.id===id);if(!liability||!Number.isFinite(liability.amount)||liability.amount<=0)return false;if(status==="Scheduled"){const run=payroll.runs.find((entry)=>entry.id===liability.payRunId);if(!run||run.status!=="Released"||runLocked(run)||runSourcesInvalid(run)||!liabilityCanSchedule(liability))return false;const scheduledAt=now();setPayroll((state)=>({...state,liabilities:state.liabilities.map((entry)=>{if(entry.id!==id||entry.status!=="Accrued")return entry;const updated:TaxLiabilityRecord={...entry,status:"Scheduled",scheduledAt,scheduledBy:currentUser.id};return updated;})}));return true;}if(status==="Paid"){const reference=evidence.reference??"";const paidDate=evidence.date??"";if(!liabilityCanRecordPaid(liability,reference,paidDate))return false;setPayroll((state)=>({...state,liabilities:state.liabilities.map((entry)=>{if(entry.id!==id||entry.status!=="Scheduled")return entry;const updated:TaxLiabilityRecord={...entry,status:"Paid",paidAt:paidDate,paidBy:currentUser.id,paymentReference:reference.trim()};return updated;})}));return true;}return false;};
  const resetPayroll=()=>{if(runtime.isDemo&&isAdmin)setPayroll(createPayrollSeed());};
  return <PayrollContext.Provider value={{payroll,savePayGroup,savePayrollEmployee,saveWithholding,saveEmployerTaxRule,saveBenefitTaxRule,buildRegularRun,buildBonusRun,setRunStatus,voidRunForCorrection,voidAndReissue,settleDisbursement,failDisbursement,retryDisbursement,updateLiability,resetPayroll}}>{children}</PayrollContext.Provider>;
}
export function usePayroll(){const value=useContext(PayrollContext);if(!value)throw new Error("usePayroll must be used inside PayrollProvider");return value;}
