import { ACCOUNT_PRICING_TIERS } from "./account-health";
import type { WorkspaceData } from "./types";

export const PARTNER_PRICING_RULE = {casePack:24,partnerPricePerCan:1,partnerPricePerCase:24,introDays:60,minimumOpeningCases:10,introQualificationCases:20,rollingWindowDays:90,rollingQualificationCases:20};
export type PartnerPricingStatus="Not started"|"Intro partner pricing"|"Partner pricing"|"Standard pricing";
export type PartnerPricingEvaluation={accountId:string;status:PartnerPricingStatus;firstOrderDate?:string;currentWindowStart?:string;currentWindowEnd?:string;countedCases:number;thresholdCases:number;partnerPricePerCase:number;currentPricePerCase?:number;reason:string;nextReviewDate?:string;evidenceOrderIds:string[]};
const dateAtNoon=(value:string)=>new Date(`${value}T12:00:00`);const dateKey=(date:Date)=>date.toISOString().slice(0,10);const addDays=(value:string,days:number)=>{const date=dateAtNoon(value);date.setDate(date.getDate()+days);return dateKey(date);};const isPaid=(order:WorkspaceData["orders"][number])=>order.paymentStatus==="Paid";
export function evaluatePartnerPricing(data:WorkspaceData,accountId:string,asOf=new Date()):PartnerPricingEvaluation{
  const account=data.accounts.find((item)=>item.id===accountId);const orders=data.orders.filter((order)=>order.accountId===accountId).sort((a,b)=>a.placedAt.localeCompare(b.placedAt));const paidOrders=orders.filter(isPaid);const firstOrder=orders[0];
  if(account?.pricingTier){const tier=ACCOUNT_PRICING_TIERS[account.pricingTier];const rollingStart=addDays(dateKey(asOf),-90);const rolling=paidOrders.filter((order)=>(order.paidAt??order.placedAt)>rollingStart&&(order.paidAt??order.placedAt)<=dateKey(asOf));const countedCases=rolling.reduce((sum,order)=>sum+order.cases,0);return{accountId,status:account.pricingTier==="A"?"Partner pricing":"Standard pricing",firstOrderDate:firstOrder?.placedAt,currentWindowStart:rollingStart,currentWindowEnd:dateKey(asOf),countedCases,thresholdCases:0,partnerPricePerCase:PARTNER_PRICING_RULE.partnerPricePerCase,currentPricePerCase:tier.pricePerCase,reason:`Pricing tier ${account.pricingTier} is assigned directly on the account at $${tier.pricePerCase.toFixed(2)} per case. Order history is tracked for account health but does not automatically change the tier.`,nextReviewDate:account.categoryReviewDate,evidenceOrderIds:rolling.map((order)=>order.id)};}
  const rule=PARTNER_PRICING_RULE;const asOfKey=dateKey(asOf);const paidBetween=(start:string,end:string,includeStart=false)=>paidOrders.filter((order)=>(includeStart?order.placedAt>=start:order.placedAt>start)&&order.placedAt<=end);const cases=(items:typeof paidOrders)=>items.reduce((sum,order)=>sum+order.cases,0);
  if(!firstOrder)return{accountId,status:"Not started",countedCases:0,thresholdCases:rule.introQualificationCases,partnerPricePerCase:rule.partnerPricePerCase,reason:"No manual A/B/C pricing tier is assigned and no opening order exists.",evidenceOrderIds:[]};
  const firstOrderDate=firstOrder.placedAt;const introEnd=addDays(firstOrderDate,rule.introDays);const openingQualified=firstOrder.cases>=rule.minimumOpeningCases;const introOrders=paidBetween(firstOrderDate,introEnd,true);const introCases=cases(introOrders);
  if(asOfKey<=introEnd)return{accountId,status:openingQualified?"Intro partner pricing":"Standard pricing",firstOrderDate,currentWindowStart:firstOrderDate,currentWindowEnd:introEnd,countedCases:introCases,thresholdCases:rule.introQualificationCases,partnerPricePerCase:rule.partnerPricePerCase,currentPricePerCase:openingQualified?rule.partnerPricePerCase:undefined,reason:openingQualified?`Legacy eligibility fallback: $${rule.partnerPricePerCase.toFixed(2)} during the first ${rule.introDays} days. Assign A, B, or C on the account to use the current manual pricing workflow.`:`No manual tier is assigned and the opening order did not meet the legacy introductory threshold.`,nextReviewDate:introEnd,evidenceOrderIds:introOrders.map((order)=>order.id)};
  let partnerActive=openingQualified&&introCases>=rule.introQualificationCases;let periodStart=introEnd;
  const findReentry=(inactiveSince:string,through:string)=>{const candidates=paidOrders.filter((order)=>order.placedAt>inactiveSince&&order.placedAt<=through);for(const order of candidates){const trailingStart=addDays(order.placedAt,-rule.rollingWindowDays);const trailing=paidOrders.filter((candidate)=>candidate.placedAt>trailingStart&&candidate.placedAt<=order.placedAt);if(cases(trailing)>=rule.rollingQualificationCases)return{date:order.placedAt,evidence:trailing};}return null;};
  while(periodStart<=asOfKey){if(partnerActive){const periodEnd=addDays(periodStart,rule.rollingWindowDays);const periodOrders=paidBetween(periodStart,periodEnd);const periodCases=cases(periodOrders);if(asOfKey<=periodEnd)return{accountId,status:"Partner pricing",firstOrderDate,currentWindowStart:periodStart,currentWindowEnd:periodEnd,countedCases:periodCases,thresholdCases:rule.rollingQualificationCases,partnerPricePerCase:rule.partnerPricePerCase,currentPricePerCase:rule.partnerPricePerCase,reason:`Legacy eligibility fallback is active. Assign an A/B/C tier to stop automatic eligibility evaluation for this account.`,nextReviewDate:periodEnd,evidenceOrderIds:periodOrders.map((order)=>order.id)};if(periodCases>=rule.rollingQualificationCases){periodStart=periodEnd;continue;}partnerActive=false;periodStart=periodEnd;continue;}
    const reentry=findReentry(periodStart,asOfKey);if(!reentry){const trailingStart=addDays(asOfKey,-rule.rollingWindowDays);const trailingOrders=paidOrders.filter((order)=>order.placedAt>trailingStart&&order.placedAt<=asOfKey);const trailingCases=cases(trailingOrders);return{accountId,status:"Standard pricing",firstOrderDate,currentWindowStart:trailingStart,currentWindowEnd:asOfKey,countedCases:trailingCases,thresholdCases:rule.rollingQualificationCases,partnerPricePerCase:rule.partnerPricePerCase,reason:"Legacy eligibility fallback is inactive. Assign A, B, or C on the account for the current manual pricing workflow.",evidenceOrderIds:trailingOrders.map((order)=>order.id)};}partnerActive=true;periodStart=reentry.date;}
  return{accountId,status:partnerActive?"Partner pricing":"Standard pricing",firstOrderDate,currentWindowStart:periodStart,currentWindowEnd:addDays(periodStart,rule.rollingWindowDays),countedCases:0,thresholdCases:rule.rollingQualificationCases,partnerPricePerCase:rule.partnerPricePerCase,currentPricePerCase:partnerActive?rule.partnerPricePerCase:undefined,reason:"Legacy eligibility fallback. Assign an A/B/C tier to use the current manual pricing workflow.",nextReviewDate:partnerActive?addDays(periodStart,rule.rollingWindowDays):undefined,evidenceOrderIds:[]};
}
