from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]

def replace_once(path,old,new):
    p=ROOT/path;text=p.read_text();count=text.count(old)
    if count!=1:raise SystemExit(f"PATCH FAILED {path}: {count} matches for {old[:140]!r}")
    p.write_text(text.replace(old,new,1));print(f"patched {path}")

def replace_between(path,start,end,replacement):
    p=ROOT/path;text=p.read_text();a=text.find(start)
    if a<0:raise SystemExit(f"PATCH FAILED {path}: start not found {start[:120]!r}")
    b=text.find(end,a)
    if b<0:raise SystemExit(f"PATCH FAILED {path}: end not found {end[:120]!r}")
    p.write_text(text[:a]+replacement.rstrip()+"\n\n"+text[b:]);print(f"patched {path}")

# 1. Sales reps may complete factual new-account setup for accounts they own, but credit/terms remain management decisions.
replace_between("lib/workspace-context.tsx","  const updateCustomerCommercial=","  const claimUnassignedProspect=",'''  const updateCustomerCommercial=(customerId:string,patch:CommercialCustomerPatch)=>{
    if(!currentUser)return false;
    const customer=(data.customers??[]).find((item)=>item.id===customerId);if(!customer)return false;
    const management=["Administrator","Sales Manager"].includes(currentUser.role);
    const repOwned=currentUser.role==="Sales Representative"&&data.accounts.some((account)=>account.customerId===customerId&&account.ownerId===currentUser.id);
    if(!management&&!repOwned)return false;
    let clean:CommercialCustomerPatch={...patch};
    if(repOwned&&!management){
      if(patch.paymentTerms&&patch.paymentTerms!=="COD")return false;
      if(patch.creditStatus&&patch.creditStatus!=="Credit Requested"&&patch.creditStatus!==customer.creditStatus)return false;
      if(patch.onboardingPackageStatus&&!(["Not started","Prepared"] as string[]).includes(patch.onboardingPackageStatus))return false;
      clean={
        billingContactName:patch.billingContactName,billingEmail:patch.billingEmail,billingPhone:patch.billingPhone,
        ein:patch.ein,accountsPayableContactName:patch.accountsPayableContactName,accountsPayablePhone:patch.accountsPayablePhone,accountsPayableEmail:patch.accountsPayableEmail,
        az5000Number:patch.az5000Number,taxExemptionStatus:patch.taxExemptionStatus,notes:patch.notes,
        ...(patch.creditStatus==="Credit Requested"?{creditStatus:"Credit Requested" as const}:{}),
        ...(patch.onboardingPackageStatus?{onboardingPackageStatus:patch.onboardingPackageStatus}:{}),
      };
    }
    if(clean.paymentTerms==="Net 30"&&clean.creditStatus!=="Net 30 Approved"&&customer.creditStatus!=="Net 30 Approved")return false;
    if(clean.paymentTerms==="Custom"&&!clean.customPaymentTerms?.trim())return false;
    if(management&&!clean.paymentTerms)clean.paymentTerms=customer.paymentTerms??"COD";
    setCommercial((state)=>({...state,customerPatches:{...state.customerPatches,[customerId]:{...(state.customerPatches[customerId]??{}),...clean}},activities:[{id:uid("act-customer-commercial"),accountId:data.accounts.find((account)=>account.customerId===customerId)?.id,type:"note",title:management?"Customer commercial setup updated":"Customer onboarding information updated",detail:`${customer.name} setup updated by ${currentUser.name}.`,at:now(),userId:currentUser.id},...state.activities]}));
    window.setTimeout(()=>void momentumStorage.flush(),0);
    return true;
  };''')
# More collision-resistant order number while retaining GE prefix.
replace_once("lib/workspace-context.tsx",'''const id=uid("ord");const number=`GE-${Date.now().toString().slice(-9)}`;''','''const id=uid("ord");const number=`GE-${Date.now().toString().slice(-9)}-${Math.floor(Math.random()*1000).toString().padStart(3,"0")}`;''')

# 2. Account setup: reps can enter factual setup and request credit, management controls approval/terms/program pricing.
replace_between("components/pages/operations-tools.tsx","export function AccountSetupPage()","export function ProductsPage()",'''export function AccountSetupPage(){
  const{data,scope,currentUser,updateCustomerCommercial,updateAccountCommercial}=useWorkspace();
  const[accountId,setAccountId]=useState(scope.accounts[0]?.id??"");const[message,setMessage]=useState("");
  if(!currentUser)return null;
  const account=scope.accounts.find(a=>a.id===accountId);const customer=(data.customers??[]).find(c=>c.id===account?.customerId);const management=["Administrator","Sales Manager"].includes(currentUser.role);
  const saveCustomer=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!customer)return;const form=new FormData(e.currentTarget);const requestCredit=String(form.get("requestCredit")||"no")==="yes";const patch={billingContactName:String(form.get("billingName")||""),billingEmail:String(form.get("billingEmail")||""),billingPhone:String(form.get("billingPhone")||""),ein:String(form.get("ein")||""),az5000Number:String(form.get("az5000")||""),accountsPayableContactName:String(form.get("apName")||""),accountsPayableEmail:String(form.get("apEmail")||""),accountsPayablePhone:String(form.get("apPhone")||""),onboardingPackageStatus:String(form.get("onboarding")||"Not started") as typeof customer.onboardingPackageStatus,...(management?{creditStatus:String(form.get("creditStatus")||"COD") as typeof customer.creditStatus,paymentTerms:String(form.get("paymentTerms")||"COD") as typeof customer.paymentTerms,onboardingProviderStatus:"Provider not selected" as const}:requestCredit?{creditStatus:"Credit Requested" as const}:{})};const ok=updateCustomerCommercial(customer.id,patch);setMessage(ok?management?"Customer commercial setup saved.":requestCredit?"Account setup saved and credit review requested.":"Account setup saved. COD remains the payment default.":"Setup was not saved. Review the fields and authorized credit/payment state.")};
  const saveProgram=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!account||!management)return;const form=new FormData(e.currentTarget);const ok=updateAccountCommercial(account.id,{programPricingLabel:String(form.get("label")||""),programPricePerCase:Number(form.get("price")||0),programPricingEffectiveDate:String(form.get("effective")||""),programPricingExpirationDate:String(form.get("expires")||""),programPricingStatus:String(form.get("status")||"Draft") as typeof account.programPricingStatus});setMessage(ok?"Program pricing saved.":"Program pricing was not saved. Review dates and price.")};
  const warning=account?.programPricingExpirationDate?Math.ceil((new Date(`${account.programPricingExpirationDate}T12:00:00`).getTime()-new Date(`${arizonaDateKey()}T12:00:00`).getTime())/86400000):undefined;
  return <div className="page"><PageHeader eyebrow="CRM & sales" title="New Account Setup" description="Capture the business once. COD is the default. Credit approval, external credit checks and e-sign remain controlled management/provider steps."/><Field label="Location"><select value={accountId} onChange={e=>{setAccountId(e.target.value);setMessage("")}}>{scope.accounts.map(a=><option key={a.id} value={a.id}>{a.locationName??a.name}</option>)}</select></Field>
  {customer&&<Section title="Company & billing" description={management?"Management may also set approved credit/payment terms.":"Sales may capture factual onboarding information and request a credit review. Sales cannot approve credit or Net terms."}><form className="form-grid" key={customer.id} onSubmit={saveCustomer}><Field label="Company"><input readOnly value={customer.name}/></Field><Field label="Billing contact"><input name="billingName" defaultValue={customer.billingContactName??""}/></Field><Field label="Billing email"><input name="billingEmail" type="email" defaultValue={customer.billingEmail??""}/></Field><Field label="Billing phone"><input name="billingPhone" defaultValue={customer.billingPhone??""}/></Field><Field label="EIN"><input name="ein" defaultValue={customer.ein??""}/></Field><Field label="AZ-5000"><input name="az5000" defaultValue={customer.az5000Number??""}/></Field><Field label="A/P contact"><input name="apName" defaultValue={customer.accountsPayableContactName??""}/></Field><Field label="A/P email"><input name="apEmail" type="email" defaultValue={customer.accountsPayableEmail??""}/></Field><Field label="A/P phone"><input name="apPhone" defaultValue={customer.accountsPayablePhone??""}/></Field>{management?<><Field label="Credit status"><select name="creditStatus" defaultValue={customer.creditStatus??"COD"}><option>COD</option><option>Credit Requested</option><option>Credit Under Review</option><option>Net 30 Approved</option><option>Credit Declined</option><option>Personal Guaranty Required</option></select></Field><Field label="Payment terms"><select name="paymentTerms" defaultValue={customer.paymentTerms??"COD"}><option>COD</option><option>Net 30</option><option>Custom</option></select></Field></>:<><Field label="Current payment terms"><input readOnly value={customer.paymentTerms??"COD"}/></Field><Field label="Credit review"><select name="requestCredit" defaultValue="no"><option value="no">No new request</option><option value="yes">Request management review</option></select></Field></>}<Field label="Onboarding package"><select name="onboarding" defaultValue={customer.onboardingPackageStatus??"Not started"}>{management?<><option>Not started</option><option>Prepared</option><option>Awaiting provider</option><option>Sent externally</option><option>Complete</option></>:<><option>Not started</option><option>Prepared</option></>}</select></Field><div className="field--full"><Button type="submit">Save setup</Button></div></form></Section>}
  {account&&<Section title="Program pricing" description="Effective/expiration dates are explicit. Momentum warns inside 30 days.">{management?<form className="form-grid" key={`${account.id}-program`} onSubmit={saveProgram}><Field label="Program"><input name="label" defaultValue={account.programPricingLabel??""}/></Field><Field label="Price / case"><input name="price" type="number" min="0.01" step="0.01" defaultValue={account.programPricePerCase??""}/></Field><Field label="Effective"><input name="effective" type="date" defaultValue={account.programPricingEffectiveDate??""}/></Field><Field label="Expires"><input name="expires" type="date" defaultValue={account.programPricingExpirationDate??""}/></Field><Field label="Status"><select name="status" defaultValue={account.programPricingStatus??"Draft"}><option>Draft</option><option>Scheduled</option><option>Active</option><option>Expired</option><option>Cancelled</option></select></Field>{warning!==undefined&&warning>=0&&warning<=30&&<div className="form-callout field--full"><p>Pricing expires in {warning} day{warning===1?"":"s"}. This is the 30-day warning window.</p></div>}<div className="field--full"><Button type="submit">Save program pricing</Button></div></form>:<div className="company-rule-facts"><div><span>Program</span><strong>{account.programPricingLabel??"No special program"}</strong></div><div><span>Price / case</span><strong>{account.programPricePerCase?`$${account.programPricePerCase.toFixed(2)}`:"Standard account pricing"}</strong></div><div><span>Effective</span><strong>{account.programPricingEffectiveDate??"Not set"}</strong></div><div><span>Expires</span><strong>{account.programPricingExpirationDate??"Not set"}</strong></div>{warning!==undefined&&warning>=0&&warning<=30&&<div><span>Warning</span><strong>Expires in {warning} day{warning===1?"":"s"}</strong></div>}</div>}</Section>}{message&&<p className="form-notice">{message}</p>}</div>
}''')
# Remove an unused import discovered during review.
replace_once("components/pages/operations-tools.tsx",'''import { latestProspectRating, prospectRatingColor, weeklyVisitSummary } from "../../lib/sales-field-engine";''','''import { prospectRatingColor, weeklyVisitSummary } from "../../lib/sales-field-engine";''')

# 3. Employee directory editor always starts from the selected employee and never blanks a phone by accident.
replace_once("components/hcm/employee-directory.tsx",'''import { useMemo, useState } from "react";''','''import { useEffect, useMemo, useState } from "react";''')
replace_once("components/hcm/employee-directory.tsx",'''  const selected = employees.find((user) => user.id === selectedId) ?? employees[0];
  if (!currentUser || !selected) return null;''','''  const selected = employees.find((user) => user.id === selectedId) ?? employees[0];
  useEffect(()=>{if(!selected)return;setEditPhone(selected.phone??"");setEditTitle(selected.title);setEditMessage("");},[selected?.id,selected?.phone,selected?.title]);
  if (!currentUser || !selected) return null;''')
replace_once("components/hcm/employee-directory.tsx",'''const result=await firebase.updateUserAccess(selected.id,{...(editTitle.trim()?{title:editTitle.trim()}:{}),phone:editPhone.trim()});''','''const result=await firebase.updateUserAccess(selected.id,{title:editTitle.trim()||selected.title,phone:editPhone.trim()});''')

# 4. Approval screen exposes exact SKU mix before an Administrator approves the one shared order.
replace_once("components/pages/work-v2.tsx",'''import { appendAudit } from "../../lib/hcm-engine";''','''import { appendAudit } from "../../lib/hcm-engine";
import { orderLinesFor } from "../../lib/order-lines";''')
replace_once("components/pages/work-v2.tsx",'''return order?`${order.cases} cases · ${formatMoney(order.amount)} · ${account?.locationName??account?.name??"Linked account"}`:approval.detail;''','''return order?`${order.cases} cases across ${orderLinesFor(order).length} SKU${orderLinesFor(order).length===1?"":"s"} · ${formatMoney(order.amount)} · ${account?.locationName??account?.name??"Linked account"}`:approval.detail;''')
replace_once("components/pages/work-v2.tsx",'''{reviewOrder&&<div className="record-review__section"><h3>Order record</h3><div className="record-review__facts"><div><span>Customer</span><strong>{reviewAccount?.name??"Linked account"}</strong></div><div><span>Location</span><strong>{reviewAccount?.locationName??reviewAccount?.location??"—"}</strong></div><div><span>Quantity</span><strong>{reviewOrder.cases} cases</strong></div><div><span>Price / case</span><strong>{formatMoney(reviewOrder.pricePerCase)}</strong></div><div><span>Total</span><strong>{formatMoney(reviewOrder.amount)}</strong></div><div><span>Status</span><strong>{reviewOrder.status}</strong></div></div></div>}''','''{reviewOrder&&<div className="record-review__section"><h3>Order record</h3><div className="record-review__facts"><div><span>Customer</span><strong>{reviewAccount?.name??"Linked account"}</strong></div><div><span>Location</span><strong>{reviewAccount?.locationName??reviewAccount?.location??"—"}</strong></div><div><span>Quantity</span><strong>{reviewOrder.cases} total cases</strong></div><div><span>Total</span><strong>{formatMoney(reviewOrder.amount)}</strong></div><div><span>Status</span><strong>{reviewOrder.status}</strong></div><div><span>Approval rule</span><strong>One Administrator decision</strong></div></div><div className="company-request-list">{orderLinesFor(reviewOrder).map((line)=><article key={line.id}><span><Boxes size={16}/></span><div><strong>{line.cases} cases · {line.product}</strong><p>{formatMoney(line.pricePerCase)} / case · {formatMoney(line.amount)}</p></div></article>)}</div></div>}''')
replace_once("components/pages/work-v2.tsx",'''<p>{approval.type} · {approval.requestedBy}{card?.status==="Returned"&&lastReturnReason(card.id)?` · ${lastReturnReason(card.id)}`:""}</p>''','''<p>{approval.type} · {approval.requestedBy}{approval.decidedBy?` · decided by ${data.users.find((user)=>user.id===approval.decidedBy)?.name??"Administrator"}`:""}{approval.returnReason?` · ${approval.returnReason}`:""}{card?.status==="Returned"&&lastReturnReason(card.id)?` · ${lastReturnReason(card.id)}`:""}</p>''')

# 5. Returned orders surface the correction reason instead of making the user hunt for it.
replace_once("components/pages/orders-v3.tsx",''' const selected=scope.orders.find((o)=>o.id===selectedId)??orders[0];const selectedLines=selected?orderLinesFor(selected):[];''',''' const selected=scope.orders.find((o)=>o.id===selectedId)??orders[0];const selectedLines=selected?orderLinesFor(selected):[];const selectedApproval=selected?scope.approvals.find((approval)=>approval.recordId===selected.id&&["Order","Low stock sale"].includes(approval.type)):undefined;''')
replace_once("components/pages/orders-v3.tsx",'''<p>The original record remains in history. Copy it to submit a corrected replacement.</p>''','''<p>{selectedApproval?.returnReason?`Correction requested: ${selectedApproval.returnReason}`:"The original record remains in history. Copy it to submit a corrected replacement."}</p>''')

# 6. Invoice view uses exact SKU descriptions/quantities and blocks accidental Net terms until credit is approved.
replace_once("components/commerce/order-cash-panel-v2.tsx",'''import { useWorkspace } from "../../lib/workspace-context";''','''import { useWorkspace } from "../../lib/workspace-context";
import { orderLinesFor } from "../../lib/order-lines";''')
replace_once("components/commerce/order-cash-panel-v2.tsx",'''  const setTerms = (terms: InvoiceTerms) => {
    if (!selected) return;''','''  const setTerms = (terms: InvoiceTerms) => {
    if (!selected) return;
    if (["Net 7","Net 15","Net 30"].includes(terms) && selectedCustomer?.creditStatus !== "Net 30 Approved") { window.alert("Net terms require an approved customer credit status first. COD remains the default."); return; }''')
replace_once("components/commerce/order-cash-panel-v2.tsx",'''          <div className="dispatch-record-pair"><article><small>Customer</small><strong>{selectedCustomer?.name ?? "Customer"}</strong><p>{selectedCustomer?.accountType}</p></article><article><small>Location</small><strong>{selectedLocation ? locationLabel(selectedLocation) : "Location"}</strong><p>{selectedLocation?.streetAddress || selectedLocation?.location}</p></article></div>''','''          <div className="dispatch-record-pair"><article><small>Customer</small><strong>{selectedCustomer?.name ?? "Customer"}</strong><p>{selectedCustomer?.accountType}</p></article><article><small>Location</small><strong>{selectedLocation ? locationLabel(selectedLocation) : "Location"}</strong><p>{selectedLocation?.streetAddress || selectedLocation?.location}</p></article></div>
          {selectedOrder&&<div className="company-request-list">{orderLinesFor(selectedOrder).map((line)=><article key={line.id}><span><ReceiptText size={17}/></span><div><strong>{line.product}</strong><p>{line.cases} cases × {formatMoney(line.pricePerCase)} = {formatMoney(line.amount)}</p></div></article>)}</div>}''')
replace_once("components/commerce/order-cash-panel-v2.tsx",'''<option>Net 7</option><option>Net 15</option><option>Net 30</option>''','''<option disabled={selectedCustomer?.creditStatus!=="Net 30 Approved"}>Net 7</option><option disabled={selectedCustomer?.creditStatus!=="Net 30 Approved"}>Net 15</option><option disabled={selectedCustomer?.creditStatus!=="Net 30 Approved"}>Net 30</option>''')

# 7. Add regression coverage for exact SKU aliasing and COD/Net credit guard assumptions.
with (ROOT/"tests/platform-workflows-v3.test.ts").open("a") as f:
    f.write('''\n\ntest("legacy shorthand resolves to canonical SKU lines",()=>{assert.equal(orderCasesForProduct(multi,"0.25L (8.4oz) Golden Eagle Energy Drink (24pack)"),12);assert.equal(orderCasesForProduct(multi,"Original"),12)});\n''')

print("PASS: platform refinements v5 applied")
