"use client";

import { AlertTriangle, ArrowLeft, BadgeDollarSign, Building2, CalendarPlus, ChevronLeft, ChevronRight, Mail, MapPin, Phone, Plus, Search, Store, UserRound } from "lucide-react";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { canCreateAccount, isCustomer } from "../../lib/access";
import { ACCOUNT_PRICING_TIERS } from "../../lib/account-health";
import { evaluateSalesRepAccountBonuses, SALES_REP_ACCOUNT_BONUS_RULE } from "../../lib/bonus-engine";
import { useCrm } from "../../lib/crm-context";
import { findAccountDuplicate } from "../../lib/duplicate-engine";
import { evaluatePartnerPricing, PARTNER_PRICING_RULE } from "../../lib/pricing-engine";
import type { AccountStage, PremiseType, PricingTier } from "../../lib/types";
import { useWorkspace } from "../../lib/workspace-context";
import { RecordHistory } from "../audit/record-history";
import { CrmDepthPanel } from "../crm/crm-depth-panel";
import { Avatar, Button, Field, Modal, PageHeader, Section, StatusPill, formatDate, formatMoney } from "../ui";

const stages:Array<"All"|AccountStage>=["All","Prospect","Qualified","Sampled","Opening order","Placed","Reordered","At risk"];
const stageTone=(stage:AccountStage)=>stage==="Reordered"||stage==="Placed"?"success" as const:stage==="At risk"?"danger" as const:stage==="Opening order"||stage==="Sampled"?"gold" as const:"info" as const;
const bonusTone=(status:string)=>status==="Earned"?"success" as const:status==="Window expired"||status==="Not qualified"?"danger" as const:status==="Awaiting payment"?"warning" as const:"info" as const;
const pricingTone=(status:string)=>status==="Partner pricing"||status==="Intro partner pricing"?"success" as const:status==="Standard pricing"?"warning" as const:"info" as const;
const blankForm={name:"",location:"Phoenix, AZ",streetAddress:"",channel:"Independent retail",contactName:"",contactRole:"Owner / buyer",phone:"",email:""};
const pageSize=50;

type CommercialForm={premiseType:PremiseType;businessType:string;categoryReviewDate:string;pricingTier?:PricingTier};

export function AccountsPage(){
  const {data,scope,currentUser,createAccount,navigate,updateAccountCommercial,transferAccountResponsibility}=useWorkspace();
  const {recordResponsibility}=useCrm();
  const focusId=typeof window!=="undefined"?window.sessionStorage.getItem("momentum-focus-record"):null;
  const focusedAccountId=focusId&&scope.accounts.some((account)=>account.id===focusId)?focusId:null;
  const initialId=focusedAccountId??scope.accounts[0]?.id??"";
  const [tab,setTab]=useState<"accounts"|"pricing"|"incentives">("accounts");
  const [query,setQuery]=useState("");
  const [stage,setStage]=useState<(typeof stages)[number]>("All");
  const [selectedId,setSelectedId]=useState(initialId);
  const [accountPageId,setAccountPageId]=useState<string|null>(focusedAccountId);
  const [listPage,setListPage]=useState(1);
  const [createOpen,setCreateOpen]=useState(false);
  const [manageOpen,setManageOpen]=useState(false);
  const [duplicateWarning,setDuplicateWarning]=useState<string|null>(null);
  const [form,setForm]=useState(blankForm);
  const [commercialForm,setCommercialForm]=useState<CommercialForm>({premiseType:"Unclassified",businessType:"",categoryReviewDate:""});
  const [handoffTo,setHandoffTo]=useState("");
  const [handoffReason,setHandoffReason]=useState("");

  useEffect(()=>{if(focusId)window.sessionStorage.removeItem("momentum-focus-record")},[focusId]);
  useEffect(()=>setListPage(1),[query,stage]);

  const filtered=useMemo(()=>{const normalized=query.trim().toLowerCase();return scope.accounts.filter((account)=>{const matchesStage=stage==="All"||account.stage===stage;const matchesQuery=!normalized||[account.name,account.locationName,account.location,account.streetAddress,account.channel,account.businessType,account.contactName,account.phone,account.email].join(" ").toLowerCase().includes(normalized);return matchesStage&&matchesQuery})},[query,scope.accounts,stage]);
  const totalPages=Math.max(1,Math.ceil(filtered.length/pageSize));
  const visibleAccounts=filtered.slice((Math.min(listPage,totalPages)-1)*pageSize,Math.min(listPage,totalPages)*pageSize);
  const selected=scope.accounts.find((account)=>account.id===(accountPageId??selectedId))??filtered[0];
  const responsible=data.users.find((user)=>user.id===selected?.ownerId);
  const accountActivities=scope.activities.filter((activity)=>activity.accountId===selected?.id);
  const accountOrders=scope.orders.filter((order)=>order.accountId===selected?.id).sort((a,b)=>b.placedAt.localeCompare(a.placedAt));
  const accountPlacements=scope.placements.filter((placement)=>placement.accountId===selected?.id);
  const selectedPricing=selected?evaluatePartnerPricing(data,selected.id):null;
  const scopeAccountIds=useMemo(()=>new Set(scope.accounts.map((account)=>account.id)),[scope.accounts]);
  const bonusSignals=useMemo(()=>evaluateSalesRepAccountBonuses(data).filter((signal)=>scopeAccountIds.has(signal.accountId)),[data,scopeAccountIds]);
  const pricingRows=useMemo(()=>scope.accounts.map((account)=>({account,pricing:evaluatePartnerPricing(data,account.id)})),[data,scope.accounts]);
  const earnedBonus=bonusSignals.filter((signal)=>signal.status==="Earned").reduce((sum,signal)=>sum+signal.amount,0);
  const paidCases=accountOrders.filter((order)=>order.paymentStatus==="Paid").reduce((sum,order)=>sum+order.cases,0);
  const openOrderValue=accountOrders.filter((order)=>order.paymentStatus!=="Paid").reduce((sum,order)=>sum+order.amount,0);
  const canEditCommercial=Boolean(currentUser&&["Administrator","Sales Manager","Sales Representative"].includes(currentUser.role));
  const canTransfer=Boolean(currentUser&&["Administrator","Sales Manager"].includes(currentUser.role));
  const salesUsers=data.users.filter((user)=>["Sales Representative","Sales Manager"].includes(user.role));

  const submit=(event:FormEvent)=>{event.preventDefault();const duplicate=findAccountDuplicate(data.accounts,form);if(duplicate){setDuplicateWarning(`${duplicate.reason} Existing record: ${duplicate.account.locationName??duplicate.account.name} (${duplicate.account.location}). Open and edit that record instead.`);return}const id=createAccount(form);if(!id)return;setSelectedId(id);setAccountPageId(id);setTab("accounts");setCreateOpen(false);setDuplicateWarning(null);setForm(blankForm)};
  const openAccountPage=(accountId:string)=>{setSelectedId(accountId);setAccountPageId(accountId)};
  const changeTab=(next:"accounts"|"pricing"|"incentives")=>{setTab(next);if(next!=="accounts")setAccountPageId(null)};
  const openLinkedPage=(page:"dispatch"|"orders",intent?:"new-order")=>{if(selected)window.sessionStorage.setItem("momentum-focus-record",selected.id);if(intent)window.sessionStorage.setItem("momentum-order-intent",intent);navigate(page)};
  const openManage=()=>{if(!selected)return;setCommercialForm({premiseType:selected.premiseType??"Unclassified",businessType:selected.businessType??selected.channel,categoryReviewDate:selected.categoryReviewDate??"",pricingTier:selected.pricingTier});setHandoffTo(selected.ownerId);setHandoffReason("");setManageOpen(true)};
  const saveCommercial=(event:FormEvent)=>{event.preventDefault();if(!selected)return;updateAccountCommercial(selected.id,{premiseType:commercialForm.premiseType,businessType:commercialForm.businessType.trim()||selected.channel,categoryReviewDate:commercialForm.categoryReviewDate||undefined,pricingTier:commercialForm.pricingTier});setManageOpen(false)};
  const transfer=()=>{if(!selected||!handoffTo||handoffTo===selected.ownerId||!handoffReason.trim())return;const priorOwner=selected.ownerId;if(!transferAccountResponsibility(selected.id,handoffTo,handoffReason.trim()))return;recordResponsibility({locationId:selected.id,fromUserId:priorOwner,toUserId:handoffTo,reason:handoffReason.trim()});setHandoffReason("")};

  if(isCustomer(currentUser))return <div className="page page--accounts page--customer-account"><PageHeader title="My account" actions={<Button variant="gold" icon={<Plus size={17}/>} onClick={()=>openLinkedPage("orders","new-order")}>Place order</Button>}/>{selected?(()=>{const pricing=evaluatePartnerPricing(data,selected.id);return <div className="customer-account-layout"><section className="customer-account-card"><header><span><Building2 size={25}/></span><div><StatusPill tone={pricingTone(pricing.status)}>{pricing.status}</StatusPill><h2>{selected.name}</h2><p><MapPin size={14}/> {selected.location} · {selected.channel}</p></div></header><div className="customer-account-card__metrics"><div><span>Orders</span><strong>{accountOrders.length}</strong></div><div><span>Paid cases</span><strong>{paidCases}</strong></div><div><span>Current price</span><strong>{selected.pricingTier?formatMoney(ACCOUNT_PRICING_TIERS[selected.pricingTier].pricePerCase):pricing.currentPricePerCase?formatMoney(pricing.currentPricePerCase):"Standard"}</strong></div></div></section><section className="customer-contact-card"><h3>Pricing</h3><p>{selected.pricingTier?`Tier ${selected.pricingTier} · ${formatMoney(ACCOUNT_PRICING_TIERS[selected.pricingTier].pricePerCase)}/case`:pricing.reason}</p><h3>Contact</h3><div><span><UserRound size={18}/></span><p><strong>{selected.contactName||"Contact not yet recorded"}</strong><small>{selected.contactRole}</small></p></div>{selected.phone&&<a href={`tel:${selected.phone}`}><Phone size={16}/> {selected.phone}</a>}{selected.email&&<a href={`mailto:${selected.email}`}><Mail size={16}/> {selected.email}</a>}</section></div>})():<div className="list-empty">No account is linked to this customer login.</div>}</div>;

  return <div className="page page--accounts">
    {tab==="accounts"&&accountPageId&&selected?<>
      <PageHeader title={selected.name} actions={<div className="account-detail__actions"><Button variant="ghost" icon={<ArrowLeft size={16}/>} onClick={()=>setAccountPageId(null)}>Back to accounts</Button>{canEditCommercial&&<Button variant="secondary" onClick={openManage}>Account details</Button>}<Button icon={<CalendarPlus size={15}/>} onClick={()=>openLinkedPage("dispatch")}>Schedule</Button><Button variant="gold" icon={<Plus size={15}/>} onClick={()=>openLinkedPage("orders","new-order")}>Draft order</Button></div>}/>
      <div className="account-profile-page">
        <section className="account-profile-page__hero"><div className="account-profile-page__identity"><span className="account-detail__logo"><Building2 size={24}/></span><div><StatusPill tone={stageTone(selected.stage)}>{selected.stage}</StatusPill><h2>{selected.locationName??selected.name}</h2><p><MapPin size={14}/> {selected.streetAddress?`${selected.streetAddress}, `:""}{selected.location}</p></div></div><div className="account-profile-page__owner"><span>Responsible</span>{responsible?<div><Avatar initials={responsible.initials} color={responsible.accent} size="sm"/><strong>{responsible.name}</strong></div>:<strong>Unassigned</strong>}</div></section>
        <div className="account-profile-page__metrics"><div><span>Paid cases</span><strong>{paidCases}</strong><small>Cleared orders only</small></div><div><span>Orders</span><strong>{accountOrders.length}</strong><small>{formatMoney(openOrderValue)} still open</small></div><div><span>Reorders</span><strong>{selected.reorderCount}</strong><small>Recorded account history</small></div><div><span>Placement</span><strong>{accountPlacements.length?"Recorded":"None"}</strong><small>{accountPlacements.length} placement record{accountPlacements.length===1?"":"s"}</small></div><div><span>Pricing</span><strong>{selected.pricingTier?`Tier ${selected.pricingTier}`:selectedPricing?.currentPricePerCase?formatMoney(selectedPricing.currentPricePerCase):"Not assigned"}</strong><small>{selected.pricingTier?`${formatMoney(ACCOUNT_PRICING_TIERS[selected.pricingTier].pricePerCase)}/case`:selectedPricing?.status??"Not started"}</small></div></div>
        <div className="account-profile-page__grid">
          <Section title="Next action"><button className="next-action-card next-action-card--button" onClick={()=>openLinkedPage("dispatch")}><span>{formatDate(selected.nextActionDate,{month:"short",day:"numeric"})}</span><div><strong>{selected.nextAction}</strong><p>Responsible: {responsible?.name??"Unassigned"}</p></div><ChevronRight size={17}/></button></Section>
          <Section title="Primary contact"><div className="account-profile-contact"><div className="contact-card"><span><UserRound size={17}/></span><div><strong>{selected.contactName||"Contact not yet recorded"}</strong><p>{selected.contactRole}</p></div></div>{selected.phone&&<a href={`tel:${selected.phone}`}><Phone size={15}/> {selected.phone}</a>}{selected.email&&<a href={`mailto:${selected.email}`}><Mail size={15}/> {selected.email}</a>}</div></Section>
          <Section title="Account details"><dl className="account-profile-facts"><div><dt>Stage</dt><dd><StatusPill tone={stageTone(selected.stage)}>{selected.stage}</StatusPill></dd></div><div><dt>Channel</dt><dd>{selected.channel}</dd></div><div><dt>Premise</dt><dd>{selected.premiseType??"Unclassified"}</dd></div><div><dt>Business type</dt><dd>{selected.businessType??selected.channel}</dd></div><div><dt>Pricing tier</dt><dd>{selected.pricingTier?`Tier ${selected.pricingTier} · ${formatMoney(ACCOUNT_PRICING_TIERS[selected.pricingTier].pricePerCase)}/case`:"Not assigned"}</dd></div><div><dt>Category review</dt><dd>{selected.categoryReviewDate?formatDate(selected.categoryReviewDate,{month:"short",day:"numeric",year:"numeric"}):"Not scheduled"}</dd></div></dl></Section>
          <Section title="Retail placement"><div className="account-profile-list">{accountPlacements.map((placement)=><div key={placement.id}><strong>{placement.product}</strong><span>{placement.location} · {placement.status} · {placement.observedStock} observed units · {placement.facings} facings</span></div>)}{accountPlacements.length===0&&<div className="review-empty"><Store size={21}/><p>No placement record is linked to this account.</p></div>}</div></Section>
        </div>
        <CrmDepthPanel accountId={selected.id}/>
        <Section title="Order history"><div className="account-profile-orders">{accountOrders.slice(0,8).map((order)=><button key={order.id} onClick={()=>{window.sessionStorage.setItem("momentum-focus-record",order.id);navigate("orders")}}><span><strong>{order.number}</strong><small>{order.product??"Golden Eagle"}</small></span><span>{formatDate(order.placedAt,{month:"short",day:"numeric",year:"numeric"})}</span><span>{order.cases} cases</span><span>{formatMoney(order.amount)}</span><StatusPill tone={order.paymentStatus==="Paid"?"success":order.status==="Draft"?"warning":"info"}>{order.paymentStatus==="Paid"?"Paid":order.status}</StatusPill><ChevronRight size={16}/></button>)}{accountOrders.length===0&&<div className="review-empty"><Store size={21}/><p>No orders are linked to this account yet.</p></div>}</div></Section>
        <div className="account-profile-page__grid account-profile-page__grid--history"><Section title="Activity"><div className="mini-timeline">{accountActivities.slice(0,8).map((activity)=><article key={activity.id}><i/><div><strong>{activity.title}</strong><p>{activity.detail}</p><small>{formatDate(activity.at,{month:"short",day:"numeric",hour:"numeric",minute:"2-digit"})}</small></div></article>)}</div></Section><Section title="Internal note"><div className="account-profile-note"><p>{selected.notes||"No internal note recorded."}</p></div></Section></div>
        <RecordHistory accountId={selected.id}/>
      </div>
    </>:<>
      <PageHeader title="Sales & accounts" actions={canCreateAccount(currentUser)?<Button variant="gold" icon={<Plus size={17}/>} onClick={()=>{setDuplicateWarning(null);setCreateOpen(true)}}>New account</Button>:undefined}/>
      <div className="company-tabs"><button className={tab==="accounts"?"is-active":""} onClick={()=>changeTab("accounts")}>Accounts</button><button className={tab==="pricing"?"is-active":""} onClick={()=>changeTab("pricing")}>Pricing</button><button className={tab==="incentives"?"is-active":""} onClick={()=>changeTab("incentives")}>Sales incentives <i>{bonusSignals.filter((s)=>s.status==="Earned").length}</i></button></div>
      {tab==="accounts"&&<><div className="account-toolbar"><label className="table-search"><Search size={17}/><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Search name, buyer, address, phone, email…"/></label><div className="stage-filters" role="group" aria-label="Filter by stage">{stages.map((item)=><button key={item} className={stage===item?"is-active":""} onClick={()=>setStage(item)}>{item}</button>)}</div></div><section className="account-list-panel account-list-panel--full"><div className="list-summary"><span><strong>{filtered.length}</strong> accounts</span><small>{filtered.length>pageSize?`Showing ${((listPage-1)*pageSize)+1}-${Math.min(listPage*pageSize,filtered.length)}`:"Select an account to open it"}</small></div><div className="account-table account-table--head"><span>Account</span><span>Stage</span><span>Responsible</span><span>Next action</span><span/></div><div className="account-table-body">{visibleAccounts.map((account)=>{const accountResponsible=data.users.find((user)=>user.id===account.ownerId);return <button className="account-table" key={account.id} onClick={()=>openAccountPage(account.id)}><span className="account-name-cell"><i><Store size={17}/></i><span><strong>{account.name}</strong><small>{account.streetAddress?`${account.streetAddress} · `:""}{account.location} · {account.channel}</small></span></span><span><StatusPill tone={stageTone(account.stage)}>{account.stage}</StatusPill></span><span className="account-owner-cell">{accountResponsible&&<><Avatar initials={accountResponsible.initials} color={accountResponsible.accent} size="sm"/><span>{accountResponsible.firstName}</span></>}</span><span className="account-action-cell"><strong>{account.nextAction}</strong><small>{formatDate(account.nextActionDate,{month:"short",day:"numeric"})}</small></span><ChevronRight size={17}/></button>})}{filtered.length===0&&<div className="list-empty">No accounts match these filters.</div>}</div>{totalPages>1&&<div className="account-pagination"><Button size="sm" variant="ghost" icon={<ChevronLeft size={15}/>} disabled={listPage<=1} onClick={()=>setListPage((page)=>Math.max(1,page-1))}>Previous</Button><span>Page {Math.min(listPage,totalPages)} of {totalPages}</span><Button size="sm" variant="ghost" disabled={listPage>=totalPages} onClick={()=>setListPage((page)=>Math.min(totalPages,page+1))}>Next <ChevronRight size={15}/></Button></div>}</section></>}
      {tab==="pricing"&&<><div className="company-rule-facts"><div><span>Tier A</span><strong>{formatMoney(ACCOUNT_PRICING_TIERS.A.pricePerCase)}/case</strong></div><div><span>Tier B</span><strong>{formatMoney(ACCOUNT_PRICING_TIERS.B.pricePerCase)}/case</strong></div><div><span>Tier C</span><strong>{formatMoney(ACCOUNT_PRICING_TIERS.C.pricePerCase)}/case</strong></div><div><span>Category review</span><strong>Every 3 months</strong></div></div><Section title="Account pricing"><div className="bonus-ledger">{pricingRows.map(({account,pricing})=><article key={account.id}><div className="bonus-ledger__head"><div><small>{account.location}</small><strong>{account.name}</strong><p>{account.pricingTier?`Tier ${account.pricingTier} · ${formatMoney(ACCOUNT_PRICING_TIERS[account.pricingTier].pricePerCase)}/case`:"Pricing tier not assigned"}</p></div><StatusPill tone={account.pricingTier==="A"?"success":account.pricingTier==="B"?"gold":account.pricingTier==="C"?"warning":"neutral"}>{account.pricingTier?`Tier ${account.pricingTier}`:pricing.status}</StatusPill></div><div className="bonus-ledger__foot"><span>{pricing.countedCases} paid cases in tracked period</span><span>{account.categoryReviewDate?`Review ${formatDate(account.categoryReviewDate,{month:"short",day:"numeric",year:"numeric"})}`:"Review date not set"}</span></div></article>)}</div></Section></>}
      {tab==="incentives"&&<><div className="company-rule-facts"><div><span>Opening threshold</span><strong>{SALES_REP_ACCOUNT_BONUS_RULE.openingOrderCases} cases</strong><small>{formatMoney(SALES_REP_ACCOUNT_BONUS_RULE.openingBonusAmount)} after payment clears</small></div><div><span>Sustained threshold</span><strong>{SALES_REP_ACCOUNT_BONUS_RULE.sustainedAccountCases} paid cases</strong><small>{formatMoney(SALES_REP_ACCOUNT_BONUS_RULE.sustainedBonusAmount)}</small></div><div><span>Window</span><strong>{SALES_REP_ACCOUNT_BONUS_RULE.windowDays} days</strong></div><div><span>Earned in scope</span><strong>{formatMoney(earnedBonus)}</strong></div></div><Section title="Account milestone ledger"><div className="bonus-ledger">{bonusSignals.map((signal)=>{const account=data.accounts.find((item)=>item.id===signal.accountId);const rep=data.users.find((item)=>item.id===signal.repId);const progress=Math.min(100,Math.round((signal.observedCases/Math.max(1,signal.thresholdCases))*100));return <article key={signal.id}><div className="bonus-ledger__head"><div><small>{signal.milestone}</small><strong>{account?.name}</strong><p>{rep?.name} · {signal.observedCases}/{signal.thresholdCases} cases</p></div><StatusPill tone={bonusTone(signal.status)}>{signal.status}</StatusPill></div><div className="bonus-progress"><i style={{width:`${progress}%`}}/></div><div className="bonus-ledger__foot"><span>Amount {formatMoney(signal.amount)}</span><span>{signal.windowEnd?`Through ${formatDate(signal.windowEnd,{month:"short",day:"numeric",year:"numeric"})}`:"Not started"}</span></div></article>})}</div></Section></>}
    </>}

    <Modal open={createOpen} title="Create account" onClose={()=>{setCreateOpen(false);setDuplicateWarning(null)}} footer={<><Button variant="ghost" onClick={()=>{setCreateOpen(false);setDuplicateWarning(null)}}>Cancel</Button><Button type="submit" form="new-account-form">Create account</Button></>}><form id="new-account-form" className="form-grid" onSubmit={submit}>{duplicateWarning&&<div className="form-callout field--full"><AlertTriangle size={17}/><p>{duplicateWarning}</p></div>}<Field label="Business name"><input required value={form.name} onChange={(event)=>{setDuplicateWarning(null);setForm({...form,name:event.target.value})}} placeholder="Example Market"/></Field><Field label="City / market"><input required value={form.location} onChange={(event)=>{setDuplicateWarning(null);setForm({...form,location:event.target.value})}}/></Field><Field label="Street address" className="field--full"><input value={form.streetAddress} onChange={(event)=>{setDuplicateWarning(null);setForm({...form,streetAddress:event.target.value})}} placeholder="1234 W Example Ave, Suite 100"/></Field><Field label="Channel"><select value={form.channel} onChange={(event)=>setForm({...form,channel:event.target.value})}><option>Independent retail</option><option>Convenience store</option><option>Restaurant / nightlife</option><option>Gym / fitness</option><option>Vending</option><option>Distributor</option></select></Field><Field label="Primary contact"><input value={form.contactName} onChange={(event)=>setForm({...form,contactName:event.target.value})}/></Field><Field label="Contact role"><input value={form.contactRole} onChange={(event)=>setForm({...form,contactRole:event.target.value})}/></Field><Field label="Phone"><input value={form.phone} onChange={(event)=>{setDuplicateWarning(null);setForm({...form,phone:event.target.value})}}/></Field><Field label="Email"><input type="email" value={form.email} onChange={(event)=>{setDuplicateWarning(null);setForm({...form,email:event.target.value})}}/></Field></form></Modal>

    <Modal open={manageOpen} title="Account details" onClose={()=>setManageOpen(false)} footer={<><Button variant="ghost" onClick={()=>setManageOpen(false)}>Cancel</Button><Button type="submit" form="account-commercial-form">Save changes</Button></>}><form id="account-commercial-form" className="form-grid" onSubmit={saveCommercial}><Field label="Pricing tier"><select value={commercialForm.pricingTier??""} onChange={(event)=>setCommercialForm({...commercialForm,pricingTier:event.target.value?event.target.value as PricingTier:undefined})}><option value="">Not assigned</option>{(["A","B","C"] as PricingTier[]).map((tier)=><option key={tier} value={tier}>Tier {tier} · {formatMoney(ACCOUNT_PRICING_TIERS[tier].pricePerCase)}/case</option>)}</select></Field><Field label="Premise"><select value={commercialForm.premiseType} onChange={(event)=>setCommercialForm({...commercialForm,premiseType:event.target.value as PremiseType})}><option>Unclassified</option><option>On-premise</option><option>Off-premise</option><option>Hybrid</option></select></Field><Field label="Business type"><input value={commercialForm.businessType} onChange={(event)=>setCommercialForm({...commercialForm,businessType:event.target.value})} placeholder="Restaurant, bar, food truck, convenience store…"/></Field><Field label="Category review date"><input type="date" value={commercialForm.categoryReviewDate} onChange={(event)=>setCommercialForm({...commercialForm,categoryReviewDate:event.target.value})}/></Field>{canTransfer&&selected&&<div className="field--full account-handoff-form"><strong>Responsibility handoff</strong><div className="form-grid"><Field label="New responsible rep"><select value={handoffTo} onChange={(event)=>setHandoffTo(event.target.value)}>{salesUsers.map((user)=><option key={user.id} value={user.id}>{user.name}</option>)}</select></Field><Field label="Reason"><input value={handoffReason} onChange={(event)=>setHandoffReason(event.target.value)}/></Field></div><Button type="button" variant="secondary" size="sm" disabled={!handoffReason.trim()||handoffTo===selected.ownerId} onClick={transfer}>Transfer responsibility</Button></div>}</form></Modal>
  </div>
}
