"use client";
import { AlertCircle, Box, Building2, CheckCircle2, ChevronRight, CircleDollarSign, Copy, FileText, Mail, MapPin, PackageSearch, Pencil, Plus, Store, Trash2, Truck, UserRound, XCircle } from "lucide-react";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { canAdvanceFulfillment, canCreateOrder, isCustomer } from "../../lib/access";
import { activeReservedForOrder, orderCanAdvanceInventory, orderDeliveryQuantity, orderOutboundQuantity, productInventoryStatus } from "../../lib/inventory-ledger";
import { useInventoryLedger } from "../../lib/inventory-ledger-context";
import { orderLinesFor } from "../../lib/order-lines";
import { GOLDEN_EAGLE_SKUS } from "../../lib/product-catalog";
import { useFirebaseSessionOptional } from "../../lib/firebase-session-context";
import { momentumStorage } from "../../lib/persistence";
import { evaluatePartnerPricing } from "../../lib/pricing-engine";
import type { Order, OrderStatus } from "../../lib/types";
import { COMMERCIAL_KEY, useWorkspace } from "../../lib/workspace-context";
import { Button, Field, Modal, PageHeader, Section, StatusPill, formatMoney } from "../ui";

const lifecycle:OrderStatus[]=["Draft","Awaiting approval","Approved","Allocated","Out for delivery","Delivered","Paid"];
const fulfillmentNext:Partial<Record<OrderStatus,"Allocated"|"Out for delivery"|"Delivered">>={Approved:"Allocated",Allocated:"Out for delivery","Out for delivery":"Delivered"};
const tone=(status:OrderStatus)=>["Paid","Delivered"].includes(status)?"success" as const:status==="Cancelled"?"danger" as const:status==="Awaiting approval"?"warning" as const:status==="Draft"?"neutral" as const:"info" as const;
type DraftLine={id:string;product:string;cases:number};
const skuOptions=GOLDEN_EAGLE_SKUS.filter((sku)=>sku.active);
const newLine=(product=skuOptions[0]?.description??"Golden Eagle",cases=10):DraftLine=>({id:`draft-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,product,cases});
const addressFor=(account:{streetAddress?:string;city?:string;state?:string;postalCode?:string;location:string})=>[account.streetAddress,account.city||account.location,account.state,account.postalCode].filter(Boolean).join(", ");

export function OrdersPage(){
 const{data,scope,currentUser,createOrder,editOrder,cancelOrder,navigate}=useWorkspace();
 const{ledger,advanceOrderFulfillment,releaseOrderReservationsForEdit}=useInventoryLedger();
 const firebase=useFirebaseSessionOptional();
 const focusId=typeof window!=="undefined"?sessionStorage.getItem("momentum-focus-record"):null;
 const editFocusId=typeof window!=="undefined"?sessionStorage.getItem("momentum-edit-order"):null;
 const focused=scope.orders.find((o)=>o.id===focusId);const focusedAccount=scope.accounts.find((a)=>a.id===focusId);
 const[query,setQuery]=useState("");
 const[selectedId,setSelectedId]=useState(focused?.id??scope.orders[0]?.id??"");
 const[open,setOpen]=useState(false);
 const[editingId,setEditingId]=useState<string|null>(null);
 const[detailOpen,setDetailOpen]=useState(false);
 const[error,setError]=useState("");
 const[submitting,setSubmitting]=useState(false);
 const[accountId,setAccountId]=useState(focusedAccount?.id??scope.accounts[0]?.id??"");
 const[lines,setLines]=useState<DraftLine[]>([newLine()]);
 const customerMode=isCustomer(currentUser);const canFulfill=canAdvanceFulfillment(currentUser);

 const orders=useMemo(()=>{const q=query.trim().toLowerCase();return scope.orders.filter((o)=>{const a=scope.accounts.find((x)=>x.id===o.accountId);return!q||`${o.number} ${a?.name??""} ${orderLinesFor(o).map((l)=>l.product).join(" ")} ${o.status}`.toLowerCase().includes(q)})},[query,scope.orders,scope.accounts]);
 const selected=scope.orders.find((o)=>o.id===selectedId)??orders[0];
 const editingOrder=editingId?scope.orders.find((o)=>o.id===editingId):undefined;
 const selectedLines=selected?orderLinesFor(selected):[];
 const selectedApproval=selected?scope.approvals.find((approval)=>approval.recordId===selected.id&&["Order","Low stock sale"].includes(approval.type)):undefined;
 const currentIndex=selected?lifecycle.indexOf(selected.status):-1;const nextStatus=selected?fulfillmentNext[selected.status]??null:null;
 const selectedAccount=selected?scope.accounts.find((a)=>a.id===selected.accountId):undefined;
 const selectedCustomer=selectedAccount?.customerId?(data.customers??[]).find((c)=>c.id===selectedAccount.customerId):undefined;
 const placedBy=selected?data.users.find((u)=>u.id===selected.ownerId):undefined;const cancelledBy=selected?.cancelledBy?data.users.find((u)=>u.id===selected.cancelledBy):undefined;
 const reserved=selected?activeReservedForOrder(ledger,selected.id):0;const outbound=selected?orderOutboundQuantity(ledger,selected.id):0;const delivered=selected?orderDeliveryQuantity(ledger,selected.id):0;const inventoryReady=Boolean(selected&&nextStatus&&orderCanAdvanceInventory(ledger,selected,nextStatus));
 const pricing=accountId?evaluatePartnerPricing(data,accountId):null;
 const formPrice=editingOrder?.pricePerCase??pricing?.currentPricePerCase;
 const requestCases=lines.reduce((s,l)=>s+(Number.isInteger(l.cases)&&l.cases>0?l.cases:0),0);
 const canEdit=(order:Order|undefined)=>Boolean(order&&currentUser&&["Draft","Awaiting approval","Approved"].includes(order.status)&&(currentUser.role==="Administrator"||(order.ownerId===currentUser.id&&["Sales Representative","Sales Manager","Customer"].includes(currentUser.role))));

 const openDraft=(order?:Order)=>{setEditingId(null);setAccountId(order?.accountId??focusedAccount?.id??scope.accounts[0]?.id??"");setLines(order?orderLinesFor(order).map((l)=>newLine(l.product,l.cases)):[newLine()]);setError("");setOpen(true)};
 const openEditor=(order:Order)=>{if(!canEdit(order))return;setSelectedId(order.id);setEditingId(order.id);setAccountId(order.accountId);setLines(orderLinesFor(order).map((l)=>newLine(l.product,l.cases)));setError("");setDetailOpen(false);setOpen(true)};
 const closeForm=()=>{if(submitting)return;setOpen(false);setEditingId(null);setError("")};

 useEffect(()=>{if(!focusId&&!editFocusId)return;const handle=window.setTimeout(()=>{const targetId=editFocusId??focusId;const target=scope.orders.find((order)=>order.id===targetId);if(target){setSelectedId(target.id);if(editFocusId&&canEdit(target))openEditor(target);else setDetailOpen(true)}sessionStorage.removeItem("momentum-focus-record");sessionStorage.removeItem("momentum-edit-order")},0);return()=>window.clearTimeout(handle)},[focusId,editFocusId,scope.orders]);

 const submit=async(e:FormEvent)=>{
  e.preventDefault();if(submitting)return;
  if(firebase&&currentUser?.role!=="Customer"&&firebase.access?.accountState!=="Active"){setError(`Your Momentum access is ${firebase.access?.accountState??"not active"}. The order was not submitted.`);return}
  if(!formPrice){setError("Current order pricing must be configured before this order can be submitted.");return}
  if(!lines.length||lines.some((l)=>!Number.isInteger(l.cases)||l.cases<1)){setError("Every order line needs a whole-number case quantity of at least 1.");return}
  setSubmitting(true);setError("");
  const lineInput=lines.map((l)=>({...l,inventoryAvailableAtOrder:productInventoryStatus(ledger,data,l.product).available}));
  if(editingOrder){
    if(editingOrder.status==="Approved"&&!releaseOrderReservationsForEdit(editingOrder.id)){setSubmitting(false);setError("This approved order cannot be edited because inventory has already moved, the inventory period is locked, or the reservation could not be safely released.");return}
    const result=editOrder(editingOrder.id,{accountId:editingOrder.accountId,lines:lineInput});
    if(!result.ok){setSubmitting(false);setError(result.message??"Momentum could not save the order changes.");return}
    const confirmed=await momentumStorage.flushAndConfirm(COMMERCIAL_KEY);setSubmitting(false);setSelectedId(editingOrder.id);
    if(!confirmed.ok){setError(`Changes to ${editingOrder.number} are safely queued on this device but Momentum cloud has NOT confirmed them. Do not repeat the edit. ${confirmed.message??"Use the sync indicator and retry after access/connectivity is corrected."}`);return}
    setOpen(false);setEditingId(null);setError("");return;
  }
  const id=createOrder({accountId,lines:lineInput});
  if(!id){setSubmitting(false);setError("Momentum rejected this request. Review the account, pricing, quantities, and permissions. Nothing was silently submitted.");return}
  const confirmed=await momentumStorage.flushAndConfirm(COMMERCIAL_KEY);setSubmitting(false);setSelectedId(id);
  if(!confirmed.ok){setError(`Order ${id} is safely queued on this device but Momentum cloud has NOT confirmed it. Do not submit it again. ${confirmed.message??"Use the sync indicator and retry after access/connectivity is corrected."}`);return}
  setOpen(false);setError("");
 };
 const advance=()=>{if(!selected||!nextStatus)return;if(!advanceOrderFulfillment(selected.id,nextStatus)){setError("Inventory evidence is incomplete for the next fulfillment step. Open Inventory to finish reservations or custody records.");return}setError("")};
 const cancelSelected=()=>{if(!selected)return;const reason=window.prompt(`Why is ${selected.number} being cancelled? This reason will remain in order history.`)?.trim()??"";if(!reason)return;const result=cancelOrder(selected.id,reason);setError(result.ok?"":result.message??"Order cancellation failed.");if(result.ok)setDetailOpen(false)};

 return <div className="page page--orders">
 <PageHeader title={customerMode?"My orders":"Orders"} actions={canCreateOrder(currentUser)?<Button variant="gold" icon={<Plus size={17}/>} onClick={()=>openDraft()}>{customerMode?"Place order":"Create order"}</Button>:undefined}/>
 <div className="order-stats"><div><span><FileText size={18}/></span><div><small>Orders in scope</small><strong>{scope.orders.length}</strong></div></div><div><span><CircleDollarSign size={18}/></span><div><small>Open amount</small><strong>{formatMoney(scope.orders.filter(o=>o.paymentStatus!=="Paid"&&o.status!=="Cancelled").reduce((s,o)=>s+o.amount,0))}</strong></div></div><div><span><Truck size={18}/></span><div><small>Delivered cases</small><strong>{scope.orders.filter(o=>["Delivered","Paid"].includes(o.status)).reduce((s,o)=>s+o.cases,0)}</strong></div></div><div><span><PackageSearch size={18}/></span><div><small>Canonical SKUs</small><strong>{skuOptions.length}</strong></div></div></div>
 <div className="orders-layout"><Section className="orders-list" title="Order register" description="Click any order to open the complete customer, delivery, product, payment and history view."><label className="table-search order-search"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search order, account, SKU, or status…"/></label><div className="order-table order-table--head"><span>Order</span><span>Customer</span><span>Cases</span><span>Amount</span><span>Status</span><span/></div><div className="order-table-body">{orders.map(o=>{const a=scope.accounts.find(x=>x.id===o.accountId);return <button className={`order-table ${selected?.id===o.id?"is-selected":""}`} key={o.id} onClick={()=>{setSelectedId(o.id);setDetailOpen(true)}}><span><strong>{o.number}</strong><small>{orderLinesFor(o).length===1?orderLinesFor(o)[0].product:`${orderLinesFor(o).length} SKUs`}</small></span><span><strong>{a?.name}</strong><small>{a?.locationName??a?.location}</small></span><span>{o.cases}</span><span>{formatMoney(o.amount)}</span><span><StatusPill tone={tone(o.status)}>{o.status}</StatusPill></span><ChevronRight size={16}/></button>})}</div></Section>
 {selected&&<Section className="order-detail" title={selected.number} action={<StatusPill tone={tone(selected.status)}>{selected.status}</StatusPill>}><div className="order-detail__body"><div className="order-price-card"><div><span>Order total</span><strong>{formatMoney(selected.amount)}</strong><small>{selected.cases} total cases · {selectedLines.length} SKU{selectedLines.length===1?"":"s"}</small></div><span><FileText size={24}/></span></div><div className="order-detail-actions"><Button size="sm" onClick={()=>setDetailOpen(true)}>View full order</Button>{canEdit(selected)&&<Button size="sm" variant="secondary" icon={<Pencil size={14}/>} onClick={()=>openEditor(selected)}>{selected.status==="Draft"?"Edit and resubmit":"Edit order"}</Button>}{canCreateOrder(currentUser)&&selected.status!=="Cancelled"&&<Button size="sm" variant="secondary" icon={<Copy size={14}/>} onClick={()=>openDraft(selected)}>Copy / reorder</Button>}</div><div className="company-request-list">{selectedLines.map(l=><article key={l.id}><span><Box size={16}/></span><div><small>Order line</small><strong>{l.cases} cases · {l.product}</strong><p>{formatMoney(l.pricePerCase)} / case · {formatMoney(l.amount)}</p></div></article>)}</div>{selected.status!=="Cancelled"&&<div className="order-lifecycle">{lifecycle.map((s,i)=><div className={i<=currentIndex?"is-complete":""} key={s}><span>{i<currentIndex?<CheckCircle2 size={14}/>:i+1}</span><small>{s}</small></div>)}</div>}<dl className="order-facts"><div><dt>Reserved</dt><dd>{reserved}/{selected.cases}</dd></div><div><dt>Outbound custody</dt><dd>{outbound}/{selected.cases}</dd></div><div><dt>Delivered</dt><dd>{delivered}/{selected.cases}</dd></div><div><dt>Payment</dt><dd>{selected.paymentStatus}</dd></div></dl>
 {selected.status==="Cancelled"?<div className="order-approval-callout"><XCircle size={20}/><div><strong>Order cancelled</strong><p>{selected.cancellationReason}</p></div></div>:selected.status==="Awaiting approval"?<div className="order-approval-callout"><Store size={20}/><div><strong>One Administrator approval required</strong><p>Once either Administrator approves this order, that decision is authoritative for the shared order record.</p></div>{currentUser?.role==="Administrator"&&<Button size="sm" onClick={()=>navigate("work")}>Review</Button>}</div>:selected.status==="Draft"?<div className="order-approval-callout"><AlertCircle size={20}/><div><strong>Returned for edits</strong><p>{selectedApproval?.returnReason?`Correction requested: ${selectedApproval.returnReason}`:"Correct the same order and resubmit it for Administrator approval."}</p></div>{canEdit(selected)&&<Button size="sm" onClick={()=>openEditor(selected)}>Edit and resubmit</Button>}</div>:nextStatus&&canFulfill&&inventoryReady?<Button size="lg" onClick={advance}>Move to {nextStatus.toLowerCase()}</Button>:nextStatus&&canFulfill?<div className="order-approval-callout"><PackageSearch size={20}/><div><strong>Inventory evidence required</strong><p>Reserve the exact SKU mix and complete custody evidence before moving forward.</p></div><Button size="sm" variant="secondary" onClick={()=>navigate("inventory")}>Open inventory</Button></div>:null}{error&&<p className="form-error" role="alert">{error}</p>}</div></Section>}</div>
 {selected&&<Modal open={detailOpen} title={`${selected.number} · full order`} description="Customer, delivery, product, payment and order-control details." onClose={()=>setDetailOpen(false)} wide footer={<><Button variant="ghost" onClick={()=>setDetailOpen(false)}>Close</Button>{canEdit(selected)&&<Button variant="secondary" icon={<Pencil size={15}/>} onClick={()=>openEditor(selected)}>{selected.status==="Draft"?"Edit and resubmit":"Edit order"}</Button>}{currentUser?.role==="Administrator"&&["Draft","Awaiting approval","Approved"].includes(selected.status)&&<Button variant="secondary" icon={<XCircle size={15}/>} onClick={cancelSelected}>Cancel order</Button>}</>}><div className="order-full-detail"><div className="company-rule-facts"><div><span>Status</span><strong>{selected.status}</strong><small>{selected.paymentStatus}</small></div><div><span>Total</span><strong>{formatMoney(selected.amount)}</strong><small>{selected.cases} cases</small></div><div><span>Placed</span><strong>{selected.placedAt}</strong><small>{placedBy?.name??selected.ownerId}</small></div><div><span>Terms</span><strong>{selectedCustomer?.paymentTerms??"COD"}</strong><small>{selected.priceBasis}</small></div></div>
 <Section title="Company & delivery location"><div className="company-request-list"><article><span><Building2 size={17}/></span><div><small>Company</small><strong>{selectedCustomer?.name??selectedAccount?.name??"Unknown customer"}</strong><p>{selectedAccount?.locationName??selectedAccount?.name}</p></div></article><article><span><MapPin size={17}/></span><div><small>Delivery address</small><strong>{selectedAccount?addressFor(selectedAccount):"Address unavailable"}</strong><p>{selectedAccount?.notes||"No location note."}</p></div></article><article><span><UserRound size={17}/></span><div><small>Primary contact</small><strong>{selectedAccount?.contactName||"Not recorded"}{selectedAccount?.contactRole?` · ${selectedAccount.contactRole}`:""}</strong><p>{selectedAccount?.phone||"No phone"}{selectedAccount?.email?` · ${selectedAccount.email}`:""}</p></div></article>{selectedCustomer&&(selectedCustomer.accountsPayableContactName||selectedCustomer.billingContactName)&&<article><span><Mail size={17}/></span><div><small>Billing / A/P</small><strong>{selectedCustomer.accountsPayableContactName??selectedCustomer.billingContactName}</strong><p>{selectedCustomer.accountsPayablePhone??selectedCustomer.billingPhone??""}{(selectedCustomer.accountsPayableEmail??selectedCustomer.billingEmail)?` · ${selectedCustomer.accountsPayableEmail??selectedCustomer.billingEmail}`:""}</p></div></article>}</div></Section>
 <Section title="Products"><div className="company-request-list">{selectedLines.map(l=><article key={l.id}><span><Box size={16}/></span><div><strong>{l.product}</strong><p>{l.cases} cases · {formatMoney(l.pricePerCase)} / case · {formatMoney(l.amount)}</p></div></article>)}</div></Section>
 {selected.status==="Cancelled"&&<Section title="Cancellation"><div className="form-callout"><XCircle size={17}/><p><strong>{selected.cancellationReason}</strong><br/>{selected.cancelledAt?new Date(selected.cancelledAt).toLocaleString():""}{cancelledBy?` · ${cancelledBy.name}`:""}</p></div></Section>}</div></Modal>}
 <Modal open={open} title={editingOrder?`Edit ${editingOrder.number}`:"Create order request"} description={editingOrder?(editingOrder.status==="Approved"&&currentUser?.role==="Administrator"?"Update this approved order before fulfillment begins. The Administrator amendment remains approved.":"Update the same order record. The revised order will return to Administrator approval before fulfillment."):"Add as many Golden Eagle SKUs as the customer needs. There is no 10-case maximum. One Administrator approval covers the complete order."} onClose={closeForm} wide footer={<><Button variant="ghost" onClick={closeForm}>Cancel</Button><Button type="submit" form="order-v3-form" disabled={submitting}>{submitting?"Confirming with cloud…":editingOrder?(editingOrder.status==="Draft"?"Save and resubmit":"Save changes"):"Submit order"}</Button></>}><form id="order-v3-form" className="form-grid" onSubmit={submit}><Field label="Customer account" className="field--full"><select value={accountId} disabled={Boolean(editingOrder)} onChange={e=>setAccountId(e.target.value)}>{scope.accounts.map(a=><option key={a.id} value={a.id}>{a.name} · {a.locationName??a.location}</option>)}</select></Field>{editingOrder&&<div className="form-callout field--full"><Pencil size={17}/><p><strong>Editing the existing order.</strong><br/>Order number, creating rep, sales credit, and prior approval history stay attached to this record. Editing stops once fulfillment begins.</p></div>}{lines.map((line,index)=><div className="field--full form-grid" key={line.id}><Field label={`Product ${index+1}`}><select value={line.product} onChange={e=>setLines(rows=>rows.map(r=>r.id===line.id?{...r,product:e.target.value}:r))}>{skuOptions.map(s=><option value={s.description} key={s.id}>{s.description}</option>)}</select></Field><Field label="Cases"><input type="number" min="1" step="1" required value={line.cases} onChange={e=>setLines(rows=>rows.map(r=>r.id===line.id?{...r,cases:Number(e.target.value)}:r))}/></Field><div className="field--full"><small>{productInventoryStatus(ledger,data,line.product).available} currently available sellable cases</small>{lines.length>1&&<Button type="button" size="sm" variant="ghost" icon={<Trash2 size={14}/>} onClick={()=>setLines(rows=>rows.filter(r=>r.id!==line.id))}>Remove line</Button>}</div></div>)}<div className="field--full"><Button type="button" variant="secondary" icon={<Plus size={15}/>} onClick={()=>setLines(rows=>[...rows,newLine()])}>Add another product</Button></div><div className="order-preview"><Box size={20}/><div><span>{editingOrder?"Revised total":"Request total"}</span><strong>{requestCases} cases · {formPrice?formatMoney(requestCases*formPrice):"Pricing setup required"}</strong></div></div>{error&&<p className="form-error field--full" role="alert">{error}</p>}</form></Modal></div>
}
