"use client";
import { AlertCircle, Box, CheckCircle2, ChevronRight, CircleDollarSign, Copy, FileText, PackageSearch, Plus, Store, Trash2, Truck } from "lucide-react";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { canAdvanceFulfillment, canCreateOrder, isCustomer } from "../../lib/access";
import { activeReservedForOrder, orderCanAdvanceInventory, orderDeliveryQuantity, orderOutboundQuantity, productInventoryStatus } from "../../lib/inventory-ledger";
import { useInventoryLedger } from "../../lib/inventory-ledger-context";
import { orderLinesFor } from "../../lib/order-lines";
import { GOLDEN_EAGLE_SKUS } from "../../lib/product-catalog";
import { evaluatePartnerPricing } from "../../lib/pricing-engine";
import type { OrderStatus } from "../../lib/types";
import { useWorkspace } from "../../lib/workspace-context";
import { Button, Field, Modal, PageHeader, Section, StatusPill, formatMoney } from "../ui";
const lifecycle:OrderStatus[]=["Draft","Awaiting approval","Approved","Allocated","Out for delivery","Delivered","Paid"];
const fulfillmentNext:Partial<Record<OrderStatus,"Allocated"|"Out for delivery"|"Delivered">>={Approved:"Allocated",Allocated:"Out for delivery","Out for delivery":"Delivered"};
const tone=(status:OrderStatus)=>["Paid","Delivered"].includes(status)?"success" as const:status==="Awaiting approval"?"warning" as const:status==="Draft"?"neutral" as const:"info" as const;
type DraftLine={id:string;product:string;cases:number};const skuOptions=GOLDEN_EAGLE_SKUS.filter((sku)=>sku.active);
const newLine=(product=skuOptions[0]?.description??"Golden Eagle",cases=10):DraftLine=>({id:`draft-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,product,cases});
export function OrdersPage(){
 const{data,scope,currentUser,createOrder,navigate}=useWorkspace();const{ledger,advanceOrderFulfillment}=useInventoryLedger();
 const focusId=typeof window!=="undefined"?sessionStorage.getItem("momentum-focus-record"):null;const focused=scope.orders.find((o)=>o.id===focusId);const focusedAccount=scope.accounts.find((a)=>a.id===focusId);
 const[query,setQuery]=useState("");const[selectedId,setSelectedId]=useState(focused?.id??scope.orders[0]?.id??"");const[open,setOpen]=useState(false);const[error,setError]=useState("");
 const[accountId,setAccountId]=useState(focusedAccount?.id??scope.accounts[0]?.id??"");const[lines,setLines]=useState<DraftLine[]>([newLine()]);const customerMode=isCustomer(currentUser);const canFulfill=canAdvanceFulfillment(currentUser);
 useEffect(()=>{if(focusId)sessionStorage.removeItem("momentum-focus-record")},[focusId]);
 const orders=useMemo(()=>{const q=query.trim().toLowerCase();return scope.orders.filter((o)=>{const a=scope.accounts.find((x)=>x.id===o.accountId);return!q||`${o.number} ${a?.name??""} ${orderLinesFor(o).map((l)=>l.product).join(" ")} ${o.status}`.toLowerCase().includes(q)})},[query,scope.orders,scope.accounts]);
 const selected=scope.orders.find((o)=>o.id===selectedId)??orders[0];const selectedLines=selected?orderLinesFor(selected):[];const selectedApproval=selected?scope.approvals.find((approval)=>approval.recordId===selected.id&&["Order","Low stock sale"].includes(approval.type)):undefined;const currentIndex=selected?lifecycle.indexOf(selected.status):-1;const nextStatus=selected?fulfillmentNext[selected.status]??null:null;
 const reserved=selected?activeReservedForOrder(ledger,selected.id):0;const outbound=selected?orderOutboundQuantity(ledger,selected.id):0;const delivered=selected?orderDeliveryQuantity(ledger,selected.id):0;const inventoryReady=Boolean(selected&&nextStatus&&orderCanAdvanceInventory(ledger,selected,nextStatus));
 const pricing=accountId?evaluatePartnerPricing(data,accountId):null;const price=pricing?.currentPricePerCase;const requestCases=lines.reduce((s,l)=>s+(Number.isInteger(l.cases)&&l.cases>0?l.cases:0),0);
 const openDraft=(order?:typeof selected)=>{setAccountId(order?.accountId??focusedAccount?.id??scope.accounts[0]?.id??"");setLines(order?orderLinesFor(order).map((l)=>newLine(l.product,l.cases)):[newLine()]);setError("");setOpen(true)};
 const submit=(e:FormEvent)=>{e.preventDefault();if(!price){setError("Current account pricing must be configured before this order can be submitted.");return}if(!lines.length||lines.some((l)=>!Number.isInteger(l.cases)||l.cases<1)){setError("Every order line needs a whole-number case quantity of at least 1.");return}const id=createOrder({accountId,lines:lines.map((l)=>({...l,inventoryAvailableAtOrder:productInventoryStatus(ledger,data,l.product).available}))});if(!id){setError("Momentum rejected this request. Review the account, pricing, quantities, and permissions. Nothing was silently submitted.");return}setSelectedId(id);setOpen(false);setError("")};
 const advance=()=>{if(!selected||!nextStatus)return;if(!advanceOrderFulfillment(selected.id,nextStatus)){setError("Inventory evidence is incomplete for the next fulfillment step. Open Inventory to finish reservations or custody records.");return}setError("")};
 return <div className="page page--orders"><PageHeader title={customerMode?"My orders":"Orders"} actions={canCreateOrder(currentUser)?<Button variant="gold" icon={<Plus size={17}/>} onClick={()=>openDraft()}>{customerMode?"Place order":"Create order"}</Button>:undefined}/>
 <div className="order-stats"><div><span><FileText size={18}/></span><div><small>Orders in scope</small><strong>{scope.orders.length}</strong></div></div><div><span><CircleDollarSign size={18}/></span><div><small>Open amount</small><strong>{formatMoney(scope.orders.filter(o=>o.paymentStatus!=="Paid").reduce((s,o)=>s+o.amount,0))}</strong></div></div><div><span><Truck size={18}/></span><div><small>Delivered cases</small><strong>{scope.orders.filter(o=>["Delivered","Paid"].includes(o.status)).reduce((s,o)=>s+o.cases,0)}</strong></div></div><div><span><PackageSearch size={18}/></span><div><small>Canonical SKUs</small><strong>{skuOptions.length}</strong></div></div></div>
 <div className="orders-layout"><Section className="orders-list" title="Order register"><label className="table-search order-search"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search order, account, SKU, or status…"/></label><div className="order-table order-table--head"><span>Order</span><span>Customer</span><span>Cases</span><span>Amount</span><span>Status</span><span/></div><div className="order-table-body">{orders.map(o=>{const a=scope.accounts.find(x=>x.id===o.accountId);return <button className={`order-table ${selected?.id===o.id?"is-selected":""}`} key={o.id} onClick={()=>setSelectedId(o.id)}><span><strong>{o.number}</strong><small>{orderLinesFor(o).length===1?orderLinesFor(o)[0].product:`${orderLinesFor(o).length} SKUs`}</small></span><span><strong>{a?.name}</strong><small>{a?.locationName??a?.location}</small></span><span>{o.cases}</span><span>{formatMoney(o.amount)}</span><span><StatusPill tone={tone(o.status)}>{o.status}</StatusPill></span><ChevronRight size={16}/></button>})}</div></Section>
 {selected&&<Section className="order-detail" title={selected.number} action={<StatusPill tone={tone(selected.status)}>{selected.status}</StatusPill>}><div className="order-detail__body"><div className="order-price-card"><div><span>Order total</span><strong>{formatMoney(selected.amount)}</strong><small>{selected.cases} total cases · {selectedLines.length} SKU{selectedLines.length===1?"":"s"}</small></div><span><FileText size={24}/></span></div><div className="order-detail-actions">{canCreateOrder(currentUser)&&<Button size="sm" variant="secondary" icon={<Copy size={14}/>} onClick={()=>openDraft(selected)}>Copy / reorder</Button>}</div><div className="company-request-list">{selectedLines.map(l=><article key={l.id}><span><Box size={16}/></span><div><small>Order line</small><strong>{l.cases} cases · {l.product}</strong><p>{formatMoney(l.pricePerCase)} / case · {formatMoney(l.amount)}</p></div></article>)}</div><div className="order-lifecycle">{lifecycle.map((s,i)=><div className={i<=currentIndex?"is-complete":""} key={s}><span>{i<currentIndex?<CheckCircle2 size={14}/>:i+1}</span><small>{s}</small></div>)}</div><dl className="order-facts"><div><dt>Reserved</dt><dd>{reserved}/{selected.cases}</dd></div><div><dt>Outbound custody</dt><dd>{outbound}/{selected.cases}</dd></div><div><dt>Delivered</dt><dd>{delivered}/{selected.cases}</dd></div><div><dt>Payment</dt><dd>{selected.paymentStatus}</dd></div></dl>
 {selected.status==="Awaiting approval"?<div className="order-approval-callout"><Store size={20}/><div><strong>One Administrator approval required</strong><p>Once either Administrator approves this order, that decision is authoritative for the shared order record.</p></div>{currentUser?.role==="Administrator"&&<Button size="sm" onClick={()=>navigate("work")}>Review</Button>}</div>:selected.status==="Draft"?<div className="order-approval-callout"><AlertCircle size={20}/><div><strong>Returned for edits</strong><p>{selectedApproval?.returnReason?`Correction requested: ${selectedApproval.returnReason}`:"The original record remains in history. Copy it to submit a corrected replacement."}</p></div></div>:nextStatus&&canFulfill&&inventoryReady?<Button size="lg" onClick={advance}>Move to {nextStatus.toLowerCase()}</Button>:nextStatus&&canFulfill?<div className="order-approval-callout"><PackageSearch size={20}/><div><strong>Inventory evidence required</strong><p>Reserve the exact SKU mix and complete custody evidence before moving forward.</p></div><Button size="sm" variant="secondary" onClick={()=>navigate("inventory")}>Open inventory</Button></div>:null}{error&&<p className="form-error" role="alert">{error}</p>}</div></Section>}</div>
 <Modal open={open} title="Create order request" description="Add as many Golden Eagle SKUs as the customer needs. There is no 10-case maximum. One Administrator approval covers the complete order." onClose={()=>setOpen(false)} wide footer={<><Button variant="ghost" onClick={()=>setOpen(false)}>Cancel</Button><Button type="submit" form="order-v3-form">Submit order</Button></>}><form id="order-v3-form" className="form-grid" onSubmit={submit}><Field label="Customer account" className="field--full"><select value={accountId} onChange={e=>setAccountId(e.target.value)}>{scope.accounts.map(a=><option key={a.id} value={a.id}>{a.name} · {a.locationName??a.location}</option>)}</select></Field>{lines.map((line,index)=><div className="field--full form-grid" key={line.id}><Field label={`Product ${index+1}`}><select value={line.product} onChange={e=>setLines(rows=>rows.map(r=>r.id===line.id?{...r,product:e.target.value}:r))}>{skuOptions.map(s=><option value={s.description} key={s.id}>{s.description}</option>)}</select></Field><Field label="Cases"><input type="number" min="1" step="1" required value={line.cases} onChange={e=>setLines(rows=>rows.map(r=>r.id===line.id?{...r,cases:Number(e.target.value)}:r))}/></Field><div className="field--full"><small>{productInventoryStatus(ledger,data,line.product).available} currently available sellable cases</small>{lines.length>1&&<Button type="button" size="sm" variant="ghost" icon={<Trash2 size={14}/>} onClick={()=>setLines(rows=>rows.filter(r=>r.id!==line.id))}>Remove line</Button>}</div></div>)}<div className="field--full"><Button type="button" variant="secondary" icon={<Plus size={15}/>} onClick={()=>setLines(rows=>[...rows,newLine()])}>Add another product</Button></div><div className="order-preview"><Box size={20}/><div><span>Request total</span><strong>{requestCases} cases · {price?formatMoney(requestCases*price):"Pricing setup required"}</strong></div></div>{error&&<p className="form-error field--full" role="alert">{error}</p>}</form></Modal></div>
}
