"use client";

import { AlertOctagon, AlertTriangle, ArrowRight, Boxes, Check, CheckCircle2, ClipboardCheck, Clock3, Eye, FileText, RotateCcw, ShieldCheck, Store } from "lucide-react";
import { useMemo, useState } from "react";
import { canReviewApproval } from "../../lib/access";
import { useHcm } from "../../lib/hcm-context";
import { appendAudit } from "../../lib/hcm-engine";
import type { Approval, PageKey } from "../../lib/types";
import { useWorkspace } from "../../lib/workspace-context";
import { TimecardRecord } from "../hcm/timecard-record";
import { Avatar, Button, Field, Modal, PageHeader, Section, StatusPill, formatDate, formatMoney, hoursBetween } from "../ui";

const orderApproval=(type:Approval["type"])=>type==="Order"||type==="Low stock sale";
const iconFor=(type:Approval["type"])=>type==="Timecard"?Clock3:orderApproval(type)?ClipboardCheck:type==="Inventory adjustment"?Boxes:ShieldCheck;
const priorityTone=(priority:Approval["priority"])=>priority==="Urgent"?"danger" as const:priority==="High"?"warning" as const:"neutral" as const;

type ExceptionRecord={id:string;icon:typeof AlertTriangle;tone:"danger"|"warning"|"info";title:string;detail:string;action:string;page:PageKey;focus?:string;peopleTab?:string};

export function WorkPage(){
  const {data,scope,currentUser,decideApproval,decideTimecard,navigate}=useWorkspace();
  const {hcm,setHcm}=useHcm();
  const [tab,setTab]=useState<"approvals"|"exceptions"|"completed">("approvals");
  const [reviewId,setReviewId]=useState<string|null>(null);
  const [returnNote,setReturnNote]=useState("");
  if(!currentUser)return null;
  const pending=scope.approvals.filter((approval)=>approval.status==="Pending");
  const completed=scope.approvals.filter((approval)=>approval.status!=="Pending");
  const reviewApproval=scope.approvals.find((approval)=>approval.id===reviewId)??null;
  const reviewOrder=reviewApproval&&orderApproval(reviewApproval.type)?scope.orders.find((order)=>order.id===reviewApproval.recordId)??null:null;
  const reviewAccount=reviewOrder?scope.accounts.find((account)=>account.id===reviewOrder.accountId)??null:null;
  const reviewTimecard=reviewApproval?.type==="Timecard"?data.timecards.find((card)=>card.id===reviewApproval.recordId)??null:null;
  const reviewEmployee=reviewTimecard?data.users.find((user)=>user.id===reviewTimecard.userId):undefined;
  const reviewEntries=useMemo(()=>reviewTimecard?data.timeEntries.filter((entry)=>entry.userId===reviewTimecard.userId&&entry.date>=reviewTimecard.weekStart&&entry.date<=reviewTimecard.weekEnd):[],[data.timeEntries,reviewTimecard]);
  const reviewHours=reviewEntries.reduce((sum,entry)=>sum+hoursBetween(entry.clockIn,entry.clockOut,entry.breakMinutes),0);
  const canDecide=Boolean(reviewApproval&&canReviewApproval(data,currentUser,reviewApproval)&&(reviewApproval.type!=="Timecard"||reviewTimecard?.userId!==currentUser.id));
  const auditReturn=(cardId:string,note:string)=>setHcm((state)=>appendAudit(state,{actorId:currentUser.id,action:"Timecard returned",entityType:"TimecardReview",entityId:cardId,reason:note.trim()}));
  const auditApprove=(cardId:string)=>setHcm((state)=>appendAudit(state,{actorId:currentUser.id,action:"Timecard approved",entityType:"TimecardReview",entityId:cardId}));

  const openReview=(id:string)=>{setReviewId(id);setReturnNote("");};
  const decide=(decision:"Approved"|"Returned")=>{if(!reviewApproval)return;if(reviewApproval.type==="Timecard"&&reviewTimecard){if(decision==="Returned"&&!returnNote.trim())return;if(decision==="Returned")auditReturn(reviewTimecard.id,returnNote);else auditApprove(reviewTimecard.id);decideTimecard(reviewTimecard.id,decision==="Approved"?"Manager approved":"Returned");}else decideApproval(reviewApproval.id,decision);setReviewId(null);setReturnNote("");};
  const openFullRecord=()=>{if(!reviewApproval)return;if(reviewOrder){window.sessionStorage.setItem("momentum-focus-record",reviewOrder.id);setReviewId(null);navigate("orders");return;}if(reviewTimecard){window.sessionStorage.setItem("momentum-focus-record",reviewTimecard.id);window.sessionStorage.setItem("momentum-people-tab","time");setReviewId(null);navigate("people");}};
  const openException=(item:ExceptionRecord)=>{if(item.focus)window.sessionStorage.setItem("momentum-focus-record",item.focus);if(item.peopleTab)window.sessionStorage.setItem("momentum-people-tab",item.peopleTab);navigate(item.page);};
  const detailFor=(approval:Approval)=>{if(approval.type==="Timecard"){const card=data.timecards.find((item)=>item.id===approval.recordId);if(!card)return approval.detail;const entries=data.timeEntries.filter((entry)=>entry.userId===card.userId&&entry.date>=card.weekStart&&entry.date<=card.weekEnd);const hours=entries.reduce((sum,entry)=>sum+hoursBetween(entry.clockIn,entry.clockOut,entry.breakMinutes),0);return`${hours.toFixed(2)} hours · ${entries.length} daily records · ${card.attested?"employee attested":"attestation missing"}`;}if(orderApproval(approval.type)){const order=scope.orders.find((item)=>item.id===approval.recordId);const account=scope.accounts.find((item)=>item.id===order?.accountId);return order?`${order.cases} cases · ${formatMoney(order.amount)} · ${account?.locationName??account?.name??"Linked account"}`:approval.detail;}return approval.detail;};
  const lastReturnReason=(cardId:string)=>hcm.audit.find((event)=>event.entityType==="TimecardReview"&&event.entityId===cardId&&event.action==="Timecard returned")?.reason;

  const exceptions:ExceptionRecord[]=[...scope.inventory.filter((lot)=>lot.status==="Quality hold").map((lot)=>({id:`hold-${lot.id}`,icon:Boxes,tone:"danger" as const,title:`${lot.lotCode} quality hold`,detail:`${lot.onHand} cases at ${lot.location} are unavailable.`,action:"Open inventory",page:"inventory" as PageKey,focus:lot.id})),...scope.placements.filter((placement)=>placement.status!=="Healthy").map((placement)=>{const account=scope.accounts.find((item)=>item.id===placement.accountId);return{id:`placement-${placement.id}`,icon:Store,tone:placement.status==="Out of stock"?"danger" as const:"warning" as const,title:`${account?.name??"Placement"}: ${placement.status}`,detail:`${placement.observedStock} units · ${placement.facings} facings · ${placement.cold?"cold":"not cold"}`,action:"Open placement",page:"retail" as PageKey,focus:placement.id};}),...scope.timecards.filter((card)=>card.status==="Returned").map((card)=>({id:`timecard-${card.id}`,icon:Clock3,tone:"warning" as const,title:`${data.users.find((user)=>user.id===card.userId)?.name??"Employee"} timecard returned`,detail:lastReturnReason(card.id)??`Week ending ${formatDate(card.weekEnd)} requires correction and resubmission.`,action:"Open timecard",page:"people" as PageKey,focus:card.id,peopleTab:"time"}))];
  const dueToday=pending.filter((item)=>new Date(item.dueAt).toDateString()===new Date().toDateString()).length;
  const approvalCard=(approval:Approval)=>{const Icon=iconFor(approval.type);const requester=data.users.find((user)=>user.id===approval.requesterId);const allowed=canReviewApproval(data,currentUser,approval);return <article className="approval-card" key={approval.id}><div className={`approval-card__icon approval-card__icon--${approval.priority.toLowerCase()}`}><Icon size={20}/></div><div className="approval-card__main"><div className="approval-card__heading"><span>{approval.type}</span><StatusPill tone={priorityTone(approval.priority)} dot={false}>{approval.priority}</StatusPill></div><h3>{approval.title}</h3><p>{detailFor(approval)}</p><div className="approval-card__meta">{requester&&<Avatar initials={requester.initials} color={requester.accent} size="sm"/>}<span>{approval.requestedBy}</span><i/><span>{formatDate(approval.submittedAt,{month:"short",day:"numeric",hour:"numeric",minute:"2-digit"})}</span></div></div><div className="approval-card__actions approval-card__actions--review"><Button size="sm" variant={allowed?"primary":"secondary"} icon={<Eye size={15}/>} onClick={()=>openReview(approval.id)}>Review</Button></div></article>;};

  return <div className="page page--work page--work-v2"><PageHeader title="My work" actions={<StatusPill tone={pending.some((item)=>item.priority==="Urgent")?"danger":"info"}>{pending.length} pending</StatusPill>}/><div className="work-summary"><div><span><ClipboardCheck size={19}/></span><div><small>Pending approval</small><strong>{pending.length}</strong></div></div><div><span><AlertOctagon size={19}/></span><div><small>Exceptions</small><strong>{exceptions.length}</strong></div></div><div><span><Clock3 size={19}/></span><div><small>Due today</small><strong>{dueToday}</strong></div></div><div><span><CheckCircle2 size={19}/></span><div><small>Completed</small><strong>{completed.length}</strong></div></div></div><div className="work-tabs"><button className={tab==="approvals"?"is-active":""} onClick={()=>setTab("approvals")}>Approvals <i>{pending.length}</i></button><button className={tab==="exceptions"?"is-active":""} onClick={()=>setTab("exceptions")}>Exceptions <i>{exceptions.length}</i></button><button className={tab==="completed"?"is-active":""} onClick={()=>setTab("completed")}>Completed</button></div>
    {tab==="approvals"&&<Section title="Ready for review" className="approval-list-panel"><div className="approval-list">{pending.map(approvalCard)}</div>{pending.length===0&&<div className="review-empty"><CheckCircle2 size={27}/><h3>No approvals waiting</h3></div>}</Section>}
    {tab==="exceptions"&&<Section title="Exceptions" className="exception-list-panel"><div className="exception-list">{exceptions.map((item)=>{const Icon=item.icon;return <article key={item.id}><span className={`exception-icon exception-icon--${item.tone}`}><Icon size={20}/></span><div><StatusPill tone={item.tone} dot={false}>{item.tone==="danger"?"Blocking":"Needs review"}</StatusPill><h3>{item.title}</h3><p>{item.detail}</p></div><Button variant="secondary" size="sm" icon={<ArrowRight size={15}/>} onClick={()=>openException(item)}>{item.action}</Button></article>})}</div></Section>}
    {tab==="completed"&&<Section title="Decision history" className="completed-list-panel">{completed.map((approval)=>{const card=approval.type==="Timecard"?data.timecards.find((item)=>item.id===approval.recordId):undefined;return <article className="completed-item" key={approval.id}><span><CheckCircle2 size={18}/></span><div><strong>{approval.title}</strong><p>{approval.type} · {approval.requestedBy}{card?.status==="Returned"&&lastReturnReason(card.id)?` · ${lastReturnReason(card.id)}`:""}</p></div><StatusPill tone={approval.status==="Approved"?"success":"danger"}>{approval.status}</StatusPill></article>})}{completed.length===0&&<div className="review-empty"><p>No completed decisions.</p></div>}</Section>}

    <Modal open={Boolean(reviewApproval)} title={reviewApproval?.title??"Review record"} onClose={()=>setReviewId(null)} wide footer={reviewApproval?<><Button variant="ghost" onClick={()=>setReviewId(null)}>Close</Button>{(reviewOrder||reviewTimecard)&&<Button variant="secondary" icon={<FileText size={15}/>} onClick={openFullRecord}>Open full record</Button>}{canDecide&&<Button variant="secondary" icon={<RotateCcw size={15}/>} disabled={reviewApproval.type==="Timecard"&&!returnNote.trim()} onClick={()=>decide("Returned")}>Return</Button>}{canDecide&&<Button icon={<Check size={15}/>} onClick={()=>decide("Approved")}>Approve</Button>}</>:undefined}>
      {reviewApproval&&<div className="record-review"><div className="record-review__banner"><ShieldCheck size={20}/><div><strong>Review before deciding</strong><p>{reviewApproval.type} · submitted {formatDate(reviewApproval.submittedAt,{month:"short",day:"numeric",hour:"numeric",minute:"2-digit"})}</p></div><StatusPill tone={priorityTone(reviewApproval.priority)} dot={false}>{reviewApproval.priority}</StatusPill></div>
        {reviewTimecard&&<><TimecardRecord timecardId={reviewTimecard.id} history={false}/>{canDecide&&<Field label="Return instructions" hint="Required when returning the timecard. The employee will see this reason in the full record."><textarea rows={3} value={returnNote} onChange={(event)=>setReturnNote(event.target.value)} placeholder="Tell the employee exactly what needs to be corrected."/></Field>}</>}
        {reviewOrder&&<div className="record-review__section"><h3>Order record</h3><div className="record-review__facts"><div><span>Customer</span><strong>{reviewAccount?.name??"Linked account"}</strong></div><div><span>Location</span><strong>{reviewAccount?.locationName??reviewAccount?.location??"—"}</strong></div><div><span>Quantity</span><strong>{reviewOrder.cases} cases</strong></div><div><span>Price / case</span><strong>{formatMoney(reviewOrder.pricePerCase)}</strong></div><div><span>Total</span><strong>{formatMoney(reviewOrder.amount)}</strong></div><div><span>Status</span><strong>{reviewOrder.status}</strong></div></div></div>}
        {!reviewOrder&&!reviewTimecard&&<div className="record-review__section"><AlertTriangle size={20}/><h3>{reviewApproval.type}</h3><p>{reviewApproval.detail}</p></div>}
      </div>}
    </Modal>
  </div>;
}
