"use client";

import { AlertOctagon, AlertTriangle, ArrowRight, Boxes, Check, CheckCircle2, ClipboardCheck, Clock3, Eye, FileText, PackageSearch, RotateCcw, ShieldAlert, ShieldCheck, Store } from "lucide-react";
import { useMemo, useState } from "react";
import { canReviewApproval } from "../../lib/access";
import { accountHealthSnapshot } from "../../lib/account-health";
import { productInventoryStatus } from "../../lib/inventory-ledger";
import { useInventoryLedger } from "../../lib/inventory-ledger-context";
import type { Approval, PageKey } from "../../lib/types";
import { useWorkspace } from "../../lib/workspace-context";
import { RecordHistory } from "../audit/record-history";
import { Avatar, Button, Modal, PageHeader, Section, StatusPill, formatDate, formatMoney, hoursBetween } from "../ui";

const orderApproval=(type:Approval["type"])=>type==="Order"||type==="Low stock sale";
const iconForApproval=(type:Approval["type"])=>type==="Timecard"?Clock3:orderApproval(type)?ClipboardCheck:type==="Inventory adjustment"?Boxes:ShieldCheck;
const priorityTone=(priority:Approval["priority"])=>priority==="Urgent"?"danger" as const:priority==="High"?"warning" as const:"neutral" as const;

export function WorkPage(){
  const{data,scope,currentUser,decideApproval,decideTimecard,navigate}=useWorkspace();const{ledger}=useInventoryLedger();
  const[tab,setTab]=useState<"approvals"|"exceptions"|"completed">("approvals");const[reviewId,setReviewId]=useState<string|null>(null);
  const pending=scope.approvals.filter((approval)=>approval.status==="Pending");const completed=scope.approvals.filter((approval)=>approval.status!=="Pending");const dueToday=pending.filter((item)=>new Date(item.dueAt).toDateString()===new Date().toDateString()).length;const reviewApproval=scope.approvals.find((approval)=>approval.id===reviewId)??null;
  const reviewOrder=reviewApproval&&orderApproval(reviewApproval.type)?scope.orders.find((order)=>order.id===reviewApproval.recordId)??null:null;const reviewAccount=reviewOrder?scope.accounts.find((account)=>account.id===reviewOrder.accountId)??null:null;const reviewTimecard=reviewApproval?.type==="Timecard"?data.timecards.find((card)=>card.id===reviewApproval.recordId)??null:null;const reviewEmployee=reviewTimecard?data.users.find((user)=>user.id===reviewTimecard.userId)??null:null;
  const reviewEntries=useMemo(()=>reviewTimecard?data.timeEntries.filter((entry)=>entry.userId===reviewTimecard.userId&&entry.date>=reviewTimecard.weekStart&&entry.date<=reviewTimecard.weekEnd).sort((a,b)=>a.date.localeCompare(b.date)):[],[data.timeEntries,reviewTimecard]);const reviewHours=reviewEntries.reduce((sum,entry)=>sum+hoursBetween(entry.clockIn,entry.clockOut,entry.breakMinutes),0);
  const orderStock=reviewOrder?.product?productInventoryStatus(ledger,data,reviewOrder.product):null;const accountHealth=reviewAccount?accountHealthSnapshot(data,reviewAccount):null;const creditedRep=reviewOrder?data.users.find((user)=>user.id===(reviewOrder.creditedRepId??reviewOrder.ownerId)&&user.role==="Sales Representative"):undefined;const priorOrders=reviewOrder?data.orders.filter((order)=>order.accountId===reviewOrder.accountId&&order.id!==reviewOrder.id).sort((a,b)=>b.placedAt.localeCompare(a.placedAt)).slice(0,5):[];
  const canDecideReview=Boolean(reviewApproval&&canReviewApproval(data,currentUser,reviewApproval)&&(reviewApproval.type!=="Timecard"||reviewTimecard?.userId!==currentUser?.id));
  const decide=(approval:Approval,decision:"Approved"|"Returned")=>{if(approval.type==="Timecard"){const card=data.timecards.find((item)=>item.id===approval.recordId&&item.status==="Submitted");if(card){decideTimecard(card.id,decision==="Approved"?"Manager approved":"Returned");setReviewId(null);return;}}decideApproval(approval.id,decision);setReviewId(null);};
  const openFullRecord=()=>{if(!reviewApproval)return;if(orderApproval(reviewApproval.type)&&reviewOrder){window.sessionStorage.setItem("momentum-focus-record",reviewOrder.id);setReviewId(null);navigate("orders");return;}if(reviewApproval.type==="Timecard"){setReviewId(null);navigate("people");}};
  const detailFor=(approval:Approval)=>{if(approval.type==="Timecard"){const card=data.timecards.find((item)=>item.id===approval.recordId);if(!card)return approval.detail;const entries=data.timeEntries.filter((entry)=>entry.userId===card.userId&&entry.date>=card.weekStart&&entry.date<=card.weekEnd);const hours=entries.reduce((sum,entry)=>sum+hoursBetween(entry.clockIn,entry.clockOut,entry.breakMinutes),0);return`${hours.toFixed(2)} hours · ${entries.length} daily records · ${card.attested?"employee attested":"attestation missing"}`;}if(orderApproval(approval.type)){const order=scope.orders.find((item)=>item.id===approval.recordId);const account=scope.accounts.find((item)=>item.id===order?.accountId);return order?`${order.product??"Golden Eagle"} · ${order.cases} cases · ${formatMoney(order.amount)} · ${account?.locationName??account?.name??"Linked account"}`:approval.detail;}return approval.detail;};
  const approvalCard=(approval:Approval)=>{const Icon=iconForApproval(approval.type);const requester=data.users.find((user)=>user.id===approval.requesterId)??data.users.find((user)=>user.name===approval.requestedBy);const canDecide=canReviewApproval(data,currentUser,approval);return <article className="approval-card" key={approval.id}><div className={`approval-card__icon approval-card__icon--${approval.priority.toLowerCase()}`}><Icon size={20}/></div><div className="approval-card__main"><div className="approval-card__heading"><span>{approval.type}</span><StatusPill tone={priorityTone(approval.priority)} dot={false}>{approval.priority}</StatusPill></div><h3>{approval.title}</h3><p>{detailFor(approval)}</p><div className="approval-card__meta">{requester&&<Avatar initials={requester.initials} color={requester.accent} size="sm"/>}<span>Requested by {approval.requestedBy}</span><i/><span>{formatDate(approval.submittedAt,{month:"short",day:"numeric",hour:"numeric",minute:"2-digit"})}</span></div></div><div className="approval-card__actions approval-card__actions--review"><Button size="sm" variant={canDecide?"primary":"secondary"} icon={<Eye size={15}/>} onClick={()=>setReviewId(approval.id)}>Review</Button>{!canDecide&&<span className="approval-card__waiting"><Clock3 size={15}/><span>Authorized reviewer required</span></span>}</div></article>;};
  const exceptionRecords:Array<{icon:typeof AlertTriangle;tone:"danger"|"warning"|"info";title:string;detail:string;action:string;page:PageKey}>=[...scope.inventory.filter((lot)=>lot.status==="Quality hold").map((lot)=>({icon:Boxes,tone:"danger" as const,title:`${lot.lotCode} quality hold`,detail:`${lot.onHand} cases at ${lot.location} are unavailable.`,action:"Open inventory",page:"inventory" as PageKey})),...scope.placements.filter((placement)=>placement.status!=="Healthy").map((placement)=>{const account=scope.accounts.find((item)=>item.id===placement.accountId);return{icon:Store,tone:placement.status==="Out of stock"?"danger" as const:"warning" as const,title:`${account?.name??"Placement"}: ${placement.status}`,detail:`${placement.observedStock} units · ${placement.facings} facings · ${placement.cold?"cold":"not cold"}`,action:"Open placement",page:"retail" as PageKey};}),...scope.timecards.filter((card)=>card.status==="Returned").map((card)=>({icon:Clock3,tone:"warning" as const,title:`${data.users.find((user)=>user.id===card.userId)?.name??"Employee"} timecard returned`,detail:`Week ending ${formatDate(card.weekEnd)} requires correction.`,action:"Open timecard",page:"people" as PageKey}))];
  return <div className="page page--work"><PageHeader title="My work" actions={<StatusPill tone={pending.some((item)=>item.priority==="Urgent")?"danger":"info"}>{pending.length} pending</StatusPill>}/><div className="work-summary"><div><span><ClipboardCheck size={19}/></span><div><small>Pending approval</small><strong>{pending.length}</strong></div></div><div><span><AlertOctagon size={19}/></span><div><small>Exceptions</small><strong>{exceptionRecords.length}</strong></div></div><div><span><Clock3 size={19}/></span><div><small>Due today</small><strong>{dueToday}</strong></div></div><div><span><CheckCircle2 size={19}/></span><div><small>Completed</small><strong>{completed.length}</strong></div></div></div><div className="work-tabs"><button className={tab==="approvals"?"is-active":""} onClick={()=>setTab("approvals")}>Approvals <i>{pending.length}</i></button><button className={tab==="exceptions"?"is-active":""} onClick={()=>setTab("exceptions")}>Exceptions <i>{exceptionRecords.length}</i></button><button className={tab==="completed"?"is-active":""} onClick={()=>setTab("completed")}>Completed</button></div>
    {tab==="approvals"&&<Section title="Ready for review" className="approval-list-panel"><div className="approval-list">{pending.map(approvalCard)}</div>{pending.length===0&&<div className="review-empty"><CheckCircle2 size={27}/><h3>No approvals waiting</h3></div>}</Section>}
    {tab==="exceptions"&&<Section title="Exceptions" className="exception-list-panel"><div className="exception-list">{exceptionRecords.map((item)=>{const Icon=item.icon;return <article key={item.title}><span className={`exception-icon exception-icon--${item.tone}`}><Icon size={20}/></span><div><StatusPill tone={item.tone} dot={false}>{item.tone==="danger"?"Blocking":"Needs review"}</StatusPill><h3>{item.title}</h3><p>{item.detail}</p></div><Button variant="secondary" size="sm" icon={<ArrowRight size={15}/>} onClick={()=>navigate(item.page)}>{item.action}</Button></article>;})}</div></Section>}
    {tab==="completed"&&<Section title="Decision history" className="completed-list-panel">{completed.map((approval)=><article className="completed-item" key={approval.id}><span><CheckCircle2 size={18}/></span><div><strong>{approval.title}</strong><p>{approval.type} · {approval.requestedBy}</p></div><StatusPill tone={approval.status==="Approved"?"success":"danger"}>{approval.status}</StatusPill></article>)}{completed.length===0&&<div className="review-empty"><p>No completed decisions.</p></div>}</Section>}
    <Modal open={Boolean(reviewApproval)} title={reviewApproval?.title??"Review record"} onClose={()=>setReviewId(null)} wide footer={reviewApproval?<><Button variant="ghost" onClick={()=>setReviewId(null)}>Close</Button>{(reviewOrder||reviewTimecard)&&<Button variant="secondary" icon={<FileText size={15}/>} onClick={openFullRecord}>Open full record</Button>}{canDecideReview&&<Button variant="secondary" icon={<RotateCcw size={15}/>} onClick={()=>decide(reviewApproval,"Returned")}>Return</Button>}{canDecideReview&&<Button icon={<Check size={15}/>} onClick={()=>decide(reviewApproval,"Approved")}>Approve</Button>}</>:undefined}>
      {reviewApproval&&<div className="record-review"><div className="record-review__banner"><ShieldCheck size={20}/><div><strong>Decision record</strong><p>{reviewApproval.type} · submitted {formatDate(reviewApproval.submittedAt,{month:"short",day:"numeric",hour:"numeric",minute:"2-digit"})}</p></div><StatusPill tone={priorityTone(reviewApproval.priority)} dot={false}>{reviewApproval.priority}</StatusPill></div>
        {reviewOrder&&<div className="record-review__section"><div className="record-review__heading"><h3>Order review</h3>{reviewOrder.lowStockApprovalRequired&&<StatusPill tone="danger">Low stock</StatusPill>}</div><div className="record-review__facts"><div><span>Customer</span><strong>{reviewAccount?.name??"Linked account"}</strong></div><div><span>Location</span><strong>{reviewAccount?.locationName??reviewAccount?.location??"—"}</strong></div><div><span>Product</span><strong>{reviewOrder.product??"Golden Eagle"}</strong></div><div><span>Quantity</span><strong>{reviewOrder.cases} cases</strong></div><div><span>Pricing tier</span><strong>{reviewAccount?.pricingTier??"Not assigned"}</strong></div><div><span>Price / case</span><strong>{formatMoney(reviewOrder.pricePerCase)}</strong></div><div><span>Total</span><strong>{formatMoney(reviewOrder.amount)}</strong></div><div><span>Sales credit</span><strong>{creditedRep?.name??"No rep credit"}</strong></div><div><span>Available at request</span><strong>{reviewOrder.inventoryAvailableAtOrder??"Not recorded"}</strong></div><div><span>Available now</span><strong>{orderStock?.available??"Not tracked"}</strong></div><div><span>Last order</span><strong>{accountHealth?.lastOrderDate?formatDate(accountHealth.lastOrderDate):"None"}</strong></div><div><span>3-mo avg</span><strong>{accountHealth?.rolling3MonthMonthlyAverage??0} cases/mo</strong></div></div>{reviewOrder.lowStockApprovalRequired&&<div className="record-review__consequence"><ShieldAlert size={17}/><p>The request was created below 50 available sellable cases. Approval authorizes the sale to enter fulfillment; it does not change the warehouse reorder flag.</p></div>}{orderStock?.reorderNeeded&&<div className="record-review__consequence"><PackageSearch size={17}/><p>{orderStock.available} available sellable cases remain. Replenishment is required below 500.</p></div>}<div className="record-review__related"><h4>Recent orders at this location</h4>{priorOrders.map((order)=><div key={order.id}><strong>{order.number}</strong><span>{formatDate(order.placedAt)} · {order.product??"Golden Eagle"} · {order.cases} cases · {order.paymentStatus}</span></div>)}{priorOrders.length===0&&<span>No prior orders.</span>}</div><RecordHistory entityType="Workspace.orders" entityId={reviewOrder.id} limit={12}/></div>}
        {reviewTimecard&&<div className="record-review__section"><div className="record-review__heading"><h3>Timecard review</h3><StatusPill tone={reviewTimecard.attested?"success":"danger"}>{reviewTimecard.attested?"Employee attested":"Attestation missing"}</StatusPill></div><div className="record-review__facts record-review__facts--compact"><div><span>Employee</span><strong>{reviewEmployee?.name??"Employee"}</strong></div><div><span>Period</span><strong>{formatDate(reviewTimecard.weekStart,{month:"short",day:"numeric"})} – {formatDate(reviewTimecard.weekEnd,{month:"short",day:"numeric"})}</strong></div><div><span>Recorded hours</span><strong>{reviewHours.toFixed(2)}</strong></div><div><span>Daily records</span><strong>{reviewEntries.length}</strong></div></div><div className="record-review__table-wrap"><table className="record-review__table"><thead><tr><th>Date</th><th>In</th><th>Meal</th><th>Out</th><th>Hours</th><th>Source</th></tr></thead><tbody>{reviewEntries.map((entry)=><tr key={entry.id}><td>{formatDate(entry.date,{month:"short",day:"numeric"})}</td><td>{entry.clockIn}</td><td>{entry.mealStart&&entry.mealEnd?`${entry.mealStart}–${entry.mealEnd}`:`${entry.breakMinutes} min`}</td><td>{entry.clockOut??"Missing"}</td><td>{hoursBetween(entry.clockIn,entry.clockOut,entry.breakMinutes).toFixed(2)}</td><td>{entry.source}</td></tr>)}</tbody></table></div></div>}
        {!reviewOrder&&!reviewTimecard&&<div className="record-review__section"><AlertTriangle size={20}/><h3>{reviewApproval.type}</h3><p>{reviewApproval.detail}</p><p>Open the source module before deciding when additional context is required.</p></div>}
      </div>}
    </Modal>
  </div>;
}
