"use client";

import { BellRing, LockKeyhole, Radio, ShieldCheck, Smartphone, UnlockKeyhole } from "lucide-react";
import { FormEvent, useState } from "react";
import type { PeriodLockDomain } from "../../lib/period-lock-engine";
import { usePeriodLocks } from "../../lib/period-lock-context";
import { useAudit } from "../../lib/audit-context";
import { useNotifications } from "../../lib/notification-context";
import { useRuntimeMode } from "../../lib/runtime-mode";
import { useWorkspace } from "../../lib/workspace-context";
import { Button, Field, Modal, Section, StatusPill, formatDate } from "../ui";

export function PlatformControls() {
  const { currentUser, data } = useWorkspace(); const runtime = useRuntimeMode(); const locks = usePeriodLocks(); const notifications = useNotifications(); const { audit } = useAudit();
  const [switchOpen,setSwitchOpen]=useState(false); const [releaseId,setReleaseId]=useState<string|null>(null); const [releaseReason,setReleaseReason]=useState("");
  const [lockForm,setLockForm]=useState<{domain:PeriodLockDomain;startDate:string;endDate:string;reason:string}>({domain:"Payroll",startDate:"",endDate:"",reason:""});
  if (currentUser?.role !== "Administrator") return null;
  const activeLocks=locks.state.locks.filter((lock)=>!lock.releasedAt);
  const createLock=(event:FormEvent)=>{event.preventDefault();const id=locks.createLock(lockForm.domain,lockForm.startDate,lockForm.endDate,lockForm.reason);if(id)setLockForm({...lockForm,startDate:"",endDate:"",reason:""});};
  const confirmSwitch=()=>{runtime.setMode(runtime.mode==="demo"?"production":"demo");setSwitchOpen(false);};
  const release=()=>{if(releaseId&&locks.releaseLock(releaseId,releaseReason)){setReleaseId(null);setReleaseReason("");}};
  return <>
    <div className="platform-control-grid">
      <Section title="Runtime mode" description="Demo can be reset. Production mode cannot expose a reset control." action={<StatusPill tone={runtime.isDemo?"gold":"success"}>{runtime.isDemo?"Demo":"Production mode"}</StatusPill>}><div className="platform-mode-card"><Radio size={25}/><div><strong>{runtime.isDemo?"Safe demo environment":"Production-mode test environment"}</strong><p>{runtime.isDemo?"Fictional browser-local records with reset enabled.":"Reset is disabled. Live Firebase, payment, SMS/email and hosting credentials are still separate integrations."}</p></div><Button variant={runtime.isDemo?"primary":"secondary"} onClick={()=>setSwitchOpen(true)}>{runtime.isDemo?"Switch demo off":"Return to demo"}</Button></div></Section>
      <Section title="Audit coverage" description="Every top-level business record is diffed into source-linked change events"><div className="platform-metric-row"><div><ShieldCheck size={20}/><span><strong>{audit.events.length}</strong><small>audit events retained</small></span></div><div><LockKeyhole size={20}/><span><strong>Append only</strong><small>No user-facing delete action</small></span></div></div><p className="platform-note">The standalone build records actor, timestamp, record type, record ID, action, and changed fields. Firebase integration must make this server-side and immutable.</p></Section>
    </div>

    <Section title="Period locks" description="Closed payroll, accounting, and inventory periods reject later posting or release actions"><form className="form-grid period-lock-form" onSubmit={createLock}><Field label="Domain"><select value={lockForm.domain} onChange={(event)=>setLockForm({...lockForm,domain:event.target.value as PeriodLockDomain})}><option>Payroll</option><option>Accounting</option><option>Inventory</option></select></Field><Field label="Start date"><input type="date" required value={lockForm.startDate} onChange={(event)=>setLockForm({...lockForm,startDate:event.target.value})}/></Field><Field label="End date"><input type="date" required value={lockForm.endDate} onChange={(event)=>setLockForm({...lockForm,endDate:event.target.value})}/></Field><Field label="Reason"><input required minLength={4} value={lockForm.reason} onChange={(event)=>setLockForm({...lockForm,reason:event.target.value})} placeholder="Month-end close, payroll finalized…"/></Field><div className="field--full"><Button type="submit" icon={<LockKeyhole size={15}/>}>Lock period</Button></div></form><div className="period-lock-list">{activeLocks.map((lock)=><article key={lock.id}><span><LockKeyhole size={18}/></span><div><strong>{lock.domain}: {lock.startDate} to {lock.endDate}</strong><p>{lock.reason}</p><small>Locked {formatDate(lock.lockedAt,{month:"short",day:"numeric",hour:"numeric",minute:"2-digit"})}</small></div><Button size="sm" variant="secondary" icon={<UnlockKeyhole size={14}/>} onClick={()=>setReleaseId(lock.id)}>Release</Button></article>)}{activeLocks.length===0&&<div className="review-empty"><UnlockKeyhole size={24}/><p>No active closed periods.</p></div>}</div></Section>

    <Section title="Notification rules" description="In-app alerts are native now. Email and SMS can be enabled per user and will queue until a transport provider is integrated." action={<StatusPill tone="info">Escalate after {notifications.state.escalationHours}h</StatusPill>}><div className="notification-policy-row"><BellRing size={19}/><label>Unread escalation window <input type="number" min={1} max={168} value={notifications.state.escalationHours} onChange={(event)=>notifications.setEscalationHours(Number(event.target.value))}/> hours</label><span>Static web mode evaluates escalations whenever the workspace is open. Production integration should also run this server-side.</span></div><div className="notification-preference-list">{data.users.filter((user)=>user.role!=="Customer").map((user)=>{const preference=notifications.state.preferences.find((item)=>item.userId===user.id);if(!preference)return null;return <article key={user.id}><div><strong>{user.name}</strong><small>{user.role}</small></div><label><input type="checkbox" checked={preference.inApp} onChange={(event)=>notifications.updatePreference(user.id,{inApp:event.target.checked})}/> In app</label><label><input type="checkbox" checked={preference.email} onChange={(event)=>notifications.updatePreference(user.id,{email:event.target.checked})}/> Email</label><label><input type="checkbox" checked={preference.sms} onChange={(event)=>notifications.updatePreference(user.id,{sms:event.target.checked})}/> SMS</label><input className="notification-destination" value={preference.smsNumber??""} onChange={(event)=>notifications.updatePreference(user.id,{smsNumber:event.target.value})} placeholder="SMS number" disabled={!preference.sms}/><span className="transport-state"><Smartphone size={14}/> {preference.email||preference.sms?"External transport required":"In-app only"}</span></article>;})}</div></Section>

    <Modal open={switchOpen} title={runtime.isDemo?"Turn demo mode off?":"Return to demo mode?"} description={runtime.isDemo?"Production mode keeps the current local records but permanently hides demo reset until you switch back.":"Returning to demo mode re-enables the demo reset control."} onClose={()=>setSwitchOpen(false)} footer={<><Button variant="ghost" onClick={()=>setSwitchOpen(false)}>Cancel</Button><Button onClick={confirmSwitch}>{runtime.isDemo?"Enter production mode":"Enter demo mode"}</Button></>}><div className="reset-confirmation"><ShieldCheck size={24}/><p>{runtime.isDemo?"This does not connect Firebase, payments, email/SMS, or hosting automatically. It changes platform behavior and removes reset from production mode.":"No records are deleted by changing modes."}</p></div></Modal>
    <Modal open={Boolean(releaseId)} title="Release closed period?" description="A released lock permits later posting again. The release itself remains in audit history." onClose={()=>{setReleaseId(null);setReleaseReason("");}} footer={<><Button variant="ghost" onClick={()=>{setReleaseId(null);setReleaseReason("");}}>Keep locked</Button><Button onClick={release}>Release period</Button></>}><Field label="Release reason"><textarea rows={3} value={releaseReason} onChange={(event)=>setReleaseReason(event.target.value)} placeholder="Why is this period being reopened?"/></Field></Modal>
  </>;
}
