"use client";

import { BadgeDollarSign, CalendarRange, Plus, Target, TrendingUp } from "lucide-react";
import { FormEvent, useMemo, useState } from "react";
import { GoalMetric, GoalPeriod, canViewPerformanceRecord, goalProgress, monthlyBonusTracker, periodRange, resolvedGoalStatus } from "../../lib/performance-engine";
import { usePerformance } from "../../lib/performance-context";
import { useWorkspace } from "../../lib/workspace-context";
import { Button, Field, Modal, Section, StatusPill, formatDate, formatMoney } from "../ui";

const metrics:GoalMetric[]=["Paid cases","Completed appointments","Paid orders","New paid accounts","Collected revenue","Manual"];
const periods:GoalPeriod[]=["Weekly","Monthly","Quarterly"];
const tone=(status:string)=>status==="Achieved"?"success" as const:status==="Missed"||status==="Cancelled"?"danger" as const:"info" as const;
const metricUnit=(metric:GoalMetric)=>metric==="Paid cases"?"cases":metric==="Completed appointments"?"appointments":metric==="Paid orders"?"orders":metric==="New paid accounts"?"accounts":metric==="Collected revenue"?"dollars":"units";

export function DashboardPerformance(){
  const {data,currentUser}=useWorkspace();const{performance,createGoal,updateManualGoal}=usePerformance();
  const [open,setOpen]=useState(false);const[manualGoalId,setManualGoalId]=useState<string|null>(null);const[manualValue,setManualValue]=useState("");const[manualNote,setManualNote]=useState("");
  const [form,setForm]=useState<{period:GoalPeriod;metric:GoalMetric;title:string;target:string;note:string}>({period:"Weekly",metric:"Paid cases",title:"",target:"",note:""});
  const visibleGoals=useMemo(()=>performance.goals.filter((goal)=>canViewPerformanceRecord(currentUser,goal.userId,data)).sort((a,b)=>a.periodEnd.localeCompare(b.periodEnd)),[currentUser,data,performance.goals]);
  const ownGoals=visibleGoals.filter((goal)=>goal.userId===currentUser?.id&&resolvedGoalStatus(goal,data)!=="Cancelled").slice(0,6);
  const teamGoals=visibleGoals.filter((goal)=>goal.userId!==currentUser?.id&&resolvedGoalStatus(goal,data)==="Active");
  const bonus=currentUser?.role==="Sales Representative"?monthlyBonusTracker(data,currentUser.id):undefined;
  const submit=(event:FormEvent)=>{event.preventDefault();if(!currentUser||!form.target)return;const range=periodRange(form.period);createGoal({userId:currentUser.id,period:form.period,title:form.title.trim()||`${form.period} ${form.metric.toLowerCase()} goal`,metric:form.metric,target:Number(form.target),unit:metricUnit(form.metric),periodStart:range.start,periodEnd:range.end,manualValue:0,status:"Active",createdBy:currentUser.id,note:form.note.trim()||undefined});setOpen(false);setForm({period:"Weekly",metric:"Paid cases",title:"",target:"",note:""});};
  const saveManual=(event:FormEvent)=>{event.preventDefault();if(!manualGoalId)return;updateManualGoal(manualGoalId,Number(manualValue||0),manualNote.trim()||undefined);setManualGoalId(null);setManualValue("");setManualNote("");};
  if(!currentUser||currentUser.role==="Customer")return null;

  return <>
    <Section title="My goals" description="Weekly, monthly, and quarterly goals from Monday planning and ongoing performance." action={<Button size="sm" variant="secondary" icon={<Plus size={15}/>} onClick={()=>setOpen(true)}>Add goal</Button>}>
      <div className="bonus-ledger">{ownGoals.map((goal)=>{const progress=goalProgress(goal,data);const status=resolvedGoalStatus(goal,data);const percent=Math.min(100,Math.round(progress/Math.max(1,goal.target)*100));return <article key={goal.id}><div className="bonus-ledger__head"><div><small>{goal.period} · {goal.metric}</small><strong>{goal.title}</strong><p>{formatDate(goal.periodStart,{month:"short",day:"numeric"})} to {formatDate(goal.periodEnd,{month:"short",day:"numeric"})}</p></div><StatusPill tone={tone(status)}>{status}</StatusPill></div><div className="bonus-progress"><i style={{width:`${percent}%`}}/></div><div className="bonus-ledger__foot"><span>{goal.metric==="Collected revenue"?formatMoney(progress):`${progress} ${goal.unit}`}</span><span>Target {goal.metric==="Collected revenue"?formatMoney(goal.target):`${goal.target} ${goal.unit}`}</span><span>{percent}%</span></div>{goal.note&&<p className="bonus-rule-note">{goal.note}</p>}{goal.metric==="Manual"&&<Button size="sm" variant="ghost" onClick={()=>{setManualGoalId(goal.id);setManualValue(String(goal.manualValue));setManualNote(goal.note??"");}}>Update progress</Button>}</article>;})}{ownGoals.length===0&&<div className="review-empty"><Target size={25}/><h3>No active goals yet</h3><p>Add the goals you set during the weekly team meeting or for the month/quarter.</p></div>}</div>
    </Section>

    {bonus&&<Section title="Monthly sales bonus tracker" description={`${formatDate(bonus.start,{month:"long",day:"numeric"})} to ${formatDate(bonus.end,{month:"long",day:"numeric"})}. Earned values come from paid source orders.`}><div className="company-rule-facts"><div><span>Earned this month</span><strong>{formatMoney(bonus.earnedAmount)}</strong><small>{bonus.earned.length} earned milestone{bonus.earned.length===1?"":"s"}</small></div><div><span>Still in play</span><strong>{formatMoney(bonus.potentialAmount)}</strong><small>{bonus.pending.length} tracked milestone{bonus.pending.length===1?"":"s"}</small></div><div><span>Calculation</span><strong>Source linked</strong><small>Paid orders only</small></div><div><span>Payout cadence</span><strong>Monthly</strong><small>Tracked here; payroll release remains controlled</small></div></div><div className="bonus-ledger">{[...bonus.earned.map((item)=>item.signal),...bonus.pending].slice(0,5).map((signal)=>{const account=data.accounts.find((item)=>item.id===signal.accountId);const pct=Math.min(100,Math.round(signal.observedCases/Math.max(1,signal.thresholdCases)*100));return <article key={signal.id}><div className="bonus-ledger__head"><div><small>{signal.milestone}</small><strong>{account?.name??"Account"}</strong><p>{signal.ruleNote}</p></div><StatusPill tone={signal.status==="Earned"?"success":"warning"}>{signal.status}</StatusPill></div><div className="bonus-progress"><i style={{width:`${pct}%`}}/></div><div className="bonus-ledger__foot"><span>{signal.observedCases}/{signal.thresholdCases} cases</span><span>{formatMoney(signal.amount)}</span><span>{pct}%</span></div></article>;})}</div></Section>}

    {teamGoals.length>0&&<Section title="Team goal watch" description="Active goals for employees inside your management scope"><div className="activity-list">{teamGoals.slice(0,6).map((goal)=>{const user=data.users.find((item)=>item.id===goal.userId);const progress=goalProgress(goal,data);return <article key={goal.id}><span><TrendingUp size={16}/></span><div><strong>{user?.name}: {goal.title}</strong><p>{progress}/{goal.target} {goal.unit} · {goal.period}</p></div><small>{formatDate(goal.periodEnd,{month:"short",day:"numeric"})}</small></article>;})}</div></Section>}

    <Modal open={open} title="Add a performance goal" description="Goals can be weekly, monthly, or quarterly. Automatic metrics recalculate from source records." onClose={()=>setOpen(false)} footer={<><Button variant="ghost" onClick={()=>setOpen(false)}>Cancel</Button><Button type="submit" form="goal-form">Save goal</Button></>}><form id="goal-form" className="form-grid" onSubmit={submit}><Field label="Period"><select value={form.period} onChange={(event)=>setForm({...form,period:event.target.value as GoalPeriod})}>{periods.map((item)=><option key={item}>{item}</option>)}</select></Field><Field label="Metric"><select value={form.metric} onChange={(event)=>setForm({...form,metric:event.target.value as GoalMetric})}>{metrics.map((item)=><option key={item}>{item}</option>)}</select></Field><Field label="Goal name" hint="Optional; a clear default will be created"><input value={form.title} onChange={(event)=>setForm({...form,title:event.target.value})} placeholder="Example: August paid cases"/></Field><Field label="Target"><input required min="0" step="0.01" type="number" value={form.target} onChange={(event)=>setForm({...form,target:event.target.value})}/></Field><Field label="Context / commitment" className="field--full"><textarea rows={3} value={form.note} onChange={(event)=>setForm({...form,note:event.target.value})} placeholder="What will you do to hit this goal?"/></Field></form></Modal>

    <Modal open={Boolean(manualGoalId)} title="Update manual goal" description="Automatic goals do not need manual updates. This is only for a custom measure." onClose={()=>setManualGoalId(null)} footer={<><Button variant="ghost" onClick={()=>setManualGoalId(null)}>Cancel</Button><Button type="submit" form="manual-goal-form">Update</Button></>}><form id="manual-goal-form" className="form-grid" onSubmit={saveManual}><Field label="Current value"><input required min="0" step="0.01" type="number" value={manualValue} onChange={(event)=>setManualValue(event.target.value)}/></Field><Field label="Progress note" className="field--full"><textarea rows={3} value={manualNote} onChange={(event)=>setManualNote(event.target.value)}/></Field></form></Modal>
  </>;
}
